// The words of the public pages (server/site.mjs renders them): pricing, terms, privacy, refunds and contact, in English and
// Bahasa Indonesia. Written for a parent to read before signing up and for a payment provider to review before it lets the
// business take money, and written to match what the service actually does — every promise here is one the code keeps:
// SUBSCRIPTIONS.md for trials, grace and pauses, PRIVACY.md for what is held and for how long, support.mjs for deletion.
// A change to what the service does is a change to these words, and a change to the terms is a new TERMS_VERSION (site.mjs),
// which the sign-up records.
//
// Blocks: ['h2', text], ['p', text], ['ul', [text…]], ['table', { head, rows }], ['note', text], ['cta', { label, href }].
// Text may carry [label](/path) links and **bold**; addresses @automathtics.net become mailto links; everything else is escaped.
// Consumer-protection note for whoever edits this: Indonesian law voids standard clauses that refuse every refund or bind a
// consumer to changes made alone (UU 8/1999 art. 18), so refunds are listed by case, changes come with notice and a way out,
// and the Indonesian text prevails where the two differ (UU 24/2009 art. 31, Perpres 63/2019).

export function sitePages({ money, trial, updated, termsVersion, business }) {
  const m = money, t = trial;
  const businessLines = (lang) => [
    [lang === 'en' ? 'Operator' : 'Pengelola', business.legalName || business.brand],
    [lang === 'en' ? 'Address' : 'Alamat', business.address],
    [lang === 'en' ? 'Phone / WhatsApp' : 'Telepon / WhatsApp', business.phone],
    ['Email', business.email],
  ].filter(([, value]) => value).map(([label, value]) => `**${label}:** ${value}`);

  return {
    pricing: {
      en: {
        title: 'Pricing', kicker: 'AUTOMATHTICS · PRICING', intro: 'One price, set by how many children practise: paid monthly, or yearly for 20% less.',
        description: `AutoMathtics costs ${m.en(m.monthly(1))} a month for one child, ${m.en(m.monthly(2))} for two, ${m.en(m.monthly(3))} for three and ${m.en(m.monthly(4))} for four, or 20% less paid yearly. Free for every family until ${t.en.ends}.`,
        blocks: [
          ['table', { head: ['Children', 'Monthly', 'Yearly, 20% off'], rows: [1, 2, 3, 4].map((n) => [`${n} ${n === 1 ? 'child' : 'children'}`, m.en(m.monthly(n)), m.en(m.annual(n))]) }],
          ['note', 'Yearly is twelve months’ price less 20%, paid once a year. For five or more children, write to support@automathtics.net. Prices are in Indonesian rupiah and include any applicable taxes.'],
          ['h2', `Free until ${t.en.ends}`],
          ['p', `Every family can use AutoMathtics free from ${t.en.opens} until ${t.en.ends}. No payment details are needed. If you subscribe during the trial, the first payment is taken on ${t.en.firstCharge}.`],
          ['h2', 'Every plan includes'],
          ['ul', [
            'Both tracks for every child: **Engine**, papers of 25 questions through six sectors from addition to fractions, and **Navigator**, the same maths in words and pictures.',
            'A placement test, so each child starts at the right level.',
            'Grid coins to earn and spend in the shop, and reward points for rewards you set and approve.',
            'A progress email every week — or every month, or none: your choice.',
            'A pace you set for each child, and a log of every session.',
            'No advertising, ever, and nothing for a child to buy.',
          ]],
          ['h2', 'How billing works'],
          ['ul', [
            'Paid monthly or yearly in advance, and renewed automatically for the same period until you cancel.',
            'Cancel any time in Mission Control. You keep access until the end of the month or year you paid for.',
            'On a monthly plan you can pause for one to three months instead, and pay nothing while paused.',
            'Payments are processed securely by Xendit. The payment methods available are shown at checkout.',
          ]],
          ['p', 'The details are in the [Terms of Service](/terms) and the [Refund Policy](/refunds).'],
          ['cta', { label: 'Get started ▶', href: '/join' }],
        ],
      },
      id: {
        title: 'Harga', kicker: 'AUTOMATHTICS · HARGA', intro: 'Satu harga sesuai jumlah anak yang berlatih: dibayar bulanan, atau tahunan dengan hemat 20%.',
        description: `AutoMathtics ${m.id(m.monthly(1))} per bulan untuk satu anak, ${m.id(m.monthly(2))} untuk dua anak, ${m.id(m.monthly(3))} untuk tiga anak, dan ${m.id(m.monthly(4))} untuk empat anak, atau hemat 20% bila dibayar tahunan. Gratis untuk setiap keluarga sampai ${t.id.ends}.`,
        blocks: [
          ['table', { head: ['Jumlah anak', 'Bulanan', 'Tahunan, hemat 20%'], rows: [1, 2, 3, 4].map((n) => [`${n} anak`, m.id(m.monthly(n)), m.id(m.annual(n))]) }],
          ['note', 'Harga tahunan adalah harga dua belas bulan dikurangi 20%, dibayar sekali setahun. Untuk lima anak atau lebih, hubungi support@automathtics.net. Harga dalam rupiah dan sudah termasuk pajak yang berlaku.'],
          ['h2', `Gratis sampai ${t.id.ends}`],
          ['p', `Setiap keluarga dapat menggunakan AutoMathtics secara gratis mulai ${t.id.opens} sampai ${t.id.ends}. Tidak perlu data pembayaran. Jika Anda berlangganan selama uji coba, pembayaran pertama baru ditagih pada ${t.id.firstCharge}.`],
          ['h2', 'Setiap paket mencakup'],
          ['ul', [
            'Dua jalur untuk setiap anak: **Engine**, lembar berisi 25 soal melalui enam sektor dari penjumlahan sampai pecahan, dan **Navigator**, matematika yang sama dalam bentuk soal cerita dan gambar.',
            'Tes penempatan, agar setiap anak mulai dari level yang tepat.',
            'Grid coins untuk dikumpulkan dan dibelanjakan di toko, serta poin hadiah untuk hadiah yang Anda tentukan dan setujui.',
            'Email perkembangan setiap minggu — atau setiap bulan, atau tidak sama sekali: Anda yang memilih.',
            'Kecepatan soal yang Anda atur untuk setiap anak, dan catatan setiap sesi.',
            'Tanpa iklan, selamanya, dan tidak ada yang bisa dibeli oleh anak.',
          ]],
          ['h2', 'Cara penagihan'],
          ['ul', [
            'Dibayar di muka setiap bulan atau setiap tahun, dan diperpanjang otomatis untuk periode yang sama sampai Anda membatalkan.',
            'Batalkan kapan saja di Mission Control. Akses tetap berjalan sampai akhir bulan atau tahun yang sudah dibayar.',
            'Pada paket bulanan, Anda juga dapat menjeda selama satu sampai tiga bulan, tanpa pembayaran selama jeda.',
            'Pembayaran diproses dengan aman oleh Xendit. Metode pembayaran yang tersedia ditampilkan saat checkout.',
          ]],
          ['p', 'Rinciannya ada di [Syarat dan Ketentuan Layanan](/id/terms) dan [Kebijakan Pengembalian Dana](/id/refunds).'],
          ['cta', { label: 'Mulai sekarang ▶', href: '/join' }],
        ],
      },
    },

    terms: {
      en: {
        title: 'Terms of Service', kicker: 'AUTOMATHTICS · TERMS', intro: `Last updated ${updated.en}. Version ${termsVersion}.`,
        description: 'The agreement between a family and AutoMathtics: accounts, trials, subscriptions, cancelling and refunds.',
        blocks: [
          ['p', 'These terms are the agreement between you and the operator of AutoMathtics (“we”, “us”), whose details are on the [Contact](/contact) page. They apply when you create an account, and you agree to them by ticking the box when you sign up. The [Privacy Policy](/privacy) and the [Refund Policy](/refunds) are part of them.'],
          ['h2', '1. The service'],
          ['p', 'AutoMathtics is a maths practice web app for children, run by their parent. Children work through papers of questions on two tracks and earn coins and reward points inside the game; their parent follows their progress, sets their pace and chooses their rewards. It runs in a web browser at automathtics.net.'],
          ['h2', '2. Who may use it'],
          ['ul', [
            'An account is for an adult: you must be at least 18 years old and the parent or legal guardian of every child you add.',
            'Children do not have accounts. They play inside your family, through the profiles you create, and you are responsible for their use of the service.',
            'Children never buy anything. Only you can subscribe, and nothing in the game costs real money.',
          ]],
          ['h2', '3. Your account'],
          ['ul', [
            'Give accurate details, and keep your email address and mobile number up to date: we use them to secure the account and to contact you.',
            'Keep your password and the SMS codes we send private. We will never ask you for them.',
            'You are responsible for what happens under your account. Tell us at once at support@automathtics.net if you think someone else has used it.',
          ]],
          ['h2', '4. Free trials'],
          ['ul', [
            `The opening trial: every family has free access from ${t.en.opens} until ${t.en.ends}. No payment details are needed.`,
            'Each verified mobile number can have one free trial. This stays true when an account is deleted and made again: that number can subscribe, but it does not get another trial. The opening trial counts as that one trial.',
            'We may offer other trials, or stop offering them. Each offer shows its own terms.',
            'When a trial ends without a subscription, your children’s progress is kept, but play stops until you subscribe.',
          ]],
          ['h2', '5. Subscriptions and payment'],
          ['ul', [
            'Prices are on the [Pricing](/pricing) page, in Indonesian rupiah, and include any applicable taxes. The price depends on how many children are in your plan.',
            'A subscription is paid monthly or yearly in advance, as you choose, and renews automatically for the same period until you cancel. A yearly plan costs twelve months’ price less 20%.',
            `If you subscribe during the opening trial, the first payment is taken on ${t.en.firstCharge}, not before.`,
            'Payments are processed by our payment processor, Xendit. We never see or store your full card or account details.',
            'If a renewal payment fails, access continues for 7 days while you sort out the payment; after that, play is paused until a payment succeeds. If nothing is paid within a further 30 days, the subscription ends. Your children’s progress is kept throughout.',
            'Adding a child to your plan changes the monthly price. We show you the new price before you confirm.',
          ]],
          ['h2', '6. Price changes'],
          ['p', 'We may change our prices. We will tell you by email at least 30 days before a new price applies to you, and it applies only from your first payment after that notice. If you do not want to pay the new price, you can cancel before it applies.'],
          ['h2', '7. Cancelling and pausing'],
          ['ul', [
            'You can cancel at any time in Mission Control, under Cancel or pause. There is no cancellation fee.',
            'Cancelling stops the next renewal. You keep access until the end of the month or year you have paid for, and you are not charged again.',
            'When you cancel, we may offer you a discount to stay. You can take one such offer, once: offers cannot be combined with each other or with any other discount, and the yearly price is never reduced further.',
            'On a monthly plan you can pause instead, for one, two or three months. A pause takes no payment and gives no access beyond the month already paid for; the subscription carries on when the pause ends.',
            'Cancelling or pausing never deletes your children’s profiles or progress. To delete your data, see section 13.',
          ]],
          ['h2', '8. Refunds'],
          ['p', 'When a payment is refunded is set out in the [Refund Policy](/refunds). Nothing in these terms limits your rights under Indonesian consumer protection law.'],
          ['h2', '9. Coins, points and rewards'],
          ['ul', [
            'Grid coins, reward points and game items exist only inside AutoMathtics. They have no money value and cannot be bought, sold, transferred or exchanged for money.',
            'Rewards are set, approved and given by you. They are an arrangement between you and your child; we only keep the list and the requests.',
            'We may rebalance the game — shop prices, or what a pass earns — to keep it fair and working well.',
          ]],
          ['h2', '10. Fair use'],
          ['p', 'You agree not to:'],
          ['ul', [
            'use the service for anything unlawful, or for anyone but your own family;',
            'try to get into another family’s account or data, or into our systems;',
            'copy, scrape, resell or rebuild the service or its questions, or interfere with how it works;',
            'create accounts, or use different mobile numbers, to obtain repeated free trials.',
          ]],
          ['h2', '11. Our content'],
          ['p', 'The questions, stories, artwork, software and the name AutoMathtics belong to us or to those who license them to us. While your account is in good standing you may use them for your own family’s learning. Nothing else is licensed.'],
          ['h2', '12. Availability and changes to the service'],
          ['ul', [
            'We work to keep AutoMathtics available at all times, but it may occasionally be unavailable for maintenance or for reasons outside our control.',
            'We improve the service over time and may change or remove features. If a change significantly reduces what you pay for, we will tell you first, and you may cancel and receive a refund for the unused part of the period you paid for.',
            'AutoMathtics supports your child’s practice. It does not guarantee particular results, and it does not replace school.',
          ]],
          ['h2', '13. Ending your account'],
          ['ul', [
            'You can delete your family at any time in Mission Control. Deletion takes effect after 14 days and can be cancelled until then; any subscription is ended first. What is kept after deletion, and why, is in the [Privacy Policy](/privacy).',
            'We may suspend or close an account that seriously breaks these terms, puts others at risk or is used for fraud. We will tell you why, unless the law or security prevents it. If we close an account for any other reason, we refund the unused part of the period you paid for.',
          ]],
          ['h2', '14. Liability'],
          ['ul', [
            'We provide the service with reasonable care and skill.',
            'We are not liable for losses that were not reasonably foreseeable, or that were caused by events outside our reasonable control.',
            'As far as the law allows, our total liability to you is limited to the amount you paid us in the three months before the event that caused the loss.',
            'Nothing in these terms excludes or limits any liability, or any right you have as a consumer, that Indonesian law does not allow to be excluded or limited.',
          ]],
          ['h2', '15. Changes to these terms'],
          ['p', 'If we change these terms, we will tell you by email and in the app at least 14 days before the change applies, unless the law or security requires it sooner. We will ask you to accept important changes. If you do not agree with a change, you can cancel before it applies, and you will not be charged under the new terms.'],
          ['h2', '16. Law and disputes'],
          ['ul', [
            'These terms are governed by the laws of the Republic of Indonesia.',
            'If something goes wrong, please write to support@automathtics.net first. We aim to resolve every complaint within 14 days.',
            'If we cannot resolve it together, you may take the dispute to a Consumer Dispute Settlement Body (BPSK) or to a competent court in Indonesia, as Indonesian consumer protection law provides.',
          ]],
          ['h2', '17. Language'],
          ['p', 'These terms are made in Bahasa Indonesia and English. If the two versions differ, the Bahasa Indonesia version prevails.'],
          ['h2', '18. Contact'],
          ['p', 'support@automathtics.net · [Contact page](/contact)'],
        ],
      },
      id: {
        title: 'Syarat dan Ketentuan Layanan', kicker: 'AUTOMATHTICS · SYARAT', intro: `Terakhir diperbarui ${updated.id}. Versi ${termsVersion}.`,
        description: 'Perjanjian antara keluarga dan AutoMathtics: akun, uji coba, langganan, pembatalan, dan pengembalian dana.',
        blocks: [
          ['p', 'Syarat ini merupakan perjanjian antara Anda dan pengelola AutoMathtics (“kami”), yang rinciannya tercantum di halaman [Kontak](/id/contact). Syarat ini berlaku saat Anda membuat akun, dan Anda menyetujuinya dengan mencentang kotak persetujuan saat mendaftar. [Kebijakan Privasi](/id/privacy) dan [Kebijakan Pengembalian Dana](/id/refunds) merupakan bagian dari syarat ini.'],
          ['h2', '1. Layanan'],
          ['p', 'AutoMathtics adalah aplikasi web latihan matematika untuk anak yang dikelola oleh orang tuanya. Anak mengerjakan lembar soal dalam dua jalur serta mengumpulkan koin dan poin hadiah di dalam permainan; orang tua memantau perkembangannya, mengatur kecepatan soal, dan menentukan hadiahnya. Layanan ini berjalan di peramban web di automathtics.net.'],
          ['h2', '2. Siapa yang boleh menggunakan'],
          ['ul', [
            'Akun diperuntukkan bagi orang dewasa: Anda harus berusia minimal 18 tahun dan merupakan orang tua atau wali sah dari setiap anak yang Anda tambahkan.',
            'Anak tidak memiliki akun. Anak bermain di dalam keluarga Anda melalui profil yang Anda buat, dan Anda bertanggung jawab atas penggunaan layanan oleh mereka.',
            'Anak tidak pernah membeli apa pun. Hanya Anda yang dapat berlangganan, dan tidak ada apa pun di dalam permainan yang dibayar dengan uang sungguhan.',
          ]],
          ['h2', '3. Akun Anda'],
          ['ul', [
            'Berikan data yang benar, dan pastikan alamat email serta nomor ponsel Anda selalu terbaru: keduanya kami gunakan untuk mengamankan akun dan menghubungi Anda.',
            'Jaga kerahasiaan kata sandi dan kode SMS yang kami kirim. Kami tidak akan pernah memintanya.',
            'Anda bertanggung jawab atas segala aktivitas di akun Anda. Segera beri tahu kami di support@automathtics.net jika Anda menduga ada orang lain yang menggunakannya.',
          ]],
          ['h2', '4. Uji coba gratis'],
          ['ul', [
            `Uji coba pembukaan: setiap keluarga mendapat akses gratis mulai ${t.id.opens} sampai ${t.id.ends}. Tidak perlu data pembayaran.`,
            'Setiap nomor ponsel yang terverifikasi hanya berhak atas satu uji coba gratis. Ketentuan ini tetap berlaku walaupun akun dihapus lalu dibuat kembali: nomor tersebut dapat berlangganan, tetapi tidak mendapat uji coba lagi. Uji coba pembukaan dihitung sebagai uji coba tersebut.',
            'Kami dapat menawarkan uji coba lain, atau berhenti menawarkannya. Setiap penawaran menampilkan ketentuannya sendiri.',
            'Jika uji coba berakhir tanpa langganan, perkembangan anak Anda tetap tersimpan, tetapi permainan berhenti sampai Anda berlangganan.',
          ]],
          ['h2', '5. Langganan dan pembayaran'],
          ['ul', [
            'Harga tercantum di halaman [Harga](/id/pricing) dalam rupiah dan sudah termasuk pajak yang berlaku. Harga ditentukan oleh jumlah anak dalam paket Anda.',
            'Langganan dibayar di muka setiap bulan atau setiap tahun, sesuai pilihan Anda, dan diperpanjang otomatis untuk periode yang sama sampai Anda membatalkannya. Paket tahunan seharga dua belas bulan dikurangi 20%.',
            `Jika Anda berlangganan selama uji coba pembukaan, pembayaran pertama baru ditagih pada ${t.id.firstCharge}, tidak lebih awal.`,
            'Pembayaran diproses oleh pemroses pembayaran kami, Xendit. Kami tidak pernah melihat atau menyimpan data lengkap kartu atau rekening Anda.',
            'Jika pembayaran perpanjangan gagal, akses tetap berjalan selama 7 hari agar Anda dapat menyelesaikan pembayaran; setelah itu permainan dijeda sampai pembayaran berhasil. Jika tidak ada pembayaran dalam 30 hari berikutnya, langganan berakhir. Perkembangan anak Anda tetap tersimpan selama itu.',
            'Menambahkan anak ke paket Anda mengubah harga bulanan. Kami menampilkan harga barunya sebelum Anda mengonfirmasi.',
          ]],
          ['h2', '6. Perubahan harga'],
          ['p', 'Kami dapat mengubah harga. Kami akan memberi tahu Anda melalui email paling lambat 30 hari sebelum harga baru berlaku bagi Anda, dan harga baru hanya berlaku mulai pembayaran pertama setelah pemberitahuan tersebut. Jika Anda tidak ingin membayar harga baru, Anda dapat membatalkan langganan sebelum harga itu berlaku.'],
          ['h2', '7. Membatalkan dan menjeda'],
          ['ul', [
            'Anda dapat membatalkan kapan saja di Mission Control, pada menu Cancel or pause. Tidak ada biaya pembatalan.',
            'Pembatalan menghentikan perpanjangan berikutnya. Akses tetap berjalan sampai akhir bulan atau tahun yang sudah dibayar, dan Anda tidak ditagih lagi.',
            'Saat Anda membatalkan, kami dapat menawarkan potongan harga agar Anda tetap berlangganan. Penawaran seperti itu hanya dapat digunakan satu kali: penawaran tidak dapat digabungkan satu sama lain maupun dengan potongan lain, dan harga tahunan tidak pernah dipotong lagi.',
            'Pada paket bulanan, Anda dapat menjeda langganan selama satu, dua, atau tiga bulan sebagai gantinya. Selama jeda tidak ada pembayaran dan tidak ada akses melebihi bulan yang sudah dibayar; langganan berlanjut ketika masa jeda berakhir.',
            'Membatalkan atau menjeda tidak pernah menghapus profil maupun perkembangan anak Anda. Untuk menghapus data, lihat bagian 13.',
          ]],
          ['h2', '8. Pengembalian dana'],
          ['p', 'Kapan pembayaran dikembalikan diatur dalam [Kebijakan Pengembalian Dana](/id/refunds). Tidak ada ketentuan dalam syarat ini yang membatasi hak Anda berdasarkan hukum perlindungan konsumen Indonesia.'],
          ['h2', '9. Koin, poin, dan hadiah'],
          ['ul', [
            'Grid coins, poin hadiah, dan item permainan hanya ada di dalam AutoMathtics. Semuanya tidak memiliki nilai uang dan tidak dapat dibeli, dijual, dipindahtangankan, atau ditukar dengan uang.',
            'Hadiah ditentukan, disetujui, dan diberikan oleh Anda. Hadiah merupakan kesepakatan antara Anda dan anak Anda; kami hanya menyimpan daftar hadiah dan permintaannya.',
            'Kami dapat menyesuaikan keseimbangan permainan — harga di toko, atau jumlah yang didapat saat lulus — agar tetap adil dan berjalan baik.',
          ]],
          ['h2', '10. Penggunaan yang wajar'],
          ['p', 'Anda setuju untuk tidak:'],
          ['ul', [
            'menggunakan layanan untuk hal yang melanggar hukum, atau untuk selain keluarga Anda sendiri;',
            'mencoba masuk ke akun atau data keluarga lain, atau ke sistem kami;',
            'menyalin, mengambil data secara otomatis (scraping), menjual kembali, atau meniru layanan maupun soal-soalnya, atau mengganggu cara kerjanya;',
            'membuat akun, atau menggunakan nomor ponsel yang berbeda, untuk mendapatkan uji coba gratis berulang kali.',
          ]],
          ['h2', '11. Konten kami'],
          ['p', 'Soal, cerita, gambar, perangkat lunak, dan nama AutoMathtics adalah milik kami atau pihak yang memberikan lisensinya kepada kami. Selama akun Anda dalam keadaan baik, Anda boleh menggunakannya untuk pembelajaran keluarga Anda sendiri. Tidak ada lisensi lain yang diberikan.'],
          ['h2', '12. Ketersediaan dan perubahan layanan'],
          ['ul', [
            'Kami berupaya agar AutoMathtics selalu tersedia, tetapi sesekali layanan dapat tidak tersedia karena pemeliharaan atau hal di luar kendali kami.',
            'Kami terus menyempurnakan layanan dan dapat mengubah atau menghapus fitur. Jika suatu perubahan secara berarti mengurangi apa yang Anda bayar, kami akan memberi tahu Anda terlebih dahulu, dan Anda dapat membatalkan serta menerima pengembalian dana untuk bagian periode yang sudah dibayar dan belum digunakan.',
            'AutoMathtics mendukung latihan anak Anda. AutoMathtics tidak menjamin hasil tertentu dan tidak menggantikan sekolah.',
          ]],
          ['h2', '13. Mengakhiri akun'],
          ['ul', [
            'Anda dapat menghapus keluarga Anda kapan saja di Mission Control. Penghapusan berlaku 14 hari setelah diminta dan dapat dibatalkan sebelum itu; langganan yang berjalan diakhiri terlebih dahulu. Data yang tetap disimpan setelah penghapusan, beserta alasannya, dijelaskan dalam [Kebijakan Privasi](/id/privacy).',
            'Kami dapat menangguhkan atau menutup akun yang melanggar syarat ini secara serius, membahayakan pihak lain, atau digunakan untuk penipuan. Kami akan menyampaikan alasannya, kecuali dilarang oleh hukum atau demi keamanan. Jika kami menutup akun karena alasan lain, kami mengembalikan dana untuk bagian periode yang sudah dibayar dan belum digunakan.',
          ]],
          ['h2', '14. Tanggung jawab'],
          ['ul', [
            'Kami menyediakan layanan dengan kecermatan dan keahlian yang wajar.',
            'Kami tidak bertanggung jawab atas kerugian yang secara wajar tidak dapat diperkirakan, atau yang disebabkan oleh kejadian di luar kendali wajar kami.',
            'Sepanjang diizinkan oleh hukum, total tanggung jawab kami kepada Anda dibatasi sebesar jumlah yang Anda bayarkan kepada kami dalam tiga bulan sebelum kejadian yang menimbulkan kerugian.',
            'Tidak ada ketentuan dalam syarat ini yang mengecualikan atau membatasi tanggung jawab, atau hak Anda sebagai konsumen, yang menurut hukum Indonesia tidak boleh dikecualikan atau dibatasi.',
          ]],
          ['h2', '15. Perubahan syarat'],
          ['p', 'Jika kami mengubah syarat ini, kami akan memberi tahu Anda melalui email dan di dalam aplikasi paling lambat 14 hari sebelum perubahan berlaku, kecuali jika hukum atau keamanan mengharuskannya lebih cepat. Untuk perubahan penting, kami akan meminta persetujuan Anda. Jika Anda tidak setuju dengan suatu perubahan, Anda dapat membatalkan langganan sebelum perubahan berlaku, dan Anda tidak akan ditagih berdasarkan syarat yang baru.'],
          ['h2', '16. Hukum dan penyelesaian sengketa'],
          ['ul', [
            'Syarat ini tunduk pada hukum Negara Republik Indonesia.',
            'Jika ada masalah, silakan hubungi support@automathtics.net terlebih dahulu. Kami berupaya menyelesaikan setiap keluhan dalam 14 hari.',
            'Jika tidak dapat diselesaikan bersama, Anda dapat mengajukan sengketa ke Badan Penyelesaian Sengketa Konsumen (BPSK) atau pengadilan yang berwenang di Indonesia, sebagaimana diatur dalam hukum perlindungan konsumen Indonesia.',
          ]],
          ['h2', '17. Bahasa'],
          ['p', 'Syarat ini dibuat dalam Bahasa Indonesia dan Bahasa Inggris. Apabila terdapat perbedaan antara kedua versi, versi Bahasa Indonesia yang berlaku.'],
          ['h2', '18. Kontak'],
          ['p', 'support@automathtics.net · [Halaman Kontak](/id/contact)'],
        ],
      },
    },

    refunds: {
      en: {
        title: 'Refund Policy', kicker: 'AUTOMATHTICS · REFUNDS', intro: `Last updated ${updated.en}.`,
        description: 'When a payment to AutoMathtics is refunded, how to ask, and how the money comes back.',
        blocks: [
          ['p', 'This policy explains when a payment to AutoMathtics is refunded. It is part of the [Terms of Service](/terms), and it does not limit your rights under Indonesian consumer protection law.'],
          ['h2', 'Free trials'],
          ['p', `A free trial costs nothing, so there is nothing to refund. The opening trial (${t.en.opens} to ${t.en.ends}) needs no payment details at all.`],
          ['h2', 'Cancelling'],
          ['p', 'You can cancel at any time in Mission Control, under Cancel or pause. Cancelling stops the next renewal; you keep access until the end of the month or year you have paid for, and you are not charged again.'],
          ['h2', 'When we refund in full'],
          ['ul', [
            'You were charged twice for the same month.',
            'You were charged after your cancellation took effect.',
            'You were charged during a free trial, or before your subscription was due to start.',
            'You were charged a different amount from the price shown when you subscribed or last changed your plan. We refund the difference.',
            'A payment was made from your account without your permission. We will check what happened and help you secure the account.',
          ]],
          ['h2', 'When we refund the unused part of a period'],
          ['ul', [
            'AutoMathtics was unavailable to your family for more than 72 hours in total during any month you paid for, for reasons within our control.',
            'We stop providing the service, or significantly reduce what your plan includes.',
            'We close your account without a breach of the terms on your part.',
          ]],
          ['h2', 'Other requests'],
          ['p', 'Otherwise we do not usually refund part of a month or year that has already started, because your access continues to its end after you cancel. If something has gone wrong for you that this page does not cover, write to us anyway: we read every request and decide it fairly.'],
          ['h2', 'How to ask for a refund'],
          ['ul', [
            'Email support@automathtics.net from the email address on your account, within 30 days of the payment.',
            'Include the date and amount of the payment, and what went wrong.',
            'We reply within 2 working days and decide within 7 working days.',
          ]],
          ['h2', 'How refunds are paid'],
          ['ul', [
            'An approved refund goes back through Xendit to the payment method you used. Where that is not possible, we transfer it to a bank account in the name of the person who paid.',
            'We send the refund within 7 working days of approving it. When it reaches you depends on your bank, card issuer or e-wallet, and can take up to 14 more working days.',
          ]],
          ['h2', 'Payment disputes'],
          ['p', 'If you do not recognise a payment, or think it is wrong, please contact us first: most problems are solved faster that way. You keep every right to dispute a payment with your bank or payment provider.'],
        ],
      },
      id: {
        title: 'Kebijakan Pengembalian Dana', kicker: 'AUTOMATHTICS · PENGEMBALIAN DANA', intro: `Terakhir diperbarui ${updated.id}.`,
        description: 'Kapan pembayaran kepada AutoMathtics dikembalikan, cara mengajukannya, dan cara dana dikembalikan.',
        blocks: [
          ['p', 'Kebijakan ini menjelaskan kapan pembayaran kepada AutoMathtics dikembalikan. Kebijakan ini merupakan bagian dari [Syarat dan Ketentuan Layanan](/id/terms) dan tidak membatasi hak Anda berdasarkan hukum perlindungan konsumen Indonesia.'],
          ['h2', 'Uji coba gratis'],
          ['p', `Uji coba gratis tidak dikenai biaya, sehingga tidak ada yang perlu dikembalikan. Uji coba pembukaan (${t.id.opens} sampai ${t.id.ends}) sama sekali tidak memerlukan data pembayaran.`],
          ['h2', 'Membatalkan langganan'],
          ['p', 'Anda dapat membatalkan kapan saja di Mission Control, pada menu Cancel or pause. Pembatalan menghentikan perpanjangan berikutnya; akses tetap berjalan sampai akhir bulan atau tahun yang sudah dibayar, dan Anda tidak ditagih lagi.'],
          ['h2', 'Pengembalian dana penuh'],
          ['ul', [
            'Anda ditagih dua kali untuk bulan yang sama.',
            'Anda ditagih setelah pembatalan Anda berlaku.',
            'Anda ditagih selama uji coba gratis, atau sebelum langganan Anda seharusnya dimulai.',
            'Anda ditagih dengan jumlah yang berbeda dari harga yang ditampilkan saat Anda berlangganan atau terakhir mengubah paket. Kami mengembalikan selisihnya.',
            'Ada pembayaran dari akun Anda tanpa izin Anda. Kami akan memeriksa kejadiannya dan membantu Anda mengamankan akun.',
          ]],
          ['h2', 'Pengembalian dana untuk bagian periode yang belum digunakan'],
          ['ul', [
            'AutoMathtics tidak dapat digunakan oleh keluarga Anda lebih dari total 72 jam dalam bulan mana pun yang sudah dibayar, karena hal yang berada dalam kendali kami.',
            'Kami berhenti menyediakan layanan, atau mengurangi isi paket Anda secara berarti.',
            'Kami menutup akun Anda tanpa adanya pelanggaran syarat dari pihak Anda.',
          ]],
          ['h2', 'Permintaan lain'],
          ['p', 'Di luar hal di atas, kami biasanya tidak mengembalikan dana untuk bulan atau tahun yang sudah berjalan, karena akses Anda tetap berlanjut sampai akhirnya setelah Anda membatalkan. Jika Anda mengalami masalah yang tidak tercakup di halaman ini, tetap hubungi kami: setiap permintaan kami baca dan kami putuskan secara adil.'],
          ['h2', 'Cara mengajukan pengembalian dana'],
          ['ul', [
            'Kirim email ke support@automathtics.net dari alamat email akun Anda, paling lambat 30 hari setelah pembayaran.',
            'Sertakan tanggal dan jumlah pembayaran, serta masalah yang terjadi.',
            'Kami membalas dalam 2 hari kerja dan memberi keputusan dalam 7 hari kerja.',
          ]],
          ['h2', 'Cara dana dikembalikan'],
          ['ul', [
            'Pengembalian dana yang disetujui dikirim melalui Xendit ke metode pembayaran yang Anda gunakan. Jika tidak memungkinkan, kami mentransfernya ke rekening bank atas nama orang yang melakukan pembayaran.',
            'Kami mengirim pengembalian dana dalam 7 hari kerja setelah disetujui. Kapan dana diterima bergantung pada bank, penerbit kartu, atau dompet digital Anda, dan dapat memakan waktu hingga 14 hari kerja tambahan.',
          ]],
          ['h2', 'Sengketa pembayaran'],
          ['p', 'Jika Anda tidak mengenali suatu pembayaran, atau merasa ada yang salah, silakan hubungi kami terlebih dahulu: sebagian besar masalah lebih cepat selesai dengan cara ini. Hak Anda untuk mengajukan sanggahan pembayaran kepada bank atau penyedia pembayaran tetap berlaku sepenuhnya.'],
        ],
      },
    },

    privacy: {
      en: {
        title: 'Privacy Policy', kicker: 'AUTOMATHTICS · PRIVACY', intro: `Last updated ${updated.en}.`,
        description: 'What AutoMathtics collects about parents and children, why, who handles it, how long it is kept, and your rights.',
        blocks: [
          ['p', 'This policy explains what AutoMathtics collects about you and your children, why, who else handles it, how long we keep it and what you can do about it. It is written to meet Indonesia’s Personal Data Protection Law (Law No. 27 of 2022). The operator of AutoMathtics, whose details are on the [Contact](/contact) page, is the controller of this data.'],
          ['h2', 'In short'],
          ['ul', [
            'Children have no account. A child’s profile holds a nickname, an icon, an age, a year level, a PIN and their progress — never an email address, phone number, photo or full date of birth.',
            'We collect only what the service needs, and use it only to run the service.',
            'No advertising, no analytics or advertising trackers, and we never sell or rent your data.',
            'You can download your family’s data, and delete it, at any time from Mission Control.',
          ]],
          ['h2', 'What we collect'],
          ['ul', [
            '**Your account.** Your email address and password, and your mobile number for the SMS security code. These are held by our sign-in provider, Google Firebase Authentication. We keep only a coded fingerprint of your number (a keyed hash, which cannot be turned back into the number), so that each number gets one free trial.',
            '**Your family.** The family name you choose, its time zone, your subscription status, your email choices, and a record of the consents you gave and when.',
            '**Each child.** A nickname and icon, an age and year level (to choose a starting point), a PIN (stored only in scrambled form), and their learning: the questions answered, results and times, coins, points, shop items, the rewards you set and the requests for them.',
            '**Payments.** Your plan, prices, payment dates and status, and the references our payment processor gives us. Card and account details are handled by Xendit; we never see or store them.',
            '**What you send us.** Feedback from the app, emails to our addresses, and — only if you choose to write one — the reason you give when you cancel.',
            '**The waiting list.** If you join it: your email address, when you joined, and a short tag naming the post that brought you (for example “ig”).',
            '**Security records.** When your account signs in and when important actions happen, and technical details of requests to our servers, such as IP address and browser type, used to protect the service from abuse.',
          ]],
          ['h2', 'Why we use it'],
          ['ul', [
            '**To provide the service you signed up for**: your account, your family, your children’s practice and progress, and your subscription (performing our agreement with you).',
            '**To keep accounts secure**: the second check by SMS, account recovery, and limits on repeated attempts (our legitimate interest, and yours, in security).',
            '**To prevent abuse**: one free trial per mobile number (our legitimate interest).',
            '**To write to you**: account and security messages, and progress reports as often as you choose (your agreement at sign-up); news and offers only if you ticked that box (your consent, which you can withdraw at any time).',
            '**To keep the financial records the law requires** (legal obligation).',
            '**To improve AutoMathtics**, using totals and averages across many families — never a report about one family or one child (our legitimate interest).',
          ]],
          ['h2', 'Children'],
          ['p', 'Children’s data is collected with the consent of the parent or legal guardian who creates the child’s profile, as the law requires. Children never enter contact details, cannot send messages to anyone and are never shown advertising. Inside a family, a child can see the other children’s nicknames on the Family Rocket; no other family ever sees them.'],
          ['h2', 'Who handles it for us'],
          ['p', 'We use these providers to run AutoMathtics. They process data only on our instructions and under their own data protection terms:'],
          ['ul', [
            '**Google** (Firebase, Google Cloud and Google Sheets): sign-in, our database and our servers; reCAPTCHA, the “I’m not a robot” check on SMS steps; and the spreadsheet in which we read the waiting list.',
            '**Xendit**: payment processing, in Indonesia.',
            '**Resend**: sending our emails, in the United States.',
            '**Cloudflare**: our domain name, and forwarding the emails sent to our addresses.',
            '**Proton**: our mailbox, in Switzerland.',
          ]],
          ['p', 'We share data with authorities only when the law requires it. We never sell data, and never share it for advertising.'],
          ['h2', 'Data outside Indonesia'],
          ['p', 'Some of these providers store or process data outside Indonesia, including in Singapore, the United States and Switzerland. When data leaves Indonesia, we rely on providers bound by data protection commitments, as Indonesian law requires.'],
          ['h2', 'How long we keep it'],
          ['ul', [
            '**Your family, children and progress**: until you delete the family. Deletion takes effect 14 days after you ask, and can be cancelled until then.',
            '**Your sign-in account**: until you delete it, which you can do once the family is gone. The sign-in provider then removes your email address, password and mobile number.',
            '**The trial record**: the coded fingerprint of your mobile number stays after deletion, so that a number gets only one free trial. It cannot be turned back into your number.',
            '**Payment records**: kept after deletion for as long as the law requires for financial and tax records.',
            '**Security and activity records, feedback and cancellation reasons**: 400 days. The words you wrote in a cancellation reason are removed when your family is deleted.',
            '**Account recovery requests**: 60 days after they can be completed.',
            '**The waiting list**: 400 days after you last joined, or until you use the unsubscribe link. Our spreadsheet copy is rewritten from the list, so an address that leaves the list leaves the copy too.',
            '**Server logs**: 30 days, then deleted automatically.',
          ]],
          ['h2', 'Your rights'],
          ['p', 'Under Indonesian law you can:'],
          ['ul', [
            'see the data we hold about you, and get a copy of it;',
            'have incorrect data corrected;',
            'have your data deleted, and withdraw a consent you gave;',
            'restrict or object to how we use it;',
            'take your data to another service, in a common machine-readable format.',
          ]],
          ['p', 'Most of this is in the app: in **Mission Control** you can download your family’s data, change your email choices and your mobile number, and delete your family or your sign-in account. For anything else, email support@automathtics.net from your account’s address; we may need to confirm it is you. If you are not satisfied with our answer, you can complain to Indonesia’s personal data protection authority.'],
          ['h2', 'Cookies and device storage'],
          ['p', 'AutoMathtics uses one cookie, and it is a necessary one: **__session** keeps you signed in and protects forms against forgery. It is ours alone, cannot be read by scripts on the page, and ends with your session.'],
          ['p', 'The app also keeps a few small notes in your browser’s own storage, which never leave your device:'],
          ['ul', [
            'whether this device was handed over to the kids, so feedback cannot be sent from a child’s device;',
            'whether you chose “Remember this device”, as a coded tag of your email address rather than the address itself;',
            'when SMS codes were last sent to a number, to show the countdown before the next one;',
            'which “How to” guides a child has already seen on this device;',
            'that this device has been used with AutoMathtics before, so it opens at sign-in rather than at our introduction.',
          ]],
          ['p', 'On SMS steps, Google’s reCAPTCHA check may set its own cookies to tell people from bots. We use no analytics, advertising or social media trackers, which is why there is no cookie banner. Clearing your browser’s site data removes everything above; you will then need to sign in again.'],
          ['h2', 'Security'],
          ['p', 'Passwords are handled by our sign-in provider and never stored by us. Every account has a second check by SMS, children’s PINs are stored only in scrambled form, every connection is encrypted, and every action our staff take on an account is recorded. If a breach puts your data at risk, we will tell you and the authorities as the law requires.'],
          ['h2', 'Changes'],
          ['p', 'If we change this policy in a way that matters, we will tell you by email and in the app before the change applies.'],
          ['h2', 'Contact'],
          ['p', 'support@automathtics.net · [Contact page](/contact)'],
        ],
      },
      id: {
        title: 'Kebijakan Privasi', kicker: 'AUTOMATHTICS · PRIVASI', intro: `Terakhir diperbarui ${updated.id}.`,
        description: 'Data orang tua dan anak yang dikumpulkan AutoMathtics, untuk apa, siapa yang memprosesnya, berapa lama disimpan, dan hak Anda.',
        blocks: [
          ['p', 'Kebijakan ini menjelaskan data apa yang dikumpulkan AutoMathtics tentang Anda dan anak-anak Anda, untuk apa, siapa saja yang turut memprosesnya, berapa lama data disimpan, dan apa yang dapat Anda lakukan. Kebijakan ini disusun untuk memenuhi Undang-Undang Nomor 27 Tahun 2022 tentang Pelindungan Data Pribadi. Pengelola AutoMathtics, yang rinciannya tercantum di halaman [Kontak](/id/contact), adalah pengendali data pribadi ini.'],
          ['h2', 'Ringkasnya'],
          ['ul', [
            'Anak tidak memiliki akun. Profil anak hanya berisi nama panggilan, ikon, usia, jenjang kelas, PIN, dan perkembangan belajarnya — tidak pernah alamat email, nomor telepon, foto, atau tanggal lahir lengkap.',
            'Kami hanya mengumpulkan data yang dibutuhkan layanan, dan hanya menggunakannya untuk menjalankan layanan.',
            'Tanpa iklan, tanpa pelacak analitik atau iklan, dan kami tidak pernah menjual atau menyewakan data Anda.',
            'Anda dapat mengunduh data keluarga, dan menghapusnya, kapan saja dari Mission Control.',
          ]],
          ['h2', 'Data yang kami kumpulkan'],
          ['ul', [
            '**Akun Anda.** Alamat email dan kata sandi, serta nomor ponsel untuk kode keamanan SMS. Data ini disimpan oleh penyedia layanan masuk kami, Google Firebase Authentication. Kami hanya menyimpan sidik kode dari nomor Anda (hash berkunci yang tidak dapat diubah kembali menjadi nomor), agar setiap nomor hanya mendapat satu uji coba gratis.',
            '**Keluarga Anda.** Nama keluarga yang Anda pilih, zona waktunya, status langganan, pilihan email Anda, serta catatan persetujuan yang Anda berikan beserta waktunya.',
            '**Setiap anak.** Nama panggilan dan ikon, usia dan jenjang kelas (untuk menentukan titik awal), PIN (disimpan hanya dalam bentuk teracak), serta data belajarnya: soal yang dijawab, hasil dan waktunya, koin, poin, item toko, hadiah yang Anda tentukan, dan permintaan hadiah.',
            '**Pembayaran.** Paket, harga, tanggal dan status pembayaran, serta nomor referensi dari pemroses pembayaran kami. Data kartu dan rekening ditangani oleh Xendit; kami tidak pernah melihat atau menyimpannya.',
            '**Yang Anda kirim kepada kami.** Masukan dari aplikasi, email ke alamat kami, dan — hanya jika Anda memilih untuk menuliskannya — alasan yang Anda berikan saat membatalkan.',
            '**Daftar tunggu.** Jika Anda bergabung: alamat email, waktu bergabung, dan label singkat yang menunjukkan unggahan yang membawa Anda (misalnya “ig”).',
            '**Catatan keamanan.** Waktu akun Anda masuk dan saat tindakan penting dilakukan, serta rincian teknis permintaan ke server kami, seperti alamat IP dan jenis peramban, untuk melindungi layanan dari penyalahgunaan.',
          ]],
          ['h2', 'Untuk apa data digunakan'],
          ['ul', [
            '**Menyediakan layanan yang Anda daftarkan**: akun, keluarga, latihan dan perkembangan anak, serta langganan Anda (pelaksanaan perjanjian dengan Anda).',
            '**Menjaga keamanan akun**: pemeriksaan kedua melalui SMS, pemulihan akun, dan pembatasan percobaan berulang (kepentingan sah kami, dan Anda, atas keamanan).',
            '**Mencegah penyalahgunaan**: satu uji coba gratis per nomor ponsel (kepentingan sah kami).',
            '**Mengirim email kepada Anda**: pesan akun dan keamanan, serta laporan perkembangan sesering yang Anda pilih (persetujuan Anda saat mendaftar); berita dan penawaran hanya jika Anda mencentang kotaknya (persetujuan yang dapat Anda tarik kapan saja).',
            '**Menyimpan catatan keuangan yang diwajibkan oleh hukum** (kewajiban hukum).',
            '**Menyempurnakan AutoMathtics**, menggunakan total dan rata-rata dari banyak keluarga — tidak pernah laporan tentang satu keluarga atau satu anak (kepentingan sah kami).',
          ]],
          ['h2', 'Anak-anak'],
          ['p', 'Data anak dikumpulkan dengan persetujuan orang tua atau wali sah yang membuat profil anak, sebagaimana diwajibkan oleh hukum. Anak tidak pernah memasukkan data kontak, tidak dapat mengirim pesan kepada siapa pun, dan tidak pernah ditampilkan iklan. Di dalam satu keluarga, anak dapat melihat nama panggilan anak lain di Family Rocket; keluarga lain tidak pernah dapat melihatnya.'],
          ['h2', 'Pihak yang memproses data untuk kami'],
          ['p', 'Kami menggunakan penyedia berikut untuk menjalankan AutoMathtics. Mereka memproses data hanya sesuai instruksi kami dan berdasarkan ketentuan pelindungan data mereka:'],
          ['ul', [
            '**Google** (Firebase, Google Cloud, dan Google Sheets): layanan masuk, basis data, dan server kami; reCAPTCHA, pemeriksaan “I’m not a robot” pada langkah SMS; serta spreadsheet tempat kami membaca daftar tunggu.',
            '**Xendit**: pemrosesan pembayaran, di Indonesia.',
            '**Resend**: pengiriman email kami, di Amerika Serikat.',
            '**Cloudflare**: nama domain kami, dan penerusan email yang dikirim ke alamat kami.',
            '**Proton**: kotak surat kami, di Swiss.',
          ]],
          ['p', 'Kami hanya membagikan data kepada otoritas jika diwajibkan oleh hukum. Kami tidak pernah menjual data, dan tidak pernah membagikannya untuk iklan.'],
          ['h2', 'Data di luar Indonesia'],
          ['p', 'Sebagian penyedia tersebut menyimpan atau memproses data di luar Indonesia, termasuk di Singapura, Amerika Serikat, dan Swiss. Saat data keluar dari Indonesia, kami menggunakan penyedia yang terikat komitmen pelindungan data, sebagaimana disyaratkan oleh hukum Indonesia.'],
          ['h2', 'Berapa lama data disimpan'],
          ['ul', [
            '**Keluarga, anak, dan perkembangan belajar**: sampai Anda menghapus keluarga. Penghapusan berlaku 14 hari setelah diminta dan dapat dibatalkan sebelum itu.',
            '**Akun masuk Anda**: sampai Anda menghapusnya, yang dapat dilakukan setelah keluarga dihapus. Penyedia layanan masuk kemudian menghapus alamat email, kata sandi, dan nomor ponsel Anda.',
            '**Catatan uji coba**: sidik kode nomor ponsel Anda tetap disimpan setelah penghapusan, agar satu nomor hanya mendapat satu uji coba gratis. Sidik kode ini tidak dapat diubah kembali menjadi nomor Anda.',
            '**Catatan pembayaran**: tetap disimpan setelah penghapusan selama diwajibkan oleh hukum untuk catatan keuangan dan perpajakan.',
            '**Catatan keamanan dan aktivitas, masukan, serta alasan pembatalan**: 400 hari. Kata-kata yang Anda tulis dalam alasan pembatalan dihapus saat keluarga Anda dihapus.',
            '**Permintaan pemulihan akun**: 60 hari setelah dapat diselesaikan.',
            '**Daftar tunggu**: 400 hari setelah terakhir kali Anda bergabung, atau sampai Anda menggunakan tautan berhenti berlangganan. Salinan di spreadsheet kami ditulis ulang dari daftar ini, sehingga alamat yang keluar dari daftar juga hilang dari salinannya.',
            '**Log server**: 30 hari, lalu terhapus otomatis.',
          ]],
          ['h2', 'Hak Anda'],
          ['p', 'Berdasarkan hukum Indonesia, Anda berhak:'],
          ['ul', [
            'melihat data yang kami simpan tentang Anda, dan mendapatkan salinannya;',
            'meminta data yang keliru diperbaiki;',
            'meminta data Anda dihapus, dan menarik persetujuan yang telah Anda berikan;',
            'membatasi atau menolak cara kami menggunakan data;',
            'memindahkan data Anda ke layanan lain dalam format yang umum dan dapat dibaca mesin.',
          ]],
          ['p', 'Sebagian besar hak ini tersedia di aplikasi: di **Mission Control** Anda dapat mengunduh data keluarga, mengubah pilihan email dan nomor ponsel, serta menghapus keluarga atau akun masuk Anda. Untuk hal lain, kirim email ke support@automathtics.net dari alamat email akun Anda; kami mungkin perlu memastikan bahwa itu memang Anda. Jika Anda tidak puas dengan jawaban kami, Anda dapat mengajukan pengaduan kepada lembaga pelindungan data pribadi Indonesia.'],
          ['h2', 'Cookie dan penyimpanan perangkat'],
          ['p', 'AutoMathtics menggunakan satu cookie, dan cookie itu memang diperlukan: **__session** menjaga Anda tetap masuk dan melindungi formulir dari pemalsuan. Cookie ini hanya milik kami, tidak dapat dibaca oleh skrip di halaman, dan berakhir bersama sesi Anda.'],
          ['p', 'Aplikasi juga menyimpan beberapa catatan kecil di penyimpanan peramban Anda sendiri, yang tidak pernah keluar dari perangkat:'],
          ['ul', [
            'apakah perangkat ini sudah diserahkan kepada anak, agar masukan tidak dapat dikirim dari perangkat anak;',
            'apakah Anda memilih “Remember this device”, sebagai label berkode dari alamat email Anda, bukan alamat itu sendiri;',
            'kapan kode SMS terakhir dikirim ke suatu nomor, untuk menampilkan hitungan mundur sebelum kode berikutnya;',
            'panduan “How to” mana yang sudah dilihat anak di perangkat ini;',
            'bahwa perangkat ini pernah digunakan dengan AutoMathtics, agar aplikasi langsung membuka layar masuk dan bukan halaman perkenalan.',
          ]],
          ['p', 'Pada langkah SMS, pemeriksaan reCAPTCHA dari Google dapat memasang cookie-nya sendiri untuk membedakan manusia dari bot. Kami tidak menggunakan pelacak analitik, iklan, atau media sosial, karena itulah tidak ada banner cookie. Menghapus data situs di peramban akan menghapus semua catatan di atas; setelah itu Anda perlu masuk kembali.'],
          ['h2', 'Keamanan'],
          ['p', 'Kata sandi ditangani oleh penyedia layanan masuk kami dan tidak pernah kami simpan. Setiap akun memiliki pemeriksaan kedua melalui SMS, PIN anak disimpan hanya dalam bentuk teracak, setiap koneksi dienkripsi, dan setiap tindakan staf kami terhadap suatu akun dicatat. Jika terjadi kebocoran yang membahayakan data Anda, kami akan memberi tahu Anda dan otoritas sebagaimana diwajibkan oleh hukum.'],
          ['h2', 'Perubahan'],
          ['p', 'Jika kami mengubah kebijakan ini secara berarti, kami akan memberi tahu Anda melalui email dan di dalam aplikasi sebelum perubahan berlaku.'],
          ['h2', 'Kontak'],
          ['p', 'support@automathtics.net · [Halaman Kontak](/id/contact)'],
        ],
      },
    },

    contact: {
      en: {
        title: 'Contact', kicker: 'AUTOMATHTICS · CONTACT', intro: 'Write to us about anything to do with your account, your payments or your family’s data.',
        description: 'How to reach AutoMathtics about accounts, billing, refunds, payment disputes and privacy.',
        blocks: [
          ['h2', 'Email'],
          ['p', '**support@automathtics.net** — billing, refunds, payment disputes, privacy and data requests, and help with your account. We reply within 2 working days (Monday to Friday, Jakarta time).'],
          ['h2', 'In the app'],
          ['p', 'Every parent screen has **Send feedback** at the bottom. It reaches the same people, and tells us which screen you were on.'],
          ['h2', 'Lost your phone?'],
          ['p', 'If you can no longer receive the SMS code, use **I can’t receive the code** on the sign-in screen. Recovery takes seven days by design, so that nobody else can take over your account.'],
          ['h2', 'The business'],
          ['ul', businessLines('en')],
          ['p', 'We will never ask you for your password or an SMS code.'],
        ],
      },
      id: {
        title: 'Kontak', kicker: 'AUTOMATHTICS · KONTAK', intro: 'Hubungi kami untuk segala hal tentang akun, pembayaran, atau data keluarga Anda.',
        description: 'Cara menghubungi AutoMathtics tentang akun, tagihan, pengembalian dana, sengketa pembayaran, dan privasi.',
        blocks: [
          ['h2', 'Email'],
          ['p', '**support@automathtics.net** — tagihan, pengembalian dana, sengketa pembayaran, permintaan terkait privasi dan data, serta bantuan akun. Kami membalas dalam 2 hari kerja (Senin sampai Jumat, waktu Jakarta).'],
          ['h2', 'Di dalam aplikasi'],
          ['p', 'Setiap layar orang tua memiliki tombol **Send feedback** di bagian bawah. Pesan Anda sampai ke tim yang sama, beserta keterangan layar tempat Anda mengirimnya.'],
          ['h2', 'Kehilangan ponsel?'],
          ['p', 'Jika Anda tidak lagi dapat menerima kode SMS, gunakan **I can’t receive the code** di layar masuk. Pemulihan akun memang memerlukan tujuh hari, agar tidak ada orang lain yang dapat mengambil alih akun Anda.'],
          ['h2', 'Usaha'],
          ['ul', businessLines('id')],
          ['p', 'Kami tidak akan pernah meminta kata sandi atau kode SMS Anda.'],
        ],
      },
    },
  };
}
