// 🦬 DC-MOON — practice modelled on the AMC 8 (the American Mathematics Competitions 8, Mathematical Association of America,
// Washington DC); not affiliated. The owner's eighth moon (19 Sep 2026): the American paper a Year 4–6 child can actually sit —
// Grade 8 and below, taken in Indonesia through the MAA's international group leader. Twenty-five multiple-choice problems with
// five options in forty minutes, no penalty for a wrong answer, difficulty climbing with the problem number: the first five
// foundational, the last five the real test. Geometry is the biggest slice across a decade of papers, then word problems and
// counting, then number theory and algebra (olympia-research.md §8). A heat is ten of them, five options each, in three
// climbing bands; Year 4 sits the warm-up and the middle, Years 5–6 the closing problems too.
import { ri, pick, shuffle, sum, thing, money, int, frac, mcOnly, withFigure, grid, bars, buildHeat, slots, factorsOf, digitsOf, lcm, cap } from './common.mjs';

const choose = (n, k) => { let r = 1; for (let i = 1; i <= k; i++) r = (r * (n - k + i)) / i; return Math.round(r); };
const DAYS = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];

// ---- warm-up (problems 1–5 of the real paper): one clean step ----
const unitPrice = () => { const per = pick([3, 4, 5, 6]), price = ri(2, 9), n = per * ri(2, 6); return int('word problems · rates', `A shop sells ${thing()}s at ${per} for ${money(price)}. How much do ${n} cost, in dollars?`, (n / per) * price); };
const percentOf = () => { const p = pick([10, 20, 25, 30, 40, 50, 60, 75]), t = pick([40, 60, 80, 120, 200, 240]); if ((t * p) % 100) return null; return int('percentages', `What is ${p}% of ${t}?`, (t * p) / 100); };
const meanOf = () => { const xs = Array.from({ length: pick([4, 5]) }, () => ri(3, 40)), t = sum(xs); if (t % xs.length) return null; return int('statistics · mean', `What is the mean (average) of ${xs.join(', ')}?`, t / xs.length); };
const orderOps = () => { const a = ri(2, 9), b = ri(2, 9), c = ri(2, 9), d = ri(1, 9); return int('arithmetic · order of operations', `What is the value of ${a} + ${b} × ${c} − ${d}?`, a + b * c - d); };
const consecutive = () => { const n = pick([3, 4, 5]), first = ri(4, 40), s = n * first + (n * (n - 1)) / 2; return int('algebra · consecutive numbers', `The sum of ${n} consecutive whole numbers is ${s}. What is the largest of them?`, first + n - 1); };
const perimeterQ = () => { const l = ri(4, 30), w = ri(2, l - 1); return int('geometry · perimeter', `A rectangle has an area of ${l * w} square units and a width of ${w} units. What is its perimeter?`, 2 * (l + w)); };
const timeToFill = () => { const rate = pick([3, 4, 5, 6, 8]), mins = ri(4, 15); return int('word problems · rates', `A tap fills a tank at ${rate} litres a minute. How many minutes does it take to fill a ${rate * mins}-litre tank?`, mins); };
const fractionOfFraction = () => { const [a, b] = pick([[1, 2], [1, 3], [2, 3], [3, 4], [1, 4], [2, 5]]), [c, d] = pick([[1, 2], [2, 3], [3, 4], [3, 5], [4, 5]]); return frac('fractions', `What is ${a}/${b} of ${c}/${d}? Give the answer in its simplest form.`, a * c, b * d); };
// ---- middle (problems 6–15): two steps, a trap or a model ----
const percentTrap = () => { const p = pick([100, 200, 400, 500]), up = pick([10, 20, 25, 50]); const after = (p * (100 + up) / 100) * ((100 - up) / 100); if (!Number.isInteger(after)) return null; return int('percentages · up then down', `The price of a bag is ${money(p)}. It is raised by ${up}% and then the new price is cut by ${up}%. What is the final price, in dollars?`, after); };
const ratioQ = () => { const a = ri(2, 5), b = ri(a + 1, 9), u = ri(3, 12); return int('ratio', `The ratio of boys to girls in a choir is ${a} : ${b}. There are ${b * u} girls. How many children are in the choir?`, (a + b) * u); };
const divisorsCount = () => { const n = pick([36, 48, 60, 72, 84, 90, 96, 100, 120, 144]); return int('number theory · divisors', `How many positive divisors does ${n} have?`, factorsOf(n).length); };
const unitsDigit = () => { const base = pick([2, 3, 7, 8, 9]), cyc = { 2: [2, 4, 8, 6], 3: [3, 9, 7, 1], 7: [7, 9, 3, 1], 8: [8, 4, 2, 6], 9: [9, 1] }[base], n = ri(20, 99); const v = cyc[(n - 1) % cyc.length]; return int('number theory · units digit', `What is the units digit of ${base}^${n} (${base} to the power ${n})?`, v, { decoys: shuffle([0, 1, 2, 3, 4, 5, 6, 7, 8, 9].filter((d) => d !== v)).slice(0, 4) }); }; // a units digit is a digit: the decoys are too
const lcmWords = () => { const a = pick([4, 6, 8, 9, 10, 12]), b = pick([6, 8, 9, 10, 14, 15]); if (a === b) return null; return int('number theory · LCM', `Two runners circle a track: one lap takes ${a} minutes for the first and ${b} minutes for the second. They start together. After how many minutes are they next at the start together?`, lcm(a, b)); };
const digitsAllOdd = () => { const k = pick([2, 3]), from = pick([1, 5, 7]); const n = from === 1 ? 5 ** k : k === 2 ? 20 : 100; // digits odd, or the first digit fixed
  return int('counting · digits', from === 1 ? `How many ${k}-digit whole numbers have all their digits odd?` : `How many ${k}-digit whole numbers start with ${from} and have all their other digits even?`, n); };
const handshakes = () => { const n = ri(6, 14); return int('counting · handshakes', `${n} people at a meeting each shake hands exactly once with everyone else. How many handshakes take place?`, (n * (n - 1)) / 2); };
const rectanglesInGrid = () => { const r = ri(2, 3), c = ri(3, 5); return withFigure(int('counting · geometry', `How many rectangles of every size (squares included) are there in this ${r} by ${c} grid of unit squares?`, choose(r + 1, 2) * choose(c + 1, 2)), grid('Count the rectangles', r, c)); };
const triangleInRect = () => { const A = ri(6, 40) * 2; return int('geometry · area', `A triangle has one side along the bottom of a rectangle of area ${A}, and its top vertex on the top side of the rectangle. What is the area of the triangle?`, A / 2); };
const polygonAngles = () => { const [name, n] = pick([['pentagon', 5], ['hexagon', 6], ['octagon', 8], ['decagon', 10]]); return int('geometry · angles', `What is the sum of the interior angles of a ${name}, in degrees?`, (n - 2) * 180); };
const pythagoras = () => { const [a, b, c] = pick([[3, 4, 5], [6, 8, 10], [5, 12, 13], [9, 12, 15], [8, 15, 17]]), k = pick([1, 1, 2]); if (ri(1, 2) === 1) return int('geometry · right triangles', `A right triangle has legs of ${a * k} and ${b * k}. How long is its hypotenuse?`, c * k); return int('geometry · right triangles', `A right triangle has a hypotenuse of ${c * k} and one leg of ${a * k}. How long is the other leg?`, b * k); };
const median5 = () => { const xs = Array.from({ length: 5 }, () => ri(2, 50)).sort((p, q) => p - q); return int('statistics · median', `What is the median of ${shuffle(xs).join(', ')}?`, xs[2]); };
const dayAfter = () => { const d = ri(0, 6), n = ri(30, 200), r = (d + n) % 7; return mcOnly('logic · calendar', `Today is ${DAYS[d]}. What day of the week will it be ${n} days from today?`, DAYS[r], shuffle(DAYS.filter((_, i) => i !== r)).slice(0, 4)); };
const circleArea = () => { const r = ri(3, 12); return mcOnly('geometry · circles', `What is the area of a circle of radius ${r}?`, `${r * r}π`, [`${2 * r}π`, `${r * r * 2}π`, `${r * r}`, `${(r + 1) * (r + 1)}π`]); };
const barChartQ = () => { const labels = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'], vals = labels.map(() => ri(2, 12) * 5), what = pick(['tickets sold', 'books borrowed', 'laps run']), t = sum(vals); if (t % 5) return null; return withFigure(int('statistics · graphs', `The bar chart shows the ${what} on five days. What is the mean per day?`, t / 5), bars(cap(what), null, labels.map((l, i) => [l, vals[i]]))); };
// ---- closing (problems 16–25): the real test ----
const diceSum = () => { const t = ri(4, 10); let n = 0; for (let a = 1; a <= 6; a++) for (let b = 1; b <= 6; b++) if (a + b === t) n++; return frac('probability · dice', `Two fair dice are rolled. What is the probability that the two numbers add up to ${t}? Give a fraction in its simplest form.`, n, 36); };
const twoMarbles = () => { const r = ri(2, 5), b = ri(2, 5), n = r + b; return frac('probability · without replacement', `A bag holds ${r} red and ${b} blue marbles. Two are drawn without looking, one after the other and not put back. What is the probability that both are red? Give a fraction in its simplest form.`, r * (r - 1), n * (n - 1)); };
const arrangements = () => { if (ri(1, 2) === 1) { const n = ri(4, 6); return int('counting · arrangements', `In how many different orders can ${n} different books be arranged on a shelf?`, [1, 1, 2, 6, 24, 120, 720][n]); } const n = ri(5, 8); return int('counting · committees', `A committee of 3 is chosen from ${n} students. How many different committees are possible?`, choose(n, 3)); };
const paths = () => { const [r, c] = pick([[3, 3], [3, 4], [2, 5], [4, 4], [2, 4]]); return withFigure(int('counting · paths', `Moving only right or down along the grid lines, how many different paths lead from corner A to corner B of this ${r} by ${c} grid?`, choose(r + c, r)), grid('Paths from A to B', r, c, { '0,0': 'A', [`${r - 1},${c - 1}`]: 'B' })); };
const lShape = () => { const L = ri(8, 20), W = ri(6, 14), l = ri(2, L - 3), w = ri(2, W - 3); return int('geometry · composite area', `An L-shaped region is a ${L} by ${W} rectangle with a ${l} by ${w} rectangle removed from one corner. What is its area?`, L * W - l * w); };
const inclusionExclusion = () => { const n = ri(30, 50), both = ri(4, 12), onlyA = ri(5, 14), onlyB = ri(5, 14), neither = n - both - onlyA - onlyB; if (neither < 1) return null; return int('counting · inclusion-exclusion', `Of ${n} students, ${onlyA + both} take art, ${onlyB + both} take band, and ${neither} take neither. How many take both?`, both); };
const meanShift = () => { const n = ri(4, 8), avg = ri(10, 40), x = ri(avg + 1, avg + 30), newAvg = (n * avg + x) / (n + 1); if (!Number.isInteger(newAvg)) return null; return int('statistics · mean', `The mean of ${n} numbers is ${avg}. When the number ${x} is added to the list, what is the new mean?`, newAvg); };
const workBack = () => { const x = ri(5, 40), k = pick([2, 3, 4]), a = ri(3, 20); return int('algebra · working backwards', `A number is multiplied by ${k}, then ${a} is added, and the result is doubled to give ${2 * (k * x + a)}. What is the number?`, x); };
const remainders = () => { const a = pick([3, 4, 5]), b = pick([5, 7]); if (a === b) return null; const ra = ri(1, a - 1), rb = ri(1, b - 1); let N = 1; while (N % a !== ra || N % b !== rb) N++; return int('number theory · remainders', `What is the smallest positive integer that leaves a remainder of ${ra} when divided by ${a} and a remainder of ${rb} when divided by ${b}?`, N); };
const clockAngle = () => { const h = ri(1, 11), m = pick([0, 30]), angle = Math.abs(30 * h - 5.5 * m); return int('geometry · clock angles', `What is the smaller angle between the hour hand and the minute hand of a clock at ${h}:${m === 0 ? '00' : '30'}, in degrees?`, Math.min(angle, 360 - angle)); };
const speedAverage = () => { const d = pick([60, 120, 180, 240]), v1 = pick([30, 40, 60]), v2 = pick([20, 30, 40, 60]); if (v1 === v2) return null; const avg = (2 * v1 * v2) / (v1 + v2); if (!Number.isInteger(avg)) return null; return int('word problems · average speed', `A car drives ${d} km at ${v1} km/h and returns the same ${d} km at ${v2} km/h. What is its average speed for the whole trip, in km/h?`, avg); };
const digitSumCount = () => { const s = ri(5, 14); let n = 0; for (let k = 10; k <= 99; k++) if (sum(digitsOf(k)) === s) n++; return int('number theory · digits', `How many two-digit whole numbers have digits that add up to ${s}?`, n); };

const E = [['rates', unitPrice], ['percent', percentOf], ['mean', meanOf], ['order of operations', orderOps], ['consecutive', consecutive], ['perimeter', perimeterQ], ['filling', timeToFill], ['fractions', fractionOfFraction]];
const M = [['percent trap', percentTrap], ['ratio', ratioQ], ['divisors', divisorsCount], ['units digit', unitsDigit], ['LCM', lcmWords], ['odd digits', digitsAllOdd], ['handshakes', handshakes], ['rectangles', rectanglesInGrid], ['triangle in rectangle', triangleInRect], ['polygon angles', polygonAngles], ['Pythagoras', pythagoras], ['median', median5], ['calendar', dayAfter], ['circle', circleArea], ['bar chart', barChartQ]];
const H = [['dice', diceSum], ['two marbles', twoMarbles], ['arrangements', arrangements], ['paths', paths], ['L-shape', lShape], ['inclusion-exclusion', inclusionExclusion], ['mean shift', meanShift], ['working backwards', workBack], ['remainders', remainders], ['clock angles', clockAngle], ['average speed', speedAverage], ['digit sums', digitSumCount]];
// Year 4's closing band is the middle kinds again; Years 5–6 get the real closing problems
const pool = (y) => [...E.map(([cat, gen]) => ({ cat, gen, sections: ['E'] })), ...M.map(([cat, gen]) => ({ cat, gen, sections: y <= 4 ? ['M', 'H'] : ['M'] })), ...(y >= 5 ? H.map(([cat, gen]) => ({ cat, gen, sections: ['H'] })) : [])];
const SHAPE = slots([['E', 'mc', 4], ['M', 'mc', 3], ['H', 'mc', 3]]);
export const heat = (year) => buildHeat(SHAPE, pool(year), year, { options: 5 });
export const TOPICS = [
  { band: 'Grade 4 · problems 1–15', lines: ['warm-up: unit prices, percentages, means, order of operations', 'consecutive numbers, perimeter from area, fractions of fractions', 'middle: ratios, divisors, units digits, handshakes, rectangles in a grid', 'Pythagorean triples, polygon angles, calendars, circles in terms of π'] },
  { band: 'Grades 5–6 · the full paper', lines: ['all of Grade 4 for the first seven', 'closing: dice and marbles as fractions, arrangements and committees', 'paths on a grid, L-shaped areas, inclusion-exclusion, shifting means', 'remainders, clock angles, average speed there and back'] },
];
