// 🐉🐘 The OCEC family — what HK-Moon (HKIMO) and BKK-Moon (TIMO) share (olympia-research.md §5, §7 and the addendum). The real
// heats are twins: five categories — Logical Thinking, Arithmetic, Number Theory, Geometry, Combinatorics — five short answers
// each, four marks each, ninety minutes, no calculators, and at primary the answer is mostly a whole number (a few fractions,
// and at P1–P2 the odd word answer, occur on the real papers). The official sample papers are one template with the numbers
// changed and the 2025 heat papers spread evenly over the five areas, so the "HKIMO leans on number theory, TIMO on logic"
// split below is OUR differentiation, not the competitions' (the source check of 20 Sep 2026). The categories live here once,
// every kind tagged, and each moon's heat prefers its own tags: two questions a category, all typed answers, in the syllabus's
// own progression by primary year.
import { ri, pick, shuffle, sum, names, thing, int, withFigure, grid, buildHeat, slots, isPrime, factorsOf, digitsOf, gcd, lcm, ord } from './common.mjs';

const choose = (n, k) => { let r = 1; for (let i = 1; i <= k; i++) r = (r * (n - k + i)) / i; return Math.round(r); };
const fact = (n) => (n <= 1 ? 1 : n * fact(n - 1));
const COLOURS = ['red', 'blue', 'green', 'yellow', 'white', 'black'];
const OBJECTS = [['ball', 'cube', 'marble'], ['apple', 'pear', 'plum'], ['brick', 'block', 'bead'], ['jar', 'can', 'coin']]; // regular plurals only: an "s" is added

// ---- Logical Thinking ----
const balance = (y) => {
  const [a, b, c] = pick(OBJECTS), p = ri(2, y <= 2 ? 4 : 6), q = ri(2, y <= 2 ? 3 : 5);
  if (y <= 3) return int('logical thinking · balance', `On a balance, 1 ${a} weighs the same as ${p} ${b}s, and 1 ${b} weighs the same as ${q} ${c}s. How many ${c}s weigh the same as 1 ${a}?`, p * q);
  const k = ri(2, 4), n = ri(2, 3); // k a's = kp b's, so one a is p b's
  return int('logical thinking · balance', `On a balance, ${k} ${a}s weigh the same as ${k * p} ${b}s, and 1 ${b} weighs the same as ${q} ${c}s. How many ${c}s weigh the same as ${n} ${a}s?`, n * p * q);
};
const guessTwoDigit = () => { const t = ri(3, 9), u = ri(0, t - 1); return int('logical thinking · guessing a number', `A two-digit number has digits that add up to ${t + u}. Its tens digit is ${t - u} more than its ones digit. What is the number?`, 10 * t + u); };
const guessFourDigit = () => {
  const h = pick([2, 3]), th = 2 * h, t = 3 * h, o = t - 5;
  // the digit sum pins the number: without it 4261 and 6394 both fit the clues (the source check of 20 Sep 2026)
  return int('logical thinking · guessing a number', `In a four-digit number, the thousands digit is twice the hundreds digit, the tens digit is the sum of the thousands and hundreds digits, the ones digit is 5 less than the tens digit, and the four digits add up to ${th + h + t + o}. What is the number?`, 1000 * th + 100 * h + 10 * t + o);
};
const periodic = (y) => {
  const p = ri(3, y <= 3 ? 4 : 6), cs = shuffle(COLOURS).slice(0, p), counts = cs.map(() => ri(1, y <= 3 ? 2 : 3)), cycle = cs.flatMap((c, i) => Array(counts[i]).fill(c)), L = cycle.length, n = ri(y <= 3 ? 15 : 40, y <= 3 ? 40 : 120);
  const kind = y >= 4 && Math.random() < 0.5 ? 2 : 1;
  const words = `Beads are threaded in a repeating pattern: ${cycle.join(', ')}, and then the pattern repeats.`;
  if (kind === 1) { const col = cycle[(n - 1) % L]; const cnt = Math.floor(n / L) * counts[cs.indexOf(col)] + cycle.slice(0, n % L).filter((c) => c === col).length; return int('logical thinking · periodic problems', `${words} How many ${col} beads are there among the first ${n} beads?`, cnt); }
  const target = pick(cs), k = ri(3, y <= 4 ? 8 : 20); // the position of the k-th bead of that colour
  let seen = 0, pos = 0; while (seen < k) { pos++; if (cycle[(pos - 1) % L] === target) seen++; }
  return int('logical thinking · periodic problems', `${words} In which position is the ${ord(k)} ${target} bead?`, pos);
};
const pigeonhole = (y) => {
  const cs = shuffle(COLOURS).slice(0, y <= 3 ? 2 : 3), counts = cs.map(() => ri(4, 12)), it = pick(['sock', 'marble', 'ball']);
  const kind = y >= 5 ? ri(1, 3) : ri(1, 2);
  const bag = cs.map((c, i) => `${counts[i]} ${c}`).join(', ').replace(/, ([^,]*)$/, ' and $1');
  if (kind === 1) return int('logical thinking · pigeonhole', `A drawer has ${bag} ${it}s, all mixed up. In the dark, what is the smallest number of ${it}s you must take to be sure of two of the same colour?`, cs.length + 1);
  if (kind === 2) { const i = ri(0, cs.length - 1); return int('logical thinking · pigeonhole', `A drawer has ${bag} ${it}s, all mixed up. In the dark, what is the smallest number of ${it}s you must take to be sure of one ${cs[i]} ${it}?`, sum(counts) - counts[i] + 1); }
  const m = ri(3, 4); return int('logical thinking · pigeonhole', `A drawer has ${bag} ${it}s, all mixed up. In the dark, what is the smallest number of ${it}s you must take to be sure of ${m} of the same colour?`, (m - 1) * cs.length + 1);
};
const chickenRabbit = (y) => { const c = ri(4, y <= 4 ? 14 : 30), r = ri(3, y <= 4 ? 10 : 24), [one, other, a, b] = pick([['chickens', 'rabbits', 2, 4], ['bicycles', 'cars', 2, 4], ['spiders', 'beetles', 8, 6]]); return int('logical thinking · chicken and rabbit', `A yard holds only ${one} and ${other}: ${c + r} heads and ${c * a + r * b} legs altogether. How many ${other} are there?`.replace('legs', one === 'bicycles' ? 'wheels' : 'legs').replace('heads', one === 'bicycles' ? 'vehicles' : 'heads'), r); };
const speed = (y) => {
  const kind = ri(1, 3);
  if (kind === 1) { const v = pick([40, 50, 60, 80, 90]), t = ri(2, 5); return int('logical thinking · speed', `A train travels at ${v} km/h. How far does it go in ${t} hours, in km?`, v * t); }
  if (kind === 2) { const v1 = pick([40, 50, 60, 80]), v2 = pick([30, 40, 70, 90]), t = ri(2, 7); return int('logical thinking · speed', `Two towns are ${(v1 + v2) * t} km apart. A car leaves one at ${v1} km/h and a van leaves the other at ${v2} km/h at the same time, driving toward each other. After how many hours do they meet?`, t); }
  const v = pick([4, 5, 6]), t = ri(2, 4), back = pick([2, 3]), dist = v * t; if (dist % back || t <= back) return null; // cycling back must be faster than walking there
  return int('logical thinking · speed', `${names(1)[0]} walks to a lake at ${v} km/h in ${t} hours and cycles back the same way in ${back} hours. What is the cycling speed, in km/h?`, dist / back);
};
const ages = (y) => {
  const t = pick([3, 4, 5, 6, 8, 9, 10, 12, 15]), [k, m] = pick([[3, 2], [4, 2], [4, 3], [5, 3], [5, 2], [6, 4], [7, 4]]);
  const x = (t * (m - 1)) / (k - m); if (!Number.isInteger(x) || k * x < x + 18 || k * x > x + 45) return null; // now: child x, mother kx; in t years mother is m times — and a mother 18 to 45 years older, not 5 or 120 (the source check)
  return int('logical thinking · ages', `A mother is ${k} times as old as her ${pick(['son', 'daughter'])}. In ${t} years she will be ${m} times as old. How old is the child now?`, x);
};
const daysBetween = (y) => { const months = [['March', 31], ['April', 30], ['May', 31], ['June', 30], ['July', 31], ['August', 31], ['September', 30], ['October', 31]]; const i = ri(0, months.length - 2), d1 = ri(1, 25), d2 = ri(1, 28); const days = months[i][1] - d1 + d2; return int('logical thinking · dates', `How many days are there from ${d1} ${months[i][0]} to ${d2} ${months[i + 1][0]} of the same year, counting both days?`, days + 1); };
const rowsOfDots = (y) => { const a = ri(1, 4), k = ri(1, 3), n = ri(4, y <= 2 ? 6 : 10); return int('logical thinking · figure patterns', `Row 1 of a figure has ${a} dot${a === 1 ? '' : 's'}, row 2 has ${a + k}, row 3 has ${a + 2 * k}, and each row has ${k} more than the one before. How many dots are there in the first ${n} rows altogether?`, n * a + (k * n * (n - 1)) / 2); };
const pairsCount = (y) => { const a = ri(2, y <= 2 ? 4 : 6), b = ri(2, y <= 2 ? 5 : 8), [x, z] = pick([['shirts', 'hats'], ['drinks', 'snacks'], ['roads into town', 'roads out of it'], ['kinds of bread', 'fillings']]); return int('combinatorics · pairs', `${names(1)[0]} has ${a} ${x} and ${b} ${z}. How many different ways are there to choose one of each?`, a * b); };
const largestWithDigitSum = (y) => { const s = ri(3, 17), t = Math.min(9, s), o = s - t; if (o > 9) return null; return int('number theory · digit sums', `What is the largest two-digit number whose digits add up to ${s}?`, 10 * t + o); };
// ---- Arithmetic ----
const smartAdd = (y) => {
  if (y <= 2) { const pairs = shuffle([[19, 21], [38, 12], [27, 13], [46, 14], [35, 25], [18, 22], [44, 16], [29, 11]]).slice(0, 2).flat(); return int('arithmetic · smart addition', `${shuffle(pairs).join(' + ')} = ?`, sum(pairs)); }
  const base = pick([98, 99, 97, 995, 996]), k = ri(3, 6); return int('arithmetic · smart addition', `${Array(k).fill(base).join(' + ')} = ?`, base * k);
};
const gauss = (y) => {
  if (y <= 4) { const n = y === 3 ? pick([10, 20, 30]) : pick([50, 100]); return int('arithmetic · Gaussian addition', `1 + 2 + 3 + … + ${n} = ?`, (n * (n + 1)) / 2); }
  const a = ri(2, 9), d = pick([3, 4, 5, 6, 7]), n = ri(10, 30), last = a + (n - 1) * d; return int('arithmetic · Gaussian addition', `${a} + ${a + d} + ${a + 2 * d} + … + ${last} = ?`, (n * (a + last)) / 2);
};
const smartFourDigit = () => { const kind = ri(1, 3); if (kind === 1) return int('arithmetic · smart calculation', '9999 + 999 + 99 + 9 = ?', 11106); if (kind === 2) { const a = ri(1000, 9999), b = 10000 - a + ri(0, 999); return int('arithmetic · smart calculation', `${a} + ${b} = ?`, a + b); } const n = ri(1001, 4999); return int('arithmetic · smart calculation', `${n} + 9999 = ?`, n + 9999); };
const multiplyTrick = () => { const kind = ri(1, 3); if (kind === 1) { const a = pick([4, 8, 16, 32]); return int('arithmetic · smart calculation', `25 × ${a} × 125 = ?`, 25 * a * 125); } if (kind === 2) { const a = ri(3, 9); return int('arithmetic · smart calculation', `999 × ${a} = ?`, 999 * a); } const a = ri(11, 19), b = ri(11, 19); return int('arithmetic · 3-digit multiplication', `${a * 10} × ${b} = ?`, a * 10 * b); };
const geometricSum = () => { const kind = ri(1, 2); if (kind === 1) { const n = ri(6, 10); return int('arithmetic · sum of a geometric sequence', `1 + 2 + 4 + 8 + … + ${2 ** n} = ?`, 2 ** (n + 1) - 1); } const n = ri(4, 6); return int('arithmetic · sum of a geometric sequence', `1 + 3 + 9 + … + ${3 ** n} = ?`, (3 ** (n + 1) - 1) / 2); };
const squaresSum = () => { const n = ri(5, 12); return int('arithmetic · sum of squares', `1² + 2² + 3² + … + ${n}² = ?`, (n * (n + 1) * (2 * n + 1)) / 6); };
const decimalTrick = () => { const kind = ri(1, 2); if (kind === 1) { const a = ri(13, 99); return int('arithmetic · decimals', `0.25 × ${a} × 4 = ?`, a); } const a = ri(2, 9); return int('arithmetic · decimals', `0.5 × ${a * 2} × 12.5 × 8 = ?`, a * 100); };
const fractionChain = () => { const n = ri(3, 6), num = 2 ** n - 1, den = 2 ** n, terms = n <= 4 ? Array.from({ length: n }, (_, i) => `1/${2 ** (i + 1)}`).join(' + ') : `1/2 + 1/4 + 1/8 + … + 1/${den}`; return int('arithmetic · fractions', `${terms} is a fraction a/b in its simplest form. What is a + b?`, num + den); };
const missingDigit = (y) => { const A = ri(1, 9), a = ri(0, 9), b = ri(10, y <= 2 ? 50 : 89), s = 10 * A + a + b; return int('arithmetic · missing digit', `In the sum ▢${a} + ${b} = ${s}, what digit is ▢?`, A, { read: `A two-digit number with ones digit ${a} plus ${b} makes ${s}. What is its tens digit?` }); };
// ---- Number Theory ----
const evenOddCount = (y) => { const a = ri(1, 20), n = ri(10, y <= 2 ? 30 : 60), b = a + n, even = Math.random() < 0.5; let c = 0; for (let k = a; k <= b; k++) if ((k % 2 === 0) === even) c++; return int('number theory · odd and even', `How many ${even ? 'even' : 'odd'} numbers are there from ${a} to ${b}, counting both?`, c); };
const digitCount = (y) => { const d = ri(1, 9), n = y <= 3 ? pick([50, 60, 80, 100]) : pick([100, 150, 200]); let c = 0; for (let k = 1; k <= n; k++) c += digitsOf(k).filter((x) => x === d).length; return int('number theory · digits', `When the whole numbers from 1 to ${n} are written down, how many times is the digit ${d} written?`, c); };
const primesQ = (y) => { const kind = ri(1, 3); if (kind === 1) { const lo = pick([10, 20, 30, 40, 50, 60]), hi = lo + pick([10, 20, 30]); let n = 0; for (let k = lo + 1; k < hi; k++) if (isPrime(k)) n++; return int('number theory · primes', `How many prime numbers are there between ${lo} and ${hi}?`, n); } if (kind === 2) { const n = ri(30, 120); let p = n - 1; while (!isPrime(p)) p--; return int('number theory · primes', `What is the largest prime number less than ${n}?`, p); } const lo = pick([10, 20, 30]), hi = lo + 10; let s = 0; for (let k = lo + 1; k < hi; k++) if (isPrime(k)) s += k; return int('number theory · primes', `What is the sum of all the prime numbers between ${lo} and ${hi}?`, s); };
const lcmHcf = () => { const kind = ri(1, 3); if (kind === 1) { const a = pick([4, 6, 8, 9, 10, 12, 15]), b = pick([6, 8, 9, 10, 12, 14, 18]); if (a === b) return null; return int('number theory · LCM', `Two lights flash every ${a} seconds and every ${b} seconds. They flash together now. After how many seconds do they next flash together?`, lcm(a, b)); } if (kind === 2) { const g = pick([6, 8, 12, 15]), a = g * pick([2, 3, 5]), b = g * pick([3, 4, 7]); if (a === b) return null; return int('number theory · HCF', `What is the highest common factor of ${a} and ${b}?`, gcd(a, b)); } const g = pick([4, 6, 9, 12]), a = g * pick([2, 3, 5]), b = g * pick([4, 7]); return int('number theory · HCF', `Ribbons of ${a} cm and ${b} cm are cut into pieces of the same length, as long as possible, with nothing left over. How long is each piece, in cm?`, gcd(a, b)); };
const divisibility = (y) => { const kind = ri(1, 3); if (kind === 1) { const d = pick([3, 9]), a = ri(1, 9), b = ri(0, 9), c = ri(0, 9); let x = 0; while ((a + b + c + x) % d !== 0) x++; return int('number theory · divisibility', `What is the smallest digit that can replace ▢ so that ${a}${b}${c}▢ is divisible by ${d}?`, x, { read: `What is the smallest digit that can go on the end of ${a}${b}${c} so the number is divisible by ${d}?` }); } if (kind === 2) { const d = pick([6, 7, 8, 9, 12]), n = pick([100, 200, 300]); return int('number theory · divisibility', `How many multiples of ${d} are there from 1 to ${n}?`, Math.floor(n / d)); } const a = pick([3, 4, 5]), b = pick([4, 5, 6, 7]); if (a === b) return null; const n = pick([100, 200, 300]); return int('number theory · divisibility', `How many whole numbers from 1 to ${n} are divisible by ${a} but not by ${b}?`, Math.floor(n / a) - Math.floor(n / lcm(a, b))); };
const factorsCount = () => { const n = pick([36, 48, 60, 72, 84, 90, 96, 100, 120, 144, 180, 200, 240, 360, 720]); return int('number theory · number of factors', `How many positive factors does ${n} have?`, factorsOf(n).length); };
const factorsSum = () => { const n = pick([12, 18, 20, 24, 28, 30, 36, 40, 45, 48]); return int('number theory · sum of factors', `What is the sum of all the positive factors of ${n}?`, sum(factorsOf(n))); };
const unitDigit = () => { const base = pick([2, 3, 4, 7, 8, 9]), cyc = { 2: [2, 4, 8, 6], 3: [3, 9, 7, 1], 4: [4, 6], 7: [7, 9, 3, 1], 8: [8, 4, 2, 6], 9: [9, 1] }[base], n = ri(10, 99); return int('number theory · unit digit', `What is the ones digit of ${base} to the power ${n}, that is ${base} multiplied by itself ${n} times?`, cyc[(n - 1) % cyc.length]); };
const remainders = () => { const a = pick([3, 4, 5]), b = pick([5, 7]); if (a === b) return null; const ra = ri(1, a - 1), rb = ri(1, b - 1); if (ra === rb) return null; let N = 1; while (N % a !== ra || N % b !== rb) N++; if (N <= b) return null; return int('number theory · remainders', `A number leaves a remainder of ${ra} when divided by ${a}, and a remainder of ${rb} when divided by ${b}. What is the smallest such number?`, N); };
const digitSumProperty = () => { const s = ri(12, 24), n = pick([3, 4]); let k = 10 ** (n - 1); while (sum(digitsOf(k)) !== s) k++; return int('number theory · digit sums', `What is the smallest ${n}-digit number whose digits add up to ${s}?`, k); };
// ---- Geometry ----
const shapesQ = () => { const c = pick([['How many sides does a hexagon have?', 6], ['How many corners does an octagon have?', 8], ['How many sides do a triangle and a pentagon have altogether?', 8], ['How many corners do two squares and a triangle have altogether?', 11], ['How many faces does a cube have?', 6], ['How many edges does a cube have?', 12], ['How many vertices does a square-based pyramid have?', 5], ['How many edges does a triangular prism have?', 9], ['How many faces does a cuboid have?', 6]]); return int('geometry · shapes and solids', c[0], c[1]); };
const countSquares = (y) => { const n = y <= 2 ? 2 : y <= 4 ? 3 : pick([4, 5]); if (y >= 5 && Math.random() < 0.5) { const r = ri(2, 3), c = ri(3, 4); return withFigure(int('geometry · counting figures', `How many rectangles of every size, squares included, are there in this ${r} by ${c} grid?`, choose(r + 1, 2) * choose(c + 1, 2)), grid('Count the rectangles', r, c)); } return withFigure(int('geometry · counting figures', `How many squares of every size are there in this ${n} by ${n} grid?`, sum(Array.from({ length: n }, (_, i) => (i + 1) * (i + 1)))), grid('Count the squares', n, n)); };
const perimeterArea = (y) => { const kind = y <= 4 ? ri(1, 3) : ri(1, 4); if (kind === 1) { const l = ri(4, 20), w = ri(2, l - 1); return int('geometry · perimeter', `A rectangle is ${l} cm long and ${w} cm wide. What is its perimeter, in cm?`, 2 * (l + w)); } if (kind === 2) { const s = ri(3, 15); return int('geometry · area', `A square has a perimeter of ${4 * s} cm. What is its area, in cm²?`, s * s); } if (kind === 3) { const n = ri(3, 12); return int('geometry · perimeter', `${n} unit squares are placed side by side in one row to make a rectangle. What is the perimeter of the rectangle?`, 2 * n + 2); } const L = ri(8, 20), W = ri(6, 15), l = ri(2, L - 3), w = ri(2, W - 3); return int('geometry · area', `An L-shaped floor is a ${L} m by ${W} m rectangle with a ${l} m by ${w} m rectangle cut from one corner. What is its area, in m²?`, L * W - l * w); };
const anglesQ = () => { const kind = ri(1, 3); if (kind === 1) { const a = ri(25, 80), b = ri(20, 175 - a); return int('geometry · angles', `Two angles of a triangle are ${a}° and ${b}°. What is the third angle, in degrees?`, 180 - a - b); } if (kind === 2) { const a = ri(50, 120), b = ri(50, 120), c = ri(30, 359 - a - b - 20); return int('geometry · angles', `Three angles of a quadrilateral are ${a}°, ${b}° and ${c}°. What is the fourth angle, in degrees?`, 360 - a - b - c); } const a = ri(30, 150); return int('geometry · angles', `Two angles together make a straight line. One is ${a}°. What is the other, in degrees?`, 180 - a); };
const circleQ = () => { const r = pick([7, 14, 21, 28]), kind = ri(1, 2); if (kind === 1) return int('geometry · circles', `Taking π as 22/7, what is the area of a circle of radius ${r} cm, in cm²?`, (22 / 7) * r * r); return int('geometry · circles', `Taking π as 22/7, what is the circumference of a circle of diameter ${2 * r} cm, in cm?`, 2 * (22 / 7) * r); };
const volumeSurface = () => { const kind = ri(1, 3); if (kind === 1) { const s = ri(2, 9); return int('geometry · volume', `What is the volume of a cube with edges of ${s} cm, in cm³?`, s ** 3); } if (kind === 2) { const s = ri(2, 9); return int('geometry · surface area', `What is the total surface area of a cube with edges of ${s} cm, in cm²?`, 6 * s * s); } const l = ri(3, 10), w = ri(2, 8), h = ri(2, 6); return int('geometry · volume', `A cuboid is ${l} cm by ${w} cm by ${h} cm. What is its volume, in cm³?`, l * w * h); };
const areaRatio = () => { const kind = ri(1, 2); if (kind === 1) { const A = ri(5, 30) * 2; return int('geometry · ratio of areas', `A triangle is drawn inside a rectangle with the same base and the same height. The rectangle has an area of ${A} cm². What is the area of the triangle, in cm²?`, A / 2); } const s = ri(2, 9), k = pick([2, 3]); return int('geometry · ratio of areas', `A square has an area of ${s * s} cm². Every side is made ${k} times as long. What is the new area, in cm²?`, s * s * k * k); };
// ---- Combinatorics ----
const twoDigitFromDigits = (y) => { const k = y <= 2 ? 3 : ri(3, 4), ds = shuffle([1, 2, 3, 4, 5, 6, 7, 8, 9]).slice(0, k).sort((a, b) => a - b); if (y >= 3 && Math.random() < 0.5) { const evens = ds.filter((d) => d % 2 === 0).length; if (!evens) return null; return int('combinatorics · forming numbers', `Using the digits ${ds.join(', ')}, with no digit used twice in a number, how many different even two-digit numbers can be formed?`, evens * (k - 1)); } return int('combinatorics · forming numbers', `Using the digits ${ds.join(', ')}, with no digit used twice in a number, how many different two-digit numbers can be formed?`, k * (k - 1)); };
const threeDigitFromDigits = () => { const withZero = Math.random() < 0.5, k = ri(4, 5), ds = (withZero ? [0, ...shuffle([1, 2, 3, 4, 5, 6, 7, 8, 9]).slice(0, k - 1)] : shuffle([1, 2, 3, 4, 5, 6, 7, 8, 9]).slice(0, k)).sort((a, b) => a - b); const total = withZero ? (k - 1) * (k - 1) * (k - 2) : k * (k - 1) * (k - 2); return int('combinatorics · forming numbers', `Using the digits ${ds.join(', ')}, with no digit used twice in a number, how many different three-digit numbers can be formed?`, total); };
const handshakes = (y) => { const n = ri(4, y <= 3 ? 8 : 15); return int('combinatorics · handshakes', `${n} people at a party each shake hands once with everyone else. How many handshakes are there?`, (n * (n - 1)) / 2); };
const routing = (y) => { const [r, c] = y <= 3 ? pick([[1, 3], [2, 2], [2, 3]]) : pick([[2, 4], [3, 3], [3, 4], [2, 5]]); return withFigure(int('combinatorics · routing', `The grid has ${r} row${r > 1 ? 's' : ''} and ${c} columns of blocks. Walking along the lines only to the right or down, how many different shortest routes are there from corner A to corner B?`, choose(r + c, r)), grid('Routes from A to B', r, c, { '0,0': 'A', [`${r - 1},${c - 1}`]: 'B' })); };
const distribution = () => { const kind = ri(1, 2); if (kind === 1) { const n = ri(5, 10), k = pick([2, 3]); return int('combinatorics · distribution', `${n} identical ${thing()}s are put into ${k} boxes so that every box has at least one. In how many ways can this be done?`, choose(n - 1, k - 1)); } const n = ri(3, 5); return int('combinatorics · distribution', `${n} different books are given to ${n} children, one book each. In how many ways can this be done?`, fact(n)); };
const excessDeficiency = () => { const kids = ri(4, 12), a = ri(2, 5), c = a + ri(1, 3), left = ri(1, 9), items = a * kids + left, short = c * kids - items; if (short <= 0) return null; return int('combinatorics · excess and deficiency', `A teacher shares ${thing()}s among a class. Giving ${a} to each child leaves ${left} over; giving ${c} to each child would be ${short} short. How many children are in the class?`, kids); };
const combinationsQ = () => { const kind = ri(1, 2); if (kind === 1) { const n = ri(5, 9), k = pick([2, 3]); return int('combinatorics · combinations', `A team of ${k} is chosen from ${n} players. How many different teams are possible?`, choose(n, k)); } const n = ri(4, 8); return int('combinatorics · combinations', `How many different lines can be drawn through pairs of ${n} points, no three of which lie on a line?`, choose(n, 2)); };
const permutationsQ = () => { const kind = ri(1, 2); if (kind === 1) { const n = ri(3, 5); return int('combinatorics · permutations', `In how many different orders can ${n} different books be placed in a row on a shelf?`, fact(n)); } const n = ri(4, 7); return int('combinatorics · permutations', `${n} runners race. In how many ways can the gold, silver and bronze medals be given out?`, n * (n - 1) * (n - 2)); };
const inclusionExclusion = () => { const n = ri(30, 45), both = ri(4, 10), onlyA = ri(5, 12), onlyB = ri(5, 12), neither = n - both - onlyA - onlyB; if (neither < 1) return null; const [x, z] = pick([['maths', 'science'], ['football', 'swimming'], ['drawing', 'music']]); return int('combinatorics · inclusion and exclusion', `In a class of ${n} pupils, ${onlyA + both} like ${x}, ${onlyB + both} like ${z}, and ${both} like both. How many like neither?`, neither); };
const diceWays = () => { const t = ri(4, 10); let n = 0; for (let a = 1; a <= 6; a++) for (let b = 1; b <= 6; b++) if (a + b === t) n++; return int('combinatorics · counting outcomes', `Two dice are rolled. In how many ways can the two numbers add up to ${t}?`, n); };

// each category's kinds, with the years they suit and the moon that leans on them ('hk' number theory and counting, 'bkk' logic set-pieces and arithmetic tricks)
const KINDS = {
  LT: [['balance', balance, [1, 6], 'bkk'], ['guess two-digit', guessTwoDigit, [2, 4]], ['guess four-digit', guessFourDigit, [5, 6]], ['periodic', periodic, [3, 6], 'bkk'], ['pigeonhole', pigeonhole, [3, 6]], ['chicken and rabbit', chickenRabbit, [4, 6], 'bkk'], ['speed', speed, [5, 6], 'bkk'], ['ages', ages, [3, 6]], ['dates', daysBetween, [3, 6]], ['figure patterns', rowsOfDots, [1, 4]]],
  AR: [['smart addition', smartAdd, [1, 3], 'bkk'], ['Gaussian addition', gauss, [3, 6], 'bkk'], ['smart four-digit', smartFourDigit, [4, 6], 'bkk'], ['multiplication trick', multiplyTrick, [4, 6], 'bkk'], ['geometric sum', geometricSum, [5, 6], 'bkk'], ['sum of squares', squaresSum, [5, 6]], ['decimals', decimalTrick, [5, 6]], ['fraction chain', fractionChain, [5, 6]], ['missing digit', missingDigit, [1, 4]]],
  NT: [['odd and even', evenOddCount, [1, 3]], ['largest with a digit sum', largestWithDigitSum, [1, 3]], ['digit count', digitCount, [2, 6], 'hk'], ['primes', primesQ, [4, 6], 'hk'], ['LCM and HCF', lcmHcf, [4, 6]], ['divisibility', divisibility, [4, 6], 'hk'], ['number of factors', factorsCount, [5, 6], 'hk'], ['sum of factors', factorsSum, [5, 6], 'hk'], ['unit digit', unitDigit, [5, 6], 'hk'], ['remainders', remainders, [5, 6], 'hk'], ['digit sums', digitSumProperty, [3, 5]]],
  GE: [['shapes and solids', shapesQ, [1, 4]], ['counting figures', countSquares, [1, 6]], ['perimeter and area', perimeterArea, [3, 6]], ['angles', anglesQ, [4, 6]], ['circles', circleQ, [5, 6]], ['volume and surface', volumeSurface, [5, 6]], ['ratio of areas', areaRatio, [5, 6]]],
  CO: [['two-digit numbers', twoDigitFromDigits, [1, 4]], ['pairs', pairsCount, [1, 3]], ['three-digit numbers', threeDigitFromDigits, [4, 6], 'hk'], ['handshakes', handshakes, [2, 6]], ['routing', routing, [3, 6], 'hk'], ['distribution', distribution, [4, 6]], ['excess and deficiency', excessDeficiency, [4, 6], 'bkk'], ['combinations', combinationsQ, [5, 6], 'hk'], ['permutations', permutationsQ, [5, 6], 'hk'], ['inclusion and exclusion', inclusionExclusion, [5, 6], 'hk'], ['dice', diceWays, [5, 6]]],
};
export const CATEGORIES = Object.freeze({ LT: 'Logical thinking', AR: 'Arithmetic', NT: 'Number theory', GE: 'Geometry', CO: 'Combinatorics' });
// the pool a moon draws from: every kind that suits the year, its own leanings first three times in four (buildHeat picks by category)
function pool(year, lean) {
  const out = [];
  for (const [cat, kinds] of Object.entries(KINDS)) {
    const fit = kinds.filter(([, , [lo, hi]]) => year >= lo && year <= hi), own = fit.filter((k) => k[3] === lean), copies = own.length ? 3 : 0;
    for (const [name, gen, , tag] of fit) for (let c = 0; c < (tag === lean ? copies : 1); c++) out.push({ cat: `${cat}:${name}`, gen, sections: [cat] });
  }
  return out;
}
const SHAPE = slots([['LT', 'sa', 2], ['AR', 'sa', 2], ['NT', 'sa', 2], ['GE', 'sa', 2], ['CO', 'sa', 2]]);
/** Ten short answers, two a category in the real order; `lean` names the moon whose signature kinds come up three times as often. */
export function ocecHeat(year, lean) {
  return buildHeat(SHAPE, pool(year, lean), year).map((q) => ({ ...q, cat: q.cat.replace(/^[A-Z]{2}:/, `${CATEGORIES[q.section].toLowerCase()} · `) }));
}
