// 🐉🐘 The OCEC family — what HK-Moon (HKIMO) and BKK-Moon (TIMO) share (olympia-research.md §5, §7 and the addendum). The real
// heats are twins: five categories — Logical Thinking, Arithmetic, Number Theory, Geometry, Combinatorics — five short answers
// each, four marks each, ninety minutes, no calculators, and at primary the answer is mostly a whole number (a few fractions,
// and at P1–P2 the odd word answer, occur on the real papers). The official sample papers are one template with the numbers
// changed and the 2025 heat papers spread evenly over the five areas, so the "HKIMO leans on number theory, TIMO on logic"
// split below is OUR differentiation, not the competitions' (the source check of 20 Sep 2026). The categories live here once,
// every kind tagged, and each moon's heat prefers its own tags: two questions a category, all typed answers, in the syllabus's
// own progression by primary year. The kinds under "the papers' staples" (20 Sep 2026) are what the 2025 heat papers ask that the
// first build lacked: cryptarithms, work and rest, give and take, defined operations, sums and multiples, telescoping sums, unit
// digits of sums of powers, three remainders at once, pyramids and prisms, exterior angles, compound routes, arrangements.
import { ri, pick, shuffle, sum, names, thing, int, withFigure, grid, buildHeat, slots, isPrime, factorsOf, digitsOf, gcd, lcm, ord } from './common.mjs';

const choose = (n, k) => { let r = 1; for (let i = 1; i <= k; i++) r = (r * (n - k + i)) / i; return Math.round(r); };
const fact = (n) => (n <= 1 ? 1 : n * fact(n - 1));
const COLOURS = ['red', 'blue', 'green', 'yellow', 'white', 'black'];
const OBJECTS = [['ball', 'cube', 'marble'], ['apple', 'pear', 'plum'], ['brick', 'block', 'bead'], ['jar', 'can', 'coin']]; // regular plurals only: an "s" is added

// ---- Logical Thinking ----
const balance = (y) => {
  const [a, b, c] = pick(OBJECTS), p = ri(2, y <= 2 ? 4 : 6), q = ri(2, y <= 2 ? 3 : 5);
  if (y <= 3) return int('logical thinking · balance', `On a balance, 1 ${a} weighs the same as ${p} ${b}s, and 1 ${b} weighs the same as ${q} ${c}s. How many ${c}s weigh the same as 1 ${a}?`, p * q);
  const k = ri(2, 4), n = ri(2, 3); // k a's = kp b's, so one a is p b's
  return int('logical thinking · balance', `On a balance, ${k} ${a}s weigh the same as ${k * p} ${b}s, and 1 ${b} weighs the same as ${q} ${c}s. How many ${c}s weigh the same as ${n} ${a}s?`, n * p * q);
};
const guessTwoDigit = () => { const t = ri(3, 9), u = ri(0, t - 1); return int('logical thinking · guessing a number', `A two-digit number has digits that add up to ${t + u}. Its tens digit is ${t - u} more than its ones digit. What is the number?`, 10 * t + u); };
const guessFourDigit = () => {
  const h = pick([2, 3]), th = 2 * h, t = 3 * h, o = t - 5;
  // the digit sum pins the number: without it 4261 and 6394 both fit the clues (the source check of 20 Sep 2026)
  return int('logical thinking · guessing a number', `In a four-digit number, the thousands digit is twice the hundreds digit, the tens digit is the sum of the thousands and hundreds digits, the ones digit is 5 less than the tens digit, and the four digits add up to ${th + h + t + o}. What is the number?`, 1000 * th + 100 * h + 10 * t + o);
};
const periodic = (y) => {
  const p = ri(3, y <= 3 ? 4 : 6), cs = shuffle(COLOURS).slice(0, p), counts = cs.map(() => ri(1, y <= 3 ? 2 : 3)), cycle = cs.flatMap((c, i) => Array(counts[i]).fill(c)), L = cycle.length, n = ri(y <= 3 ? 15 : 40, y <= 3 ? 40 : 120);
  const kind = y >= 4 && Math.random() < 0.5 ? 2 : 1;
  const words = `Beads are threaded in a repeating pattern: ${cycle.join(', ')}, and then the pattern repeats.`;
  if (kind === 1) { const col = cycle[(n - 1) % L]; const cnt = Math.floor(n / L) * counts[cs.indexOf(col)] + cycle.slice(0, n % L).filter((c) => c === col).length; return int('logical thinking · periodic problems', `${words} How many ${col} beads are there among the first ${n} beads?`, cnt); }
  const target = pick(cs), k = ri(3, y <= 4 ? 8 : 20); // the position of the k-th bead of that colour
  let seen = 0, pos = 0; while (seen < k) { pos++; if (cycle[(pos - 1) % L] === target) seen++; }
  return int('logical thinking · periodic problems', `${words} In which position is the ${ord(k)} ${target} bead?`, pos);
};
const pigeonhole = (y) => {
  const cs = shuffle(COLOURS).slice(0, y <= 3 ? 2 : 3), counts = cs.map(() => ri(4, 12)), it = pick(['sock', 'marble', 'ball']);
  const kind = y >= 5 ? ri(1, 3) : ri(1, 2);
  const bag = cs.map((c, i) => `${counts[i]} ${c}`).join(', ').replace(/, ([^,]*)$/, ' and $1');
  if (kind === 1) return int('logical thinking · pigeonhole', `A drawer has ${bag} ${it}s, all mixed up. In the dark, what is the smallest number of ${it}s you must take to be sure of two of the same colour?`, cs.length + 1);
  if (kind === 2) { const i = ri(0, cs.length - 1); return int('logical thinking · pigeonhole', `A drawer has ${bag} ${it}s, all mixed up. In the dark, what is the smallest number of ${it}s you must take to be sure of one ${cs[i]} ${it}?`, sum(counts) - counts[i] + 1); }
  const m = ri(3, 4); return int('logical thinking · pigeonhole', `A drawer has ${bag} ${it}s, all mixed up. In the dark, what is the smallest number of ${it}s you must take to be sure of ${m} of the same colour?`, (m - 1) * cs.length + 1);
};
const chickenRabbit = (y) => { const c = ri(4, y <= 4 ? 14 : 30), r = ri(3, y <= 4 ? 10 : 24), [one, other, a, b] = pick([['chickens', 'rabbits', 2, 4], ['bicycles', 'cars', 2, 4], ['spiders', 'beetles', 8, 6]]); return int('logical thinking · chicken and rabbit', `A yard holds only ${one} and ${other}: ${c + r} heads and ${c * a + r * b} legs altogether. How many ${other} are there?`.replace('legs', one === 'bicycles' ? 'wheels' : 'legs').replace('heads', one === 'bicycles' ? 'vehicles' : 'heads'), r); };
const speed = (y) => {
  const kind = ri(1, 3);
  if (kind === 1) { const v = pick([40, 50, 60, 80, 90]), t = ri(2, 5); return int('logical thinking · speed', `A train travels at ${v} km/h. How far does it go in ${t} hours, in km?`, v * t); }
  if (kind === 2) { const v1 = pick([40, 50, 60, 80]), v2 = pick([30, 40, 70, 90]), t = ri(2, 7); return int('logical thinking · speed', `Two towns are ${(v1 + v2) * t} km apart. A car leaves one at ${v1} km/h and a van leaves the other at ${v2} km/h at the same time, driving toward each other. After how many hours do they meet?`, t); }
  const v = pick([4, 5, 6]), t = ri(2, 4), back = pick([2, 3]), dist = v * t; if (dist % back || t <= back) return null; // cycling back must be faster than walking there
  return int('logical thinking · speed', `${names(1)[0]} walks to a lake at ${v} km/h in ${t} hours and cycles back the same way in ${back} hours. What is the cycling speed, in km/h?`, dist / back);
};
const ages = (y) => {
  const t = pick([3, 4, 5, 6, 8, 9, 10, 12, 15]), [k, m] = pick([[3, 2], [4, 2], [4, 3], [5, 3], [5, 2], [6, 4], [7, 4]]);
  const x = (t * (m - 1)) / (k - m); if (!Number.isInteger(x) || k * x < x + 18 || k * x > x + 45) return null; // now: child x, mother kx; in t years mother is m times — and a mother 18 to 45 years older, not 5 or 120 (the source check)
  return int('logical thinking · ages', `A mother is ${k} times as old as her ${pick(['son', 'daughter'])}. In ${t} years she will be ${m} times as old. How old is the child now?`, x);
};
const daysBetween = (y) => { const months = [['March', 31], ['April', 30], ['May', 31], ['June', 30], ['July', 31], ['August', 31], ['September', 30], ['October', 31]]; const i = ri(0, months.length - 2), d1 = ri(1, 25), d2 = ri(1, 28); const days = months[i][1] - d1 + d2; return int('logical thinking · dates', `How many days are there from ${d1} ${months[i][0]} to ${d2} ${months[i + 1][0]} of the same year, counting both days?`, days + 1); };
const rowsOfDots = (y) => { const a = ri(1, 4), k = ri(1, 3), n = ri(4, y <= 2 ? 6 : 10); return int('logical thinking · figure patterns', `Row 1 of a figure has ${a} dot${a === 1 ? '' : 's'}, row 2 has ${a + k}, row 3 has ${a + 2 * k}, and each row has ${k} more than the one before. How many dots are there in the first ${n} rows altogether?`, n * a + (k * n * (n - 1)) / 2); };
const pairsCount = (y) => { const a = ri(2, y <= 2 ? 4 : 6), b = ri(2, y <= 2 ? 5 : 8), [x, z] = pick([['shirts', 'hats'], ['drinks', 'snacks'], ['roads into town', 'roads out of it'], ['kinds of bread', 'fillings']]); return int('combinatorics · pairs', `${names(1)[0]} has ${a} ${x} and ${b} ${z}. How many different ways are there to choose one of each?`, a * b); };
const largestWithDigitSum = (y) => { const s = ri(3, 17), t = Math.min(9, s), o = s - t; if (o > 9) return null; return int('number theory · digit sums', `What is the largest two-digit number whose digits add up to ${s}?`, 10 * t + o); };
// ---- Arithmetic ----
const smartAdd = (y) => {
  if (y <= 2) { const pairs = shuffle([[19, 21], [38, 12], [27, 13], [46, 14], [35, 25], [18, 22], [44, 16], [29, 11]]).slice(0, 2).flat(); return int('arithmetic · smart addition', `${shuffle(pairs).join(' + ')} = ?`, sum(pairs)); }
  const base = pick([98, 99, 97, 995, 996]), k = ri(3, 6); return int('arithmetic · smart addition', `${Array(k).fill(base).join(' + ')} = ?`, base * k);
};
const gauss = (y) => {
  if (y <= 4) { const n = y === 3 ? pick([10, 20, 30]) : pick([50, 100]); return int('arithmetic · Gaussian addition', `1 + 2 + 3 + … + ${n} = ?`, (n * (n + 1)) / 2); }
  const a = ri(2, 9), d = pick([3, 4, 5, 6, 7]), n = ri(10, 30), last = a + (n - 1) * d; return int('arithmetic · Gaussian addition', `${a} + ${a + d} + ${a + 2 * d} + … + ${last} = ?`, (n * (a + last)) / 2);
};
const smartFourDigit = () => { const kind = ri(1, 3); if (kind === 1) return int('arithmetic · smart calculation', '9999 + 999 + 99 + 9 = ?', 11106); if (kind === 2) { const a = ri(1000, 9999), b = 10000 - a + ri(0, 999); return int('arithmetic · smart calculation', `${a} + ${b} = ?`, a + b); } const n = ri(1001, 4999); return int('arithmetic · smart calculation', `${n} + 9999 = ?`, n + 9999); };
const multiplyTrick = () => { const kind = ri(1, 3); if (kind === 1) { const a = pick([4, 8, 16, 32]); return int('arithmetic · smart calculation', `25 × ${a} × 125 = ?`, 25 * a * 125); } if (kind === 2) { const a = ri(3, 9); return int('arithmetic · smart calculation', `999 × ${a} = ?`, 999 * a); } const a = ri(11, 19), b = ri(11, 19); return int('arithmetic · 3-digit multiplication', `${a * 10} × ${b} = ?`, a * 10 * b); };
const geometricSum = () => { const kind = ri(1, 2); if (kind === 1) { const n = ri(6, 10); return int('arithmetic · sum of a geometric sequence', `1 + 2 + 4 + 8 + … + ${2 ** n} = ?`, 2 ** (n + 1) - 1); } const n = ri(4, 6); return int('arithmetic · sum of a geometric sequence', `1 + 3 + 9 + … + ${3 ** n} = ?`, (3 ** (n + 1) - 1) / 2); };
const squaresSum = () => { const n = ri(5, 12); return int('arithmetic · sum of squares', `1² + 2² + 3² + … + ${n}² = ?`, (n * (n + 1) * (2 * n + 1)) / 6); };
const decimalTrick = () => { const kind = ri(1, 2); if (kind === 1) { const a = ri(13, 99); return int('arithmetic · decimals', `0.25 × ${a} × 4 = ?`, a); } const a = ri(2, 9); return int('arithmetic · decimals', `0.5 × ${a * 2} × 12.5 × 8 = ?`, a * 100); };
const fractionChain = () => { const n = ri(3, 6), num = 2 ** n - 1, den = 2 ** n, terms = n <= 4 ? Array.from({ length: n }, (_, i) => `1/${2 ** (i + 1)}`).join(' + ') : `1/2 + 1/4 + 1/8 + … + 1/${den}`; return int('arithmetic · fractions', `${terms} is a fraction a/b in its simplest form. What is a + b?`, num + den); };
const missingDigit = (y) => { const A = ri(1, 9), a = ri(0, 9), b = ri(10, y <= 2 ? 50 : 89), s = 10 * A + a + b; return int('arithmetic · missing digit', `In the sum ▢${a} + ${b} = ${s}, what digit is ▢?`, A, { read: `A two-digit number with ones digit ${a} plus ${b} makes ${s}. What is its tens digit?` }); };
// ---- Number Theory ----
const evenOddCount = (y) => { const a = ri(1, 20), n = ri(10, y <= 2 ? 30 : 60), b = a + n, even = Math.random() < 0.5; let c = 0; for (let k = a; k <= b; k++) if ((k % 2 === 0) === even) c++; return int('number theory · odd and even', `How many ${even ? 'even' : 'odd'} numbers are there from ${a} to ${b}, counting both?`, c); };
const digitCount = (y) => { const d = ri(1, 9), n = y <= 3 ? pick([50, 60, 80, 100]) : pick([100, 150, 200]); let c = 0; for (let k = 1; k <= n; k++) c += digitsOf(k).filter((x) => x === d).length; return int('number theory · digits', `When the whole numbers from 1 to ${n} are written down, how many times is the digit ${d} written?`, c); };
const primesQ = (y) => { const kind = ri(1, 3); if (kind === 1) { const lo = pick([10, 20, 30, 40, 50, 60]), hi = lo + pick([10, 20, 30]); let n = 0; for (let k = lo + 1; k < hi; k++) if (isPrime(k)) n++; return int('number theory · primes', `How many prime numbers are there between ${lo} and ${hi}?`, n); } if (kind === 2) { const n = ri(30, 120); let p = n - 1; while (!isPrime(p)) p--; return int('number theory · primes', `What is the largest prime number less than ${n}?`, p); } const lo = pick([10, 20, 30]), hi = lo + 10; let s = 0; for (let k = lo + 1; k < hi; k++) if (isPrime(k)) s += k; return int('number theory · primes', `What is the sum of all the prime numbers between ${lo} and ${hi}?`, s); };
const lcmHcf = () => { const kind = ri(1, 3); if (kind === 1) { const a = pick([4, 6, 8, 9, 10, 12, 15]), b = pick([6, 8, 9, 10, 12, 14, 18]); if (a === b) return null; return int('number theory · LCM', `Two lights flash every ${a} seconds and every ${b} seconds. They flash together now. After how many seconds do they next flash together?`, lcm(a, b)); } if (kind === 2) { const g = pick([6, 8, 12, 15]), a = g * pick([2, 3, 5]), b = g * pick([3, 4, 7]); if (a === b) return null; return int('number theory · HCF', `What is the highest common factor of ${a} and ${b}?`, gcd(a, b)); } const g = pick([4, 6, 9, 12]), a = g * pick([2, 3, 5]), b = g * pick([4, 7]); return int('number theory · HCF', `Ribbons of ${a} cm and ${b} cm are cut into pieces of the same length, as long as possible, with nothing left over. How long is each piece, in cm?`, gcd(a, b)); };
const divisibility = (y) => { const kind = ri(1, 3); if (kind === 1) { const d = pick([3, 9]), a = ri(1, 9), b = ri(0, 9), c = ri(0, 9); let x = 0; while ((a + b + c + x) % d !== 0) x++; return int('number theory · divisibility', `What is the smallest digit that can replace ▢ so that ${a}${b}${c}▢ is divisible by ${d}?`, x, { read: `What is the smallest digit that can go on the end of ${a}${b}${c} so the number is divisible by ${d}?` }); } if (kind === 2) { const d = pick([6, 7, 8, 9, 12]), n = pick([100, 200, 300]); return int('number theory · divisibility', `How many multiples of ${d} are there from 1 to ${n}?`, Math.floor(n / d)); } const a = pick([3, 4, 5]), b = pick([4, 5, 6, 7]); if (a === b) return null; const n = pick([100, 200, 300]); return int('number theory · divisibility', `How many whole numbers from 1 to ${n} are divisible by ${a} but not by ${b}?`, Math.floor(n / a) - Math.floor(n / lcm(a, b))); };
const factorsCount = () => { const n = pick([36, 48, 60, 72, 84, 90, 96, 100, 120, 144, 180, 200, 240, 360, 720]); return int('number theory · number of factors', `How many positive factors does ${n} have?`, factorsOf(n).length); };
const factorsSum = () => { const n = pick([12, 18, 20, 24, 28, 30, 36, 40, 45, 48]); return int('number theory · sum of factors', `What is the sum of all the positive factors of ${n}?`, sum(factorsOf(n))); };
const unitDigit = () => { const base = pick([2, 3, 4, 7, 8, 9]), cyc = { 2: [2, 4, 8, 6], 3: [3, 9, 7, 1], 4: [4, 6], 7: [7, 9, 3, 1], 8: [8, 4, 2, 6], 9: [9, 1] }[base], n = ri(10, 99); return int('number theory · unit digit', `What is the ones digit of ${base} to the power ${n}, that is ${base} multiplied by itself ${n} times?`, cyc[(n - 1) % cyc.length]); };
const remainders = () => { const a = pick([3, 4, 5]), b = pick([5, 7]); if (a === b) return null; const ra = ri(1, a - 1), rb = ri(1, b - 1); if (ra === rb) return null; let N = 1; while (N % a !== ra || N % b !== rb) N++; if (N <= b) return null; return int('number theory · remainders', `A number leaves a remainder of ${ra} when divided by ${a}, and a remainder of ${rb} when divided by ${b}. What is the smallest such number?`, N); };
const digitSumProperty = () => { const s = ri(12, 24), n = pick([3, 4]); let k = 10 ** (n - 1); while (sum(digitsOf(k)) !== s) k++; return int('number theory · digit sums', `What is the smallest ${n}-digit number whose digits add up to ${s}?`, k); };
// ---- Geometry ----
const shapesQ = () => { const c = pick([['How many sides does a hexagon have?', 6], ['How many corners does an octagon have?', 8], ['How many sides do a triangle and a pentagon have altogether?', 8], ['How many corners do two squares and a triangle have altogether?', 11], ['How many faces does a cube have?', 6], ['How many edges does a cube have?', 12], ['How many vertices does a square-based pyramid have?', 5], ['How many edges does a triangular prism have?', 9], ['How many faces does a cuboid have?', 6]]); return int('geometry · shapes and solids', c[0], c[1]); };
const countSquares = (y) => { const n = y <= 2 ? 2 : y <= 4 ? 3 : pick([4, 5]); if (y >= 5 && Math.random() < 0.5) { const r = ri(2, 3), c = ri(3, 4); return withFigure(int('geometry · counting figures', `How many rectangles of every size, squares included, are there in this ${r} by ${c} grid?`, choose(r + 1, 2) * choose(c + 1, 2)), grid('Count the rectangles', r, c)); } return withFigure(int('geometry · counting figures', `How many squares of every size are there in this ${n} by ${n} grid?`, sum(Array.from({ length: n }, (_, i) => (i + 1) * (i + 1)))), grid('Count the squares', n, n)); };
const perimeterArea = (y) => { const kind = y <= 4 ? ri(1, 3) : ri(1, 4); if (kind === 1) { const l = ri(4, 20), w = ri(2, l - 1); return int('geometry · perimeter', `A rectangle is ${l} cm long and ${w} cm wide. What is its perimeter, in cm?`, 2 * (l + w)); } if (kind === 2) { const s = ri(3, 15); return int('geometry · area', `A square has a perimeter of ${4 * s} cm. What is its area, in cm²?`, s * s); } if (kind === 3) { const n = ri(3, 12); return int('geometry · perimeter', `${n} unit squares are placed side by side in one row to make a rectangle. What is the perimeter of the rectangle?`, 2 * n + 2); } const L = ri(8, 20), W = ri(6, 15), l = ri(2, L - 3), w = ri(2, W - 3); return int('geometry · area', `An L-shaped floor is a ${L} m by ${W} m rectangle with a ${l} m by ${w} m rectangle cut from one corner. What is its area, in m²?`, L * W - l * w); };
const anglesQ = () => { const kind = ri(1, 3); if (kind === 1) { const a = ri(25, 80), b = ri(20, 175 - a); return int('geometry · angles', `Two angles of a triangle are ${a}° and ${b}°. What is the third angle, in degrees?`, 180 - a - b); } if (kind === 2) { const a = ri(50, 120), b = ri(50, 120), c = ri(30, 359 - a - b - 20); return int('geometry · angles', `Three angles of a quadrilateral are ${a}°, ${b}° and ${c}°. What is the fourth angle, in degrees?`, 360 - a - b - c); } const a = ri(30, 150); return int('geometry · angles', `Two angles together make a straight line. One is ${a}°. What is the other, in degrees?`, 180 - a); };
const circleQ = () => { const r = pick([7, 14, 21, 28]), kind = ri(1, 2); if (kind === 1) return int('geometry · circles', `Taking π as 22/7, what is the area of a circle of radius ${r} cm, in cm²?`, (22 / 7) * r * r); return int('geometry · circles', `Taking π as 22/7, what is the circumference of a circle of diameter ${2 * r} cm, in cm?`, 2 * (22 / 7) * r); };
const volumeSurface = () => { const kind = ri(1, 3); if (kind === 1) { const s = ri(2, 9); return int('geometry · volume', `What is the volume of a cube with edges of ${s} cm, in cm³?`, s ** 3); } if (kind === 2) { const s = ri(2, 9); return int('geometry · surface area', `What is the total surface area of a cube with edges of ${s} cm, in cm²?`, 6 * s * s); } const l = ri(3, 10), w = ri(2, 8), h = ri(2, 6); return int('geometry · volume', `A cuboid is ${l} cm by ${w} cm by ${h} cm. What is its volume, in cm³?`, l * w * h); };
const areaRatio = () => { const kind = ri(1, 2); if (kind === 1) { const A = ri(5, 30) * 2; return int('geometry · ratio of areas', `A triangle is drawn inside a rectangle with the same base and the same height. The rectangle has an area of ${A} cm². What is the area of the triangle, in cm²?`, A / 2); } const s = ri(2, 9), k = pick([2, 3]); return int('geometry · ratio of areas', `A square has an area of ${s * s} cm². Every side is made ${k} times as long. What is the new area, in cm²?`, s * s * k * k); };
// ---- Combinatorics ----
const twoDigitFromDigits = (y) => { const k = y <= 2 ? 3 : ri(3, 4), ds = shuffle([1, 2, 3, 4, 5, 6, 7, 8, 9]).slice(0, k).sort((a, b) => a - b); if (y >= 3 && Math.random() < 0.5) { const evens = ds.filter((d) => d % 2 === 0).length; if (!evens) return null; return int('combinatorics · forming numbers', `Using the digits ${ds.join(', ')}, with no digit used twice in a number, how many different even two-digit numbers can be formed?`, evens * (k - 1)); } return int('combinatorics · forming numbers', `Using the digits ${ds.join(', ')}, with no digit used twice in a number, how many different two-digit numbers can be formed?`, k * (k - 1)); };
const threeDigitFromDigits = () => { const withZero = Math.random() < 0.5, k = ri(4, 5), ds = (withZero ? [0, ...shuffle([1, 2, 3, 4, 5, 6, 7, 8, 9]).slice(0, k - 1)] : shuffle([1, 2, 3, 4, 5, 6, 7, 8, 9]).slice(0, k)).sort((a, b) => a - b); const total = withZero ? (k - 1) * (k - 1) * (k - 2) : k * (k - 1) * (k - 2); return int('combinatorics · forming numbers', `Using the digits ${ds.join(', ')}, with no digit used twice in a number, how many different three-digit numbers can be formed?`, total); };
const handshakes = (y) => { const n = ri(4, y <= 3 ? 8 : 15); return int('combinatorics · handshakes', `${n} people at a party each shake hands once with everyone else. How many handshakes are there?`, (n * (n - 1)) / 2); };
const routing = (y) => { const [r, c] = y <= 3 ? pick([[1, 3], [2, 2], [2, 3]]) : pick([[2, 4], [3, 3], [3, 4], [2, 5]]); return withFigure(int('combinatorics · routing', `The grid has ${r} row${r > 1 ? 's' : ''} and ${c} columns of blocks. Walking along the lines only to the right or down, how many different shortest routes are there from corner A to corner B?`, choose(r + c, r)), grid('Routes from A to B', r, c, { '0,0': 'A', [`${r - 1},${c - 1}`]: 'B' })); };
const distribution = () => { const kind = ri(1, 2); if (kind === 1) { const n = ri(5, 10), k = pick([2, 3]); return int('combinatorics · distribution', `${n} identical ${thing()}s are put into ${k} boxes so that every box has at least one. In how many ways can this be done?`, choose(n - 1, k - 1)); } const n = ri(3, 5); return int('combinatorics · distribution', `${n} different books are given to ${n} children, one book each. In how many ways can this be done?`, fact(n)); };
const excessDeficiency = () => { const kids = ri(4, 12), a = ri(2, 5), c = a + ri(1, 3), left = ri(1, 9), items = a * kids + left, short = c * kids - items; if (short <= 0) return null; return int('combinatorics · excess and deficiency', `A teacher shares ${thing()}s among a class. Giving ${a} to each child leaves ${left} over; giving ${c} to each child would be ${short} short. How many children are in the class?`, kids); };
const combinationsQ = () => { const kind = ri(1, 2); if (kind === 1) { const n = ri(5, 9), k = pick([2, 3]); return int('combinatorics · combinations', `A team of ${k} is chosen from ${n} players. How many different teams are possible?`, choose(n, k)); } const n = ri(4, 8); return int('combinatorics · combinations', `How many different lines can be drawn through pairs of ${n} points, no three of which lie on a line?`, choose(n, 2)); };
const permutationsQ = () => { const kind = ri(1, 2); if (kind === 1) { const n = ri(3, 5); return int('combinatorics · permutations', `In how many different orders can ${n} different books be placed in a row on a shelf?`, fact(n)); } const n = ri(4, 7); return int('combinatorics · permutations', `${n} runners race. In how many ways can the gold, silver and bronze medals be given out?`, n * (n - 1) * (n - 2)); };
const inclusionExclusion = () => { const n = ri(30, 45), both = ri(4, 10), onlyA = ri(5, 12), onlyB = ri(5, 12), neither = n - both - onlyA - onlyB; if (neither < 1) return null; const [x, z] = pick([['maths', 'science'], ['football', 'swimming'], ['drawing', 'music']]); return int('combinatorics · inclusion and exclusion', `In a class of ${n} pupils, ${onlyA + both} like ${x}, ${onlyB + both} like ${z}, and ${both} like both. How many like neither?`, neither); };
const diceWays = () => { const t = ri(4, 10); let n = 0; for (let a = 1; a <= 6; a++) for (let b = 1; b <= 6; b++) if (a + b === t) n++; return int('combinatorics · counting outcomes', `Two dice are rolled. In how many ways can the two numbers add up to ${t}?`, n); };

// ---- the papers' staples the source check found missing (20 Sep 2026: the HKIMO 2025 heat papers P2, P4, P6, the two official samples) ----
const cryptAB = () => { const D = pick([0, 2, 4, 6, 8]), B = (10 + D) / 2; return int('logical thinking · cryptarithm', `In the addition AB + AB = 1A${D}, each letter stands for one digit. What is A + B?`, 9 + B); }; // 2(10A + B) = 100 + 10A + D forces A = 9
const workRest = (y) => { const t = ri(y <= 2 ? 5 : 10, y <= 2 ? 12 : 30), r = ri(2, 8), n = ri(3, 8); return int('logical thinking · work and rest', `${names(1)[0]} makes a drawing in ${t} minutes and rests ${r} minutes before starting the next one. How many minutes pass from starting the first drawing to finishing the ${ord(n)}?`, n * t + (n - 1) * r); };
const giveTake = () => { const [m, e, a] = names(3), g = ri(3, 12), t = ri(3, 15); if (g === t) return null; return int('logical thinking · give and take', `${m} gives ${g} marbles to ${e} and takes ${t} marbles from ${a}. Now the three children have the same number of marbles. How many more marbles did ${a} have than ${e} at first?`, g + t); };
const definedOp = () => { const [sym, f, words] = pick([['⊗', (a, b) => (a + b) * (2 * a - b), 'a ⊗ b = (a + b) × (2a − b)'], ['⊕', (a, b) => a * b - a - b, 'a ⊕ b = a × b − a − b'], ['⊙', (a, b) => 2 * a + 3 * b, 'a ⊙ b = 2a + 3b'], ['⊛', (a, b) => a * a - b, 'a ⊛ b = a² − b']]), a = ri(2, 6), b = ri(1, 5), c = ri(2, 20), inner = f(a, b); if (inner < 1 || inner > 40) return null; const v = f(c, inner); if (v < 0 || v > 100000) return null; return int('logical thinking · defined operations', `For whole numbers, ${words}. What is ${c} ${sym} (${a} ${sym} ${b})?`, v); };
const sumMultiple = () => { const k = ri(3, 12), B = ri(20, 300), A = k * B; if (ri(1, 2) === 1) return int('logical thinking · sum and multiple', `A + B = ${A + B}, and A is ${k} times B. What is B?`, B); return int('logical thinking · sum and multiple', `A + B = ${A + B}, and A is ${k} times B. What is A − B?`, A - B); };
const decreasingDiffs = () => { const start = ri(60, 99), d0 = ri(2, 5), terms = [start]; for (let i = 1; i < 7; i++) terms.push(terms[i - 1] - (d0 + i - 1)); if (terms[6] < 0) return null; return int('logical thinking · number sequences', `${terms.slice(0, 5).join(', ')}, A, B, … The numbers follow a rule. What is A + B?`, terms[5] + terms[6]); };
const averageMissing = () => { const a = ri(30, 99), b = ri(30, 99), avg = ri(40, 95), x = 3 * avg - a - b; if (x < 1 || x > 150) return null; return int('logical thinking · averages', `The average of ${a}, ${b} and a third number is ${avg}. What is the third number?`, x); };
const ratioChickenRabbit = () => { const k = ri(2, 8), r = ri(4, 30); return int('logical thinking · chicken and rabbit', `A farm has ${k} times as many chickens as rabbits, and ${2 * k * r + 4 * r} legs altogether. How many rabbits are there?`, r); };
const workBackFractions = () => { const left = ri(5, 40), c2 = ri(2, 9), c1 = ri(2, 9), q = pick([3, 4, 5]), x1 = ((left + c2) * q) / (q - 1); if (!Number.isInteger(x1)) return null; const x0 = 2 * (x1 - c1); if (x0 <= 0) return null; return int('logical thinking · working backwards', `A shop had some books. In the morning it sold ${c1} fewer than half of them, and in the afternoon it sold ${c2} more than a ${['', '', 'half', 'third', 'quarter', 'fifth'][q]} of the rest. ${left} books were left. How many books were there at first?`, x0); };
const workBackOps = () => { const x = ri(10, 60), a = ri(2, 9), k = pick([3, 4, 5]), c = ri(2, 9), d = pick([2, 3, 4, 6]), v = (x - a) * k + c; if (v % d) return null; return int('logical thinking · working backwards', `A number has ${a} subtracted from it, the result is multiplied by ${k}, then ${c} is added, and the result is divided by ${d} to give ${v / d}. What is the number?`, x); };
const multiplesSum = (y) => { if (y <= 3 || ri(1, 2) === 1) { const base = pick([11, 111, 22, 33]), n = ri(4, 6); return int('arithmetic · multiples sum', `${Array.from({ length: n }, (_, i) => base * (i + 1)).join(' + ')} = ?`, (base * n * (n + 1)) / 2); } const k = ri(11, 25), n = ri(10, 25); return int('arithmetic · multiples sum', `${k} + ${2 * k} + ${3 * k} + … + ${n * k} = ?`, (k * n * (n + 1)) / 2); };
const triangularSum = () => { const n = ri(8, 14); return int('arithmetic · triangular numbers', `1 + 3 + 6 + 10 + … + ${(n * (n + 1)) / 2} = ?`, (n * (n + 1) * (n + 2)) / 6); };
const computeMixed = () => { const a = ri(11, 30), b = ri(11, 60), c = ri(50, 120), d = pick([50, 25, 20]), e = ri(11, 40), f = ri(11, 60); return int('arithmetic · mixed calculation', `${a} × ${b} + ${c} × ${d} + ${e} × ${f} = ?`, a * b + c * d + e * f); };
const squareMinus = () => { const a = ri(31, 99), b = ri(11, 30), c = ri(50, 200), v = a * a - b * c; if (v < 0) return null; return int('arithmetic · squares', `${a}² − ${b} × ${c} = ?`, v); };
const squaresRange = () => { const a = ri(5, 15), n = ri(5, 12), b = a + n - 1, S = (k) => (k * (k + 1) * (2 * k + 1)) / 6; return int('arithmetic · sum of squares', `${a}² + ${a + 1}² + … + ${b}² = ?`, S(b) - S(a - 1)); };
const telescopingOdd = () => { const n = ri(4, 12), num = n, den = 3 * (2 * n + 3), g = gcd(num, den); return int('arithmetic · telescoping', `1/15 + 1/35 + 1/63 + … + 1/${(2 * n + 1) * (2 * n + 3)} is a fraction a/b in its simplest form. What is a + b?`, num / g + den / g); }; // each term is half of 1/(2k+1) − 1/(2k+3)
const seriesAverage = () => { const a = ri(1000, 2000), d = pick([7, 14, 21]), n = ri(10, 40); if ((2 * a + (n - 1) * d) % 2) return null; return int('arithmetic · averages', `What is the average of ${a}, ${a + d}, ${a + 2 * d}, …, ${a + (n - 1) * d}?`, (2 * a + (n - 1) * d) / 2); };
const eggsBoxes = () => { const a = ri(20, 99), b = ri(5, 40), box = pick([6, 10, 12, 24, 30]); return int('arithmetic · division', `${a} + ${b} eggs are packed in boxes of ${box}. How many boxes are needed to pack them all?`, Math.ceil((a + b) / box)); };
const smallestMultiple = () => { const m = ri(13, 49); return int('arithmetic · multiples', `What is the smallest three-digit multiple of ${m}?`, m * Math.ceil(100 / m)); };
const evensInRange = () => { const a = ri(50, 150), b = ri(a + 100, 999); let c = 0; for (let k = a; k <= b; k++) if (k % 2 === 0) c++; return int('number theory · odd and even', `How many even numbers are there from ${a} to ${b}?`, c); };
const unitDigitSumPowers = () => { const base = pick([2, 3, 7, 8]), m = ri(2, 5), n = ri(20, 99), cyc = { 2: [2, 4, 8, 6], 3: [3, 9, 7, 1], 7: [7, 9, 3, 1], 8: [8, 4, 2, 6] }[base]; let s = 0; for (let k = m; k <= n; k++) s += cyc[(k - 1) % 4]; return int('number theory · unit digit', `What is the ones digit of ${base}^${m} + ${base}^${m + 1} + … + ${base}^${n}?`, s % 10); };
const crtLargest = () => { const [m1, m2, m3] = pick([[6, 5, 7], [4, 5, 7], [3, 5, 8], [5, 7, 9]]), r1 = ri(1, m1 - 1), r2 = ri(1, m2 - 1), r3 = ri(1, m3 - 1); let N = 999; while (N > 100 && (N % m1 !== r1 || N % m2 !== r2 || N % m3 !== r3)) N--; if (N <= 100) return null; return int('number theory · remainders', `What is the largest three-digit number that leaves a remainder of ${r1} when divided by ${m1}, ${r2} when divided by ${m2}, and ${r3} when divided by ${m3}?`, N); };
const phiCount = () => { const n = pick([30, 36, 42, 60, 84, 90, 120, 210, 330, 420]); let c = 0; for (let k = 1; k < n; k++) if (gcd(k, n) === 1) c++; return int('number theory · coprime', `How many proper fractions with denominator ${n} are in their simplest form?`, c); };
const divisibleEither = () => { const a = pick([3, 5, 7]), b = pick([5, 7, 8, 9]); if (a === b) return null; let c = 0; for (let k = 100; k <= 999; k++) if (k % a === 0 || k % b === 0) c++; return int('number theory · divisibility', `How many three-digit numbers are divisible by ${a} or by ${b}?`, c); };
const largestSmallestDigits = () => { const ds = [0, ...shuffle([1, 2, 3, 4, 5, 6, 7, 8, 9]).slice(0, 3)], desc = [...ds].sort((a, b) => b - a), asc = [...ds].sort((a, b) => a - b); return int('number theory · digits', `Using three of the digits ${shuffle(ds).join(', ')}, each at most once, the largest three-digit number and the smallest three-digit number are formed. What is their difference?`, Number(desc.slice(0, 3).join('')) - Number([asc[1], asc[0], asc[2]].join(''))); };
const pyramidPrism = (y) => { const n = ri(4, y <= 4 ? 8 : 20); if (ri(1, 2) === 1) return int('geometry · solids', `A pyramid has ${n + 1} vertices. How many edges does it have?`, 2 * n); return int('geometry · solids', `A prism has ${2 * n} vertices. How many edges and faces does it have altogether?`, 4 * n + 2); }; // a pyramid on an n-gon: n + 1 vertices, 2n edges; a prism on an n-gon: 2n vertices, 3n edges, n + 2 faces
const minMaxArea = () => { const P = ri(10, 50) * 2, half = P / 2; if (ri(1, 2) === 1) return int('geometry · area', `A rectangle has a perimeter of ${P} cm and whole-number sides. What is the smallest possible area, in cm²?`, half - 1); const a = Math.floor(half / 2); return int('geometry · area', `A rectangle has a perimeter of ${P} cm and whole-number sides. What is the largest possible area, in cm²?`, a * (half - a)); };
const exteriorAngle = () => { const n = pick([5, 6, 8, 9, 10, 12, 15, 18, 20]); if (ri(1, 2) === 1) return int('geometry · angles', `Each exterior angle of a regular polygon is ${360 / n}°. How many sides does it have?`, n); return int('geometry · angles', `Each interior angle of a regular polygon is ${180 - 360 / n}°. How many sides does it have?`, n); };
const coinsSquare = () => { const s = ri(3, 15); return int('geometry · coins round a square', `${4 * (s - 1)} coins form a square with the same number of coins along each side and one at each corner. How many coins are along each side?`, s); };
const wireSquares = () => { const total = pick([100, 120, 160, 200, 240]), s1 = ri(5, total / 4 - 5), rest = total - 4 * s1; if (rest % 4) return null; return int('geometry · perimeter', `A wire ${total} cm long is cut into two pieces and each is bent into a square. One square has sides of ${s1} cm. How long is each side of the other square, in cm?`, rest / 4); };
const routesCompound = (y) => { const a = ri(2, 4), b = ri(2, 3), direct = ri(1, 2), c = ri(2, 4); if (y <= 3) return int('combinatorics · routes', `There are ${a} roads from the zoo to the station and ${b} roads from the station to the cinema, and ${direct} road${direct > 1 ? 's' : ''} straight from the zoo to the cinema. How many different ways are there to go from the zoo to the cinema?`, a * b + direct); return int('combinatorics · routes', `There are ${a} roads from the zoo to the station, ${b} roads from the station to the cinema and ${direct} road${direct > 1 ? 's' : ''} straight from the zoo to the cinema, then ${c} roads from the cinema to the park. How many different ways are there to go from the zoo to the park through the cinema?`, (a * b + direct) * c); };
const bigCombinations = () => { const n = ri(10, 17), k = ri(3, Math.floor(n / 2)); return int('combinatorics · combinations', `${k} pupils are chosen from ${n} to form a team. How many different teams are possible?`, choose(n, k)); };
const multinomial = () => { const [a, b, c] = pick([[2, 2, 1], [3, 2, 1], [3, 3, 1], [4, 2, 1], [3, 2, 2], [4, 3, 1], [4, 2, 2], [5, 2, 1], [3, 3, 2], [4, 3, 2], [5, 3, 1], [5, 3, 2], [4, 4, 2], [6, 3, 2], [7, 5, 3]]), n = a + b + c, cols = shuffle(['red', 'blue', 'green', 'white']).slice(0, 3); return int('combinatorics · arrangements', `${a} identical ${cols[0]} cups, ${b} identical ${cols[1]} cups and ${c} identical ${cols[2]} cup${c > 1 ? 's' : ''} are placed in a row. How many different arrangements are there?`, Math.round(fact(n) / (fact(a) * fact(b) * fact(c)))); };
const complementCount = () => { const kind = ri(1, 3), d = ri(1, 9); if (kind === 1) return int('combinatorics · complement counting', `How many three-digit numbers do not contain the digit ${d}?`, 648); if (kind === 2) { const e = pick([1, 2, 3, 4, 5, 6, 7, 8, 9].filter((x) => x !== d)); return int('combinatorics · complement counting', `How many three-digit numbers contain neither the digit ${d} nor the digit ${e}?`, 7 * 8 * 8); } return int('combinatorics · complement counting', `How many three-digit numbers contain the digit ${d} at least once?`, 900 - 648); };
const digitRestricted = () => { const ds = [0, ...shuffle([1, 2, 3, 4, 5, 6, 7, 8, 9]).slice(0, 5)].sort((a, b) => a - b), bound = pick([300, 400, 500, 600]), odd = ri(1, 2) === 1; let c = 0; for (const a of ds) for (const b of ds) for (const e of ds) { if (a === 0 || a === b || b === e || a === e) continue; const n = 100 * a + 10 * b + e; if (n > bound && (odd ? n % 2 === 1 : n % 2 === 0)) c++; } if (!c) return null; return int('combinatorics · forming numbers', `Using three different digits from ${ds.join(', ')}, how many ${odd ? 'odd' : 'even'} three-digit numbers greater than ${bound} can be formed?`, c); };

// each category's kinds, with the years they suit and the moon that leans on them ('hk' number theory and counting, 'bkk' logic set-pieces and arithmetic tricks)
const KINDS = {
  LT: [['balance', balance, [1, 6], 'bkk'], ['guess two-digit', guessTwoDigit, [2, 4]], ['guess four-digit', guessFourDigit, [5, 6]], ['periodic', periodic, [3, 6], 'bkk'], ['pigeonhole', pigeonhole, [3, 6]], ['chicken and rabbit', chickenRabbit, [4, 6], 'bkk'], ['speed', speed, [5, 6], 'bkk'], ['ages', ages, [3, 6]], ['dates', daysBetween, [3, 6]], ['figure patterns', rowsOfDots, [1, 4]],
    ['cryptarithm', cryptAB, [2, 4], 'hk'], ['work and rest', workRest, [1, 4], 'bkk'], ['give and take', giveTake, [3, 6]], ['defined operations', definedOp, [4, 6], 'hk'], ['sum and multiple', sumMultiple, [3, 6]], ['number sequences', decreasingDiffs, [2, 5], 'bkk'], ['averages', averageMissing, [3, 6]], ['ratio chicken and rabbit', ratioChickenRabbit, [5, 6], 'bkk'], ['working backwards with fractions', workBackFractions, [4, 6]], ['working backwards', workBackOps, [4, 6]]],
  AR: [['smart addition', smartAdd, [1, 3], 'bkk'], ['Gaussian addition', gauss, [3, 6], 'bkk'], ['smart four-digit', smartFourDigit, [4, 6], 'bkk'], ['multiplication trick', multiplyTrick, [4, 6], 'bkk'], ['geometric sum', geometricSum, [5, 6], 'bkk'], ['sum of squares', squaresSum, [5, 6]], ['decimals', decimalTrick, [5, 6]], ['fraction chain', fractionChain, [5, 6]], ['missing digit', missingDigit, [1, 4]],
    ['multiples sum', multiplesSum, [2, 6], 'bkk'], ['triangular numbers', triangularSum, [4, 6]], ['mixed calculation', computeMixed, [4, 6]], ['squares', squareMinus, [5, 6]], ['squares in a range', squaresRange, [5, 6]], ['telescoping', telescopingOdd, [5, 6]], ['series average', seriesAverage, [5, 6]], ['eggs in boxes', eggsBoxes, [1, 3]], ['smallest multiple', smallestMultiple, [2, 4]]],
  NT: [['odd and even', evenOddCount, [1, 3]], ['largest with a digit sum', largestWithDigitSum, [1, 3]], ['digit count', digitCount, [2, 6], 'hk'], ['primes', primesQ, [4, 6], 'hk'], ['LCM and HCF', lcmHcf, [4, 6]], ['divisibility', divisibility, [4, 6], 'hk'], ['number of factors', factorsCount, [4, 6], 'hk'], ['sum of factors', factorsSum, [5, 6], 'hk'], ['unit digit', unitDigit, [5, 6], 'hk'], ['remainders', remainders, [5, 6], 'hk'], ['digit sums', digitSumProperty, [3, 5]],
    ['evens in a range', evensInRange, [2, 4]], ['unit digit of a sum', unitDigitSumPowers, [5, 6], 'hk'], ['three remainders', crtLargest, [5, 6], 'hk'], ['coprime', phiCount, [6, 6], 'hk'], ['divisible by either', divisibleEither, [4, 6], 'hk'], ['largest and smallest', largestSmallestDigits, [2, 4]]],
  GE: [['shapes and solids', shapesQ, [1, 2]], ['counting figures', countSquares, [1, 6]], ['perimeter and area', perimeterArea, [3, 6]], ['angles', anglesQ, [4, 6]], ['circles', circleQ, [5, 6]], ['volume and surface', volumeSurface, [5, 6]], ['ratio of areas', areaRatio, [5, 6]],
    ['pyramids and prisms', pyramidPrism, [3, 6]], ['smallest and largest area', minMaxArea, [4, 6]], ['exterior angles', exteriorAngle, [5, 6]], ['coins round a square', coinsSquare, [1, 3]], ['wire into squares', wireSquares, [3, 6]]],
  CO: [['two-digit numbers', twoDigitFromDigits, [1, 4]], ['pairs', pairsCount, [1, 3]], ['three-digit numbers', threeDigitFromDigits, [4, 6], 'hk'], ['handshakes', handshakes, [2, 6]], ['routing', routing, [3, 6], 'hk'], ['distribution', distribution, [4, 6]], ['excess and deficiency', excessDeficiency, [4, 6], 'bkk'], ['combinations', combinationsQ, [5, 6], 'hk'], ['permutations', permutationsQ, [5, 6], 'hk'], ['inclusion and exclusion', inclusionExclusion, [5, 6], 'hk'], ['dice', diceWays, [5, 6]],
    ['routes', routesCompound, [2, 5], 'hk'], ['big teams', bigCombinations, [6, 6], 'hk'], ['arrangements', multinomial, [6, 6], 'hk'], ['complement counting', complementCount, [5, 6], 'hk'], ['restricted digits', digitRestricted, [4, 6]]],
};
export const CATEGORIES = Object.freeze({ LT: 'Logical thinking', AR: 'Arithmetic', NT: 'Number theory', GE: 'Geometry', CO: 'Combinatorics' });
// the pool a moon draws from: every kind that suits the year, its own leanings first three times in four (buildHeat picks by category)
function pool(year, lean) {
  const out = [];
  for (const [cat, kinds] of Object.entries(KINDS)) {
    const fit = kinds.filter(([, , [lo, hi]]) => year >= lo && year <= hi), own = fit.filter((k) => k[3] === lean), copies = own.length ? 3 : 0;
    for (const [name, gen, , tag] of fit) for (let c = 0; c < (tag === lean ? copies : 1); c++) out.push({ cat: `${cat}:${name}`, gen, sections: [cat] });
  }
  return out;
}
const SHAPE = slots([['LT', 'sa', 2], ['AR', 'sa', 2], ['NT', 'sa', 2], ['GE', 'sa', 2], ['CO', 'sa', 2]]);
/** Ten short answers, two a category in the real order; `lean` names the moon whose signature kinds come up three times as often. */
export function ocecHeat(year, lean) {
  return buildHeat(SHAPE, pool(year, lean), year).map((q) => ({ ...q, cat: q.cat.replace(/^[A-Z]{2}:/, `${CATEGORIES[q.section].toLowerCase()} · `) }));
}
