// 🌴 PHI-MOON — practice modelled on PhIMO (the Philippine International Mathematical Olympiad, Math Olympiads Training League);
// not affiliated. Its own family, not OCEC's: the Philippine K-12 strands — Number and Number Sense, Geometry, Pattern and
// Algebra, Measurements, Statistics and Probability — at every grade, in a paper that ramps from ten multiple-choice questions
// of five options with "None of the above" (2 marks) through ten short answers (3) to five hard ones (5): the 2025 heat papers,
// 25 questions in 90 minutes, no calculator, no penalty (the source check of 20 Sep 2026). So a heat is five two-mark multiple
// choice — one from each strand — then three three-mark and two five-mark typed answers drawn across the strands, every strand
// carrying a kind for each tier; the kinds are the staples of the 2025 papers and the Malaysian mock: tiling and stacked cubes,
// rule machines and symbol equations, remainders and LCM, frogs in wells, pie charts, pigeonholes, two dice (20 Sep 2026).
import { ri, pick, shuffle, sum, names, int, dec, frac, mcOnly, withFigure, grid, table, bars, buildHeat, slots, gcd, lcm, cap, factorsOf, isPrime, digitsOf, ord } from './common.mjs';

const low = (y) => y <= 2, mid = (y) => y >= 3 && y <= 4;
// four things of very different lengths, from a window of a long table (shortest first), so the longest and the shortest of the four
// are not the same two things every time (kept for any moon that still wants it)
export const LENGTHS = [['an ant', 0.5], ['a paper clip', 3], ['an eraser', 4], ['a pencil', 15], ['a ruler', 30], ['a chair', 90], ['a door', 200], ['a car', 400], ['a bus', 1200], ['a football field', 10000]];
export const lengthWindow = () => { const lo = ri(0, LENGTHS.length - 4); return shuffle(LENGTHS.slice(lo, lo + 4)); };
const pie = (title, pairs) => ({ kind: 'pie', title, slices: pairs.map(([label, pct]) => ({ label, pct })) });
const choose = (n, k) => { let r = 1; for (let i = 1; i <= k; i++) r = (r * (n - k + i)) / i; return Math.round(r); };
const hm = (t) => `${Math.floor(t / 60)}:${String(t % 60).padStart(2, '0')}`;
const KIDS = ['Ana', 'Ben', 'Carlo', 'Dina', 'Elsa'];
const bagOf = (cs, counts, it) => `${cs.map((c, i) => `${counts[i]} ${c}`).join(', ').replace(/, (\d+ \w+)$/, ' and $1')} ${it}`;

// ---- Number and Number Sense ----
const nsP1 = (y) => {
  const kind = ri(1, 3);
  if (low(y)) {
    if (kind === 1) { const a = ri(6, 40), d = ri(2, 15); return int('number sense · more than', `There are ${a} red balloons, and ${d} more blue balloons than red ones. How many balloons are there altogether?`, 2 * a + d); }
    if (kind === 2) { const m = pick([5, 6, 7, 8, 9]), r = ri(1, m - 1); let n = 99; while (n % m !== r) n--; return int('number sense · remainders', `What is the largest two-digit number that leaves a remainder of ${r} when divided by ${m}?`, n); }
    const price = pick([2, 3, 4, 5]), [word, k] = pick([['A quarter', 4], ['Half', 2]]); return int('number sense · fractions', `${word} of a pizza costs $${price}. How much does the whole pizza cost, in dollars?`, price * k);
  }
  if (mid(y)) {
    if (kind === 1) { const d = pick([3, 4, 5, 6, 8]), n = d * ri(3, 12), k = ri(1, d - 1); if (gcd(k, d) !== 1) return null; return int('number sense · fractions', `What is ${k}/${d} of ${n}?`, (n / d) * k); }
    if (kind === 2) { const m = pick([6, 7, 8, 9, 11, 12]), r = ri(1, m - 1); let n = 999; while (n % m !== r) n--; return int('number sense · remainders', `What is the largest three-digit number that leaves a remainder of ${r} when divided by ${m}?`, n); }
    const a = ri(2, 6), b = ri(a + 1, 9), u = ri(2, 12); if (gcd(a, b) !== 1) return null; return int('number sense · ratio', `Two friends share ${(a + b) * u} stickers in the ratio ${a} : ${b}. How many does the one with more get?`, b * u);
  }
  if (kind === 1) { const p = pick([15, 20, 25, 30, 40, 60, 75]), t = pick([40, 60, 80, 120, 200]); if ((t * p) % 100) return null; return int('number sense · percentages', `What is ${p}% of ${t}?`, (t * p) / 100); }
  if (kind === 2) { const fs = shuffle([[2, 3], [3, 5], [5, 8], [7, 12], [4, 7], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12], [4, 5], [5, 9]]).slice(0, 4), best = fs.reduce((a, b) => (b[0] * a[1] > a[0] * b[1] ? b : a)); return mcOnly('number sense · fractions', 'Which fraction is the greatest?', `${best[0]}/${best[1]}`, fs.filter((f) => f !== best).map((f) => `${f[0]}/${f[1]}`)); }
  const n = pick([12, 18, 20, 24, 30, 36, 40, 48, 60]); return int('number sense · factors', `How many different rectangles with whole-number sides have an area of ${n} square units?`, Math.ceil(factorsOf(n).length / 2));
};
const nsP2 = (y) => {
  if (low(y)) {
    if (ri(1, 2) === 1) { const cols = shuffle(['red', 'green', 'blue', 'yellow']).slice(0, 3), pat = [...Array(4).fill(cols[0]), ...Array(2).fill(cols[1]), cols[2]], n = ri(15, 60), ask = ri(0, 2), cnt = Math.floor(n / 7) * [4, 2, 1][ask] + pat.slice(0, n % 7).filter((c) => c === cols[ask]).length; return int('number sense · repeating patterns', `Balloons hang in a repeating pattern: 4 ${cols[0]}, then 2 ${cols[1]}, then 1 ${cols[2]}, and again. Of the first ${n} balloons, how many are ${cols[ask]}?`, cnt); }
    const a = ri(3, 30), b = a + ri(8, 40); let c = 0; for (let k = a; k <= b; k++) if (k % 2) c++; return int('number sense · odd and even', `How many odd numbers are there from ${a} to ${b}?`, c);
  }
  if (mid(y)) {
    const kind = ri(1, 4);
    if (kind === 1) { const k = ri(5, 30); return int('number sense · fractions', `What is 1/2 of 1/4 of 1/8 of ${64 * k}?`, k); }
    if (kind === 2) { const [a, b] = pick([[4, 7], [3, 5], [4, 6], [6, 8], [5, 7], [3, 8]]); return int('number sense · common multiples', `Two friends visit a library, one every ${a} days and the other every ${b} days. They meet there today. In how many days will they next meet there?`, lcm(a, b)); }
    if (kind === 3) { const start = pick([3, 5, 6, 8, 10]), every = pick([2, 3, 4, 5]), times = ri(3, 5); return int('number sense · doubling', `A colony of bacteria doubles every ${every} hours. There are ${start} now. How many will there be in ${every * times} hours?`, start * 2 ** times); }
    const t = pick([42, 60, 72, 90, 120]), d1 = pick([5, 6]), d2 = pick([4, 5]), white = t / d1; if (!Number.isInteger(white)) return null; const rest = t - white, blue = rest / d2; if (!Number.isInteger(blue)) return null; return int('number sense · fraction of a remainder', `Of ${t} cupcakes, 1/${d1} are white and 1/${d2} of the rest are blue. The others are red. How many are red?`, rest - blue);
  }
  const kind = ri(1, 3);
  if (kind === 1) { const h = pick([6, 8, 12, 15, 23, 46]), p = pick([3, 4, 5, 7]), q = pick([2, 5, 8, 9]); if (gcd(p, q) !== 1) return null; return int('number sense · LCM and HCF', `The lowest common multiple of two numbers is ${h * p * q} and their highest common factor is ${h}. One of the numbers is ${h * p}. What is the other?`, h * q); }
  if (kind === 2) { const n = pick([120, 150, 180, 200, 240, 300, 360]), k = pick([4, 5, 6]); return int('number sense · factors', `${n} chairs are set out in equal rows, with more than ${k} rows and at least 2 chairs in each row. How many different numbers of rows are possible?`, factorsOf(n).filter((d) => d > k && n / d >= 2).length); }
  const k = ri(1, 8); return int('number sense · digits', `How many two-digit numbers become larger by ${9 * k} when their two digits are swapped?`, 9 - k);
};
const nsP3 = (y) => {
  if (low(y)) { if (ri(1, 2) === 1) { const N = pick([500, 800, 1000]), a = ri(2, 12), b = ri(2, 12); return int('number sense · place value', `Take ${a} tens and ${b} ones away from ${N}. What is left?`, N - 10 * a - b); } const d = ri(1, 9), n = pick([30, 40, 50]); let c = 0; for (let k = 1; k <= n; k++) if (digitsOf(k).includes(d)) c++; return int('number sense · digits', `The pages of a book are numbered 1 to ${n}. How many page numbers contain the digit ${d}?`, c); }
  if (mid(y)) { if (ri(1, 2) === 1) { const A = ri(10, 40), B = ri(10, 40), C = ri(10, 40), D = ri(10, 40); return int('number sense · sums', `Four numbers A, B, C and D add up to ${A + B + C + D}. B + C = ${B + C} and A + C + D = ${A + C + D}. What is C?`, C); } const parts = shuffle([100, 110, 120, 150, 90, 80]).slice(0, 3), u = ri(2, 12), w = names(3), i = ri(0, 2); return int('number sense · ratio', `${w.join(', ')} share $${sum(parts) * u} in the ratio of their heights, which are ${parts[0]} cm, ${parts[1]} cm and ${parts[2]} cm. How much does ${w[i]} get, in dollars?`, parts[i] * u); }
  const kind = ri(1, 3);
  if (kind === 1) { const N = ri(100, 2000); let p = 2; while (p * p <= N) { p++; while (!isPrime(p)) p++; } return int('number sense · factors', `What is the smallest number greater than ${N} that has exactly three factors?`, p * p); }
  if (kind === 2) { const n = pick([100, 120, 150, 200, 300]), a = pick([3, 4, 5]), b = pick([5, 6, 7, 8]); if (a === b) return null; return int('number sense · counting', `How many whole numbers from 1 to ${n} are divisible by ${a} or by ${b} (or both)?`, Math.floor(n / a) + Math.floor(n / b) - Math.floor(n / lcm(a, b))); }
  const [a, b, c] = pick([[4, 5, 7], [3, 4, 5], [4, 6, 9], [5, 6, 8], [3, 5, 7], [6, 8, 10]]), l = lcm(lcm(a, b), c), k = ri(2, Math.max(2, Math.floor(999 / l))), lo = Math.floor((k * l) / 100) * 100, hi = lo + 100; if (k * l > 999 || Math.floor(hi / l) - Math.floor(lo / l) !== 1 || (k * l) % 100 === 0) return null; return int('number sense · common multiples', `A library has between ${lo} and ${hi} books. They fill shelves of ${a}, of ${b} or of ${c} with none left over. How many books are there?`, k * l);
};
// ---- Geometry ----
const geP1 = (y) => {
  const kind = ri(1, 3);
  if (low(y)) { if (kind === 1) { const a = ri(2, 6), b = ri(2, 6); return int('geometry · shapes', `A picture is made of ${a} triangles and ${b} squares. How many sides do the shapes have altogether?`, 3 * a + 4 * b); } if (kind === 2) { const c = pick([['square', 4], ['rectangle', 2], ['equilateral triangle', 3]]); return int('geometry · symmetry', `How many lines of symmetry does a${c[0][0] === 'e' ? 'n' : ''} ${c[0]} have?`, c[1]); } return withFigure(int('geometry · counting figures', 'How many squares of every size are there in this 2 by 2 grid?', 5), grid('Count the squares', 2, 2)); }
  if (mid(y)) { if (kind === 1) { const l = ri(4, 20), w = ri(2, l - 1); return int('geometry · perimeter', `A rectangle is ${l} cm long and ${w} cm wide. What is its perimeter, in cm?`, 2 * (l + w)); } if (kind === 2) { const a = ri(30, 80), b = ri(20, 170 - a); return int('geometry · angles', `Two angles of a triangle are ${a}° and ${b}°. What is the third angle, in degrees?`, 180 - a - b); } const r = ri(2, 3), c = ri(3, 4); return withFigure(int('geometry · counting figures', `How many rectangles of every size (squares included) are there in this ${r} by ${c} grid?`, choose(r + 1, 2) * choose(c + 1, 2)), grid('Count the rectangles', r, c)); }
  if (kind === 1) { const r = pick([7, 14, 21]); return int('geometry · circles', `Taking π as 22/7, what is the area of a circle of radius ${r} cm, in cm²?`, (22 / 7) * r * r); }
  if (kind === 2) { const l = ri(3, 10), w = ri(2, 8), h = ri(2, 6); return int('geometry · volume', `A box is ${l} cm by ${w} cm by ${h} cm. What is its volume, in cm³?`, l * w * h); }
  const a = ri(50, 120), b = ri(50, 120), c = ri(40, 359 - a - b - 30); if (360 - a - b - c >= 180) return null; return int('geometry · angles', `Three angles of a quadrilateral are ${a}°, ${b}° and ${c}°. What is the fourth angle, in degrees?`, 360 - a - b - c);
};
const geP2 = (y) => {
  const kind = ri(1, 2);
  if (low(y)) { if (kind === 1) { const r = pick([3, 4, 5]), c = pick([3, 5, 7]); return withFigure(int('geometry · tiling', `A ${r} by ${c} board is covered with tiles that are 2 squares long and 1 square wide. What is the greatest number of tiles that fit without overlapping?`, Math.floor((r * c) / 2)), grid('Fit the tiles', r, c)); } const l = pick([2, 3]), w = pick([2, 3]), h = pick([2, 3]), placed = ri(1, l * w * h - 2); return int('geometry · solids', `Unit cubes are stacked to build a block ${l} cubes long, ${w} cubes wide and ${h} cubes tall. ${placed} cubes are in place. How many more cubes are needed?`, l * w * h - placed); }
  if (mid(y)) { if (kind === 1) { const l = ri(2, 5), w = ri(2, 5), h = ri(2, 5); return int('geometry · surface area', `A block ${l} cm by ${w} cm by ${h} cm is built from centimetre cubes. What is its surface area, in cm²?`, 2 * (l * w + w * h + l * h)); } const n = pick([3, 4]), placed = ri(5, n ** 3 - 5); return int('geometry · solids', `Unit cubes are being stacked to build a ${n} by ${n} by ${n} cube. ${placed} cubes are in place. How many more cubes are needed?`, n ** 3 - placed); }
  if (kind === 1) { const L = ri(10, 20), W = ri(6, 12); return int('geometry · area', `A rectangular garden is ${L} m by ${W} m. A path 1 m wide runs all the way around the inside edge. What is the area of the path, in m²?`, L * W - (L - 2) * (W - 2)); }
  const n = pick([3, 4, 5]), what = pick([['exactly two faces painted', 12 * (n - 2)], ['no face painted', (n - 2) ** 3], ['at least two faces painted', 8 + 12 * (n - 2)]]); return int('geometry · solids', `A ${n} by ${n} by ${n} cube is painted on the outside and cut into ${n ** 3} unit cubes. How many unit cubes have ${what[0]}?`, what[1]);
};
const geP3 = (y) => {
  if (low(y)) { const r = pick([2, 3]), c = pick([3, 4]); return withFigure(int('geometry · counting figures', `How many rectangles of every size (squares included) are there in this ${r} by ${c} grid?`, choose(r + 1, 2) * choose(c + 1, 2)), grid('Count the rectangles', r, c)); }
  if (mid(y)) { const n = pick([3, 4, 5]); return int('geometry · solids', `A ${n} by ${n} by ${n} cube is painted on the outside and cut into ${n ** 3} unit cubes. How many unit cubes have exactly one face painted?`, 6 * (n - 2) * (n - 2)); }
  if (ri(1, 2) === 1) { const n = pick([3, 4, 5]); return int('geometry · surface area', `A ${n} by ${n} by ${n} cube is built from unit cubes, and then its 8 corner cubes are removed. What is the surface area of the shape that is left, in square units?`, 6 * n * n); }
  const l1 = ri(6, 15), w = ri(3, 8), h = ri(2, 6), l2 = ri(3, 10), h2 = ri(2, 6); return int('geometry · volume', `Two blocks are glued together: one ${l1} cm by ${w} cm by ${h} cm and one ${l2} cm by ${w} cm by ${h2} cm. What is the volume of the solid, in cm³?`, l1 * w * h + l2 * w * h2);
};
// ---- Pattern and Algebra ----
const RULES = [['a + b', (a, b) => a + b], ['a × b', (a, b) => a * b], ['2a + b', (a, b) => 2 * a + b], ['a + 2b', (a, b) => a + 2 * b], ['a × b − a', (a, b) => a * b - a], ['a² + b²', (a, b) => a * a + b * b], ['a × b + a + b', (a, b) => a * b + a + b]];
const machine = (rules, hi, cat, star) => { const [, f] = pick(rules), ex = Array.from({ length: 3 }, () => [ri(1, hi), ri(1, hi)]), a = ri(2, hi + 1), b = ri(2, hi + 1); if (new Set(ex.map(String)).size < 3 || rules.some(([, g]) => g !== f && ex.every(([p, q]) => g(p, q) === f(p, q)))) return null; if (star) return int(cat, `${ex.map(([p, q]) => `${p} ⍟ ${q} = ${f(p, q)}`).join(', ')}. Following the same rule, what is ${a} ⍟ ${b}?`, f(a, b), { read: `${ex.map(([p, q]) => `${p} star ${q} is ${f(p, q)}`).join(', ')}. Following the same rule, what is ${a} star ${b}?` }); return int(cat, `A machine turns two numbers into one: ${ex.map(([p, q]) => `${p} and ${q} give ${f(p, q)}`).join('; ')}. What does it give for ${a} and ${b}?`, f(a, b)); };
const paP1 = (y) => {
  const kind = ri(1, 3);
  if (low(y)) { if (kind === 1) { const s = ri(1, 10), k = pick([2, 3, 5]), n = ri(6, 9); return int('pattern and algebra · number patterns', `Look at the pattern: ${s}, ${s + k}, ${s + 2 * k}, ${s + 3 * k}, … What is the ${ord(n)} number?`, s + (n - 1) * k); } if (kind === 2) { const a = ri(2, 9), b = ri(1, 9); return int('pattern and algebra · missing number', `${a} + ▢ = ${a + b}. What number goes in the box?`, b, { read: `${a} plus what number makes ${a + b}?` }); } const s = ri(5, 20), terms = [s, s + 1, s + 3, s + 6, s + 10, s + 15]; return int('pattern and algebra · number patterns', `${terms[0]}, ${terms[1]}, ___, ${terms[3]}, ${terms[4]}, ${terms[5]}. What number is missing?`, terms[2]); }
  if (mid(y)) { if (kind === 1) { const s = ri(2, 20), k = ri(3, 9), n = ri(10, 20); return int('pattern and algebra · number patterns', `${s}, ${s + k}, ${s + 2 * k}, ${s + 3 * k}, … What is the ${ord(n)} number in the pattern?`, s + (n - 1) * k); } if (kind === 2) { const a = ri(2, 9), x = ri(2, 12); return int('pattern and algebra · missing number', `${a} × ▢ = ${a * x}. What number goes in the box?`, x, { read: `${a} times what number makes ${a * x}?` }); } const k = ri(2, 4), n = ri(5, 10); return int('pattern and algebra · growing patterns', `Figure 1 is made of ${k + 1} sticks, Figure 2 of ${2 * k + 1}, Figure 3 of ${3 * k + 1}, and each figure has ${k} more sticks than the one before. How many sticks are in Figure ${n}?`, n * k + 1); }
  if (kind === 1) { const a = ri(2, 9), x = ri(2, 20), b = ri(1, 30); return int('pattern and algebra · equations', `If ${a}x + ${b} = ${a * x + b}, what is x?`, x); }
  if (kind === 2) { const n = ri(6, 15); return int('pattern and algebra · number patterns', `1, 4, 9, 16, 25, … What is the ${ord(n)} number in the pattern?`, n * n); }
  const s = ri(1000, 1020), d = pick([15, 25, 30]), n = ri(20, 60); return int('pattern and algebra · number patterns', `${s}, ${s + d}, ${s + 2 * d}, ${s + 3 * d}, … What is the ${ord(n)} number in the pattern?`, s + (n - 1) * d);
};
const paP2 = (y) => {
  if (low(y)) { if (ri(1, 2) === 1) return machine(RULES.slice(0, 3), 6, 'pattern and algebra · rule machines', false); const [s1, s2] = shuffle(['♥', '▲', '★', '●']).slice(0, 2), a = ri(2, 12), b = ri(1, 12); return int('pattern and algebra · symbol equations', `${s1} + ${s1} + ${s2} = ${2 * a + b} and ${s1} + ${s2} = ${a + b}. Each symbol stands for one number. What number is ${s1}?`, a); }
  if (mid(y)) { const kind = ri(1, 3); if (kind === 1) return machine(RULES.slice(0, 5), 9, 'pattern and algebra · rule machines', false); if (kind === 2) { const A = ri(10, 40), B = ri(10, 40), C = ri(10, 40); return int('pattern and algebra · sums', `A + B = ${A + B}, B + C = ${B + C} and A + C = ${A + C}. What is B?`, B); } const [s1, s2] = shuffle(['♥', '▲', '★', '●']).slice(0, 2), a = ri(3, 30), b = ri(1, a - 1); return int('pattern and algebra · symbol equations', `${s1} + ${s2} = ${a + b} and ${s1} − ${s2} = ${a - b}. Each symbol stands for one number. What number is ${s1}?`, a); }
  const kind = ri(1, 3);
  if (kind === 1) { const x = ri(3, 30), k = ri(2, 6), d = ri(1, 20); if (k * x - d <= 0) return null; return int('pattern and algebra · equations', `A number is multiplied by ${k}, then ${d} is subtracted, and the result is ${k * x - d}. What is the number?`, x); }
  if (kind === 2) return machine(RULES, 9, 'pattern and algebra · rule machines', true);
  const o = ri(2, 30), t = ri(1, 40); return int('pattern and algebra · symbol equations', `△ + ○ + △ = ${2 * t + o} and ○ + ○ + ○ = ${3 * o}. What is ○ × △?`, o * t, { read: `Triangle plus circle plus triangle is ${2 * t + o}; three circles make ${3 * o}. What is circle times triangle?` });
};
const paP3 = (y) => {
  if (low(y)) { const A = ri(3, 15), B = ri(3, 15), C = ri(3, 15); return int('pattern and algebra · sums', `A + B = ${A + B}, B + C = ${B + C} and A + C = ${A + C}. What is B?`, B); }
  if (mid(y)) { if (ri(1, 2) === 1) return machine(RULES, 12, 'pattern and algebra · rule machines', true); const o = ri(2, 20), t = ri(1, 20); return int('pattern and algebra · symbol equations', `△ + ○ + △ = ${2 * t + o} and ○ + ○ + ○ = ${3 * o}. What is ○ × △?`, o * t, { read: `Triangle plus circle plus triangle is ${2 * t + o}; three circles make ${3 * o}. What is circle times triangle?` }); }
  const kind = ri(1, 3);
  if (kind === 1) { const a = ri(1, 5), d = pick([3, 4, 5, 6, 7]), n = ri(20, 60); return int('pattern and algebra · series', `What is ${a} + ${a + d} + ${a + 2 * d} + … + ${a + (n - 1) * d}?`, (n * (2 * a + (n - 1) * d)) / 2); }
  if (kind === 2) { const [t1, t2, h] = pick([[6, 3, 2], [4, 4, 2], [6, 12, 4], [10, 15, 6], [4, 12, 3], [8, 8, 4], [5, 20, 4], [3, 6, 2]]); return int('pattern and algebra · work rate', `Robot A can build a wall in ${t1} hours and robot B can build the same wall in ${t2} hours. Working together at the same rates, how many minutes do they take?`, h * 60); }
  const p = pick([4, 5, 8, 10]), n = ri(1, 4), q = pick([5, 6, 8, 10]); if (n >= q) return null; const x2 = ri(20, 200) * 10, c1 = ri(1, 9) * 10, c2 = ri(1, 9) * 10, x1 = ((x2 + c2) * q) / (q - n); if (!Number.isInteger(x1)) return null; const x0 = ((x1 + c1) * p) / (p - 1); if (!Number.isInteger(x0)) return null; const [w] = names(1); return int('pattern and algebra · working backwards', `${w} spent 1/${p} of ${w}'s savings and another $${c1} on a bag, then ${n}/${q} of the remaining money and another $${c2} on shoes. ${w} then had $${x2} left. How much did ${w} have at first, in dollars?`, x0);
};
// ---- Measurements ----
const frog = (D, up, slip) => { let n = 0, pos = 0; for (;;) { n++; pos += up; if (pos >= D) return n; pos -= slip; } };
const meP1 = (y) => {
  const kind = ri(1, 3);
  if (low(y)) { if (kind === 1) { const h = ri(1, 9), d = pick([1, 2, 3]); return int('measurement · time', `A film starts at ${h} o'clock and lasts ${d} hour${d > 1 ? 's' : ''}. It ends at ___ o'clock. What number goes in the blank?`, h + d); } if (kind === 2) { const a = ri(2, 9), b = ri(2, 9); return int('measurement · length', `A ribbon is ${a} cm long and another is ${b} cm long. How long are they altogether, in cm?`, a + b); } const s = ri(1, 9) * 60 + pick([0, 15, 30, 45]), d = pick([15, 30, 45]); return int('measurement · time', `A game starts at ${hm(s)} and ends at ${hm(s + d)}. How many minutes does it last?`, d); }
  if (mid(y)) { if (kind === 1) { const s = ri(1, 9) * 60 + pick([0, 10, 20, 30, 40, 50]), d = ri(5, 35) * 5; return int('measurement · time', `A lesson starts at ${hm(s)} and ends at ${hm(s + d)}. How many minutes does it last?`, d); } if (kind === 2) { const m = pick([5, 10, 15, 20, 25, 40, 45, 50]); return int('measurement · angles', `Through how many degrees does the minute hand of a clock turn in ${m} minutes?`, 6 * m); } const h = ri(1, 10), m = pick([0, 15, 30, 45]), d = pick([25, 40, 45, 70, 95]), e = h * 60 + m + d; return mcOnly('measurement · time', `A lesson starts at ${hm(h * 60 + m)} and lasts ${d} minutes. When does it end?`, hm(e), [hm(e + 15), hm(e - 15), hm(e + 30)]); }
  if (kind === 1) { const v = pick([40, 50, 60, 80]), t = ri(2, 5); return int('measurement · speed', `A car travels at ${v} km/h for ${t} hours. How far does it go, in km?`, v * t); }
  if (kind === 2) { const m = pick([5, 10, 15, 20, 25, 35, 40, 50]); return int('measurement · angles', `Through how many degrees does the minute hand of a clock turn in ${m} minutes?`, 6 * m); }
  const s = ri(9, 11) * 60 + pick([0, 15, 30, 45]), d = ri(20, 50) * 5, e = s + d; return int('measurement · time', `A film starts at ${hm(s)} am and ends at ${hm(e >= 13 * 60 ? e - 12 * 60 : e)} ${e >= 12 * 60 ? 'pm' : 'am'}. How many minutes does it last?`, d);
};
const meP2 = (y) => {
  if (low(y)) { if (ri(1, 2) === 1) { const D = ri(4, 9), up = ri(2, 3); return int('measurement · frog in a well', `A frog is at the bottom of a well ${D} m deep. Each hour it climbs ${up} m, then slips back 1 m before the next hour. After how many hours does it reach the top?`, frog(D, up, 1)); } const L = ri(12, 40), p = pick([3, 4, 5]); return int('measurement · length', `A ribbon ${L} cm long is cut into pieces ${p} cm long. How many centimetres are left over?`, L % p); }
  if (mid(y)) { const kind = ri(1, 3); if (kind === 1) { const D = ri(6, 12), up = ri(2, 4), slip = ri(1, up - 1), per = pick([10, 15, 20]); return int('measurement · frog in a well', `A frog is at the bottom of a well ${D} m deep. Every ${per} minutes it climbs ${up} m, then slips back ${slip} m before the next climb. After how many minutes does it reach the top?`, frog(D, up, slip) * per); } if (kind === 2) { const L = ri(4, 20) * 5, W = ri(2, 12) * 5, k = pick([5, 10]); if ((2 * (L + W)) % k) return null; return int('measurement · perimeter', `Fence posts stand every ${k} m around the edge of a rectangular field ${L} m by ${W} m, with a post at each corner. How many posts are there?`, (2 * (L + W)) / k); } const h = ri(1, 12), m = pick([0, 10, 20, 30, 40, 50]), a = Math.abs(30 * (h % 12) - 5.5 * m), v = Math.min(a, 360 - a); if (v === 0) return null; return int('measurement · angles', `What is the smaller angle between the hands of a clock at ${h}:${String(m).padStart(2, '0')}, in degrees?`, v); }
  const kind = ri(1, 3);
  if (kind === 1) { const D = ri(10, 30), up = ri(3, 6), slip = ri(1, up - 1), per = pick([10, 15, 20, 30]); return int('measurement · frog in a well', `A frog is at the bottom of a well ${D} m deep. Every ${per} minutes it climbs ${up} m, then slips back ${slip} m before the next climb. After how many minutes does it reach the top?`, frog(D, up, slip) * per); }
  if (kind === 2) { const [v1, v2] = pick([[30, 60], [40, 60], [60, 30], [60, 40], [20, 60], [60, 20], [30, 20], [20, 30]]), d = pick([60, 120, 180, 240]), avg = (2 * d) / (d / v1 + d / v2); if (!Number.isInteger(avg) || !Number.isInteger(d / v1) || !Number.isInteger(d / v2)) return null; return int('measurement · speed', `A bus drives ${d} km from one town to another at ${v1} km/h and comes straight back the same way at ${v2} km/h. What is its average speed for the whole trip, in km/h?`, avg); }
  const h = ri(1, 12), m = pick([0, 10, 20, 30, 40, 50]), a = Math.abs(30 * (h % 12) - 5.5 * m), v = Math.min(a, 360 - a); if (v === 0) return null; return int('measurement · angles', `What is the smaller angle between the hands of a clock at ${h}:${String(m).padStart(2, '0')}, in degrees?`, v);
};
const meP3 = (y) => {
  if (low(y)) { const per = ri(2, 3), a = ri(3, 4), c = ri(a + 2, 8); return int('measurement · intervals', `It takes ${per * (a - 1)} minutes to walk up from the 1st floor to the ${ord(a)} floor of a building. At the same pace, how many minutes does it take to walk up from the 1st floor to the ${ord(c)} floor?`, per * (c - 1)); }
  if (mid(y)) { if (ri(1, 2) === 1) { const D = ri(10, 25), up = ri(3, 5), slip = ri(1, up - 1), per = pick([10, 15, 20]); return int('measurement · frog in a well', `A frog is at the bottom of a well ${D} m deep. Every ${per} minutes it climbs ${up} m, then slips back ${slip} m before the next climb. After how many minutes does it reach the top?`, frog(D, up, slip) * per); } const gap = pick([4, 5, 6, 8, 10, 12, 15]), n = ri(8, 60); return int('measurement · intervals', `Trees are planted along one side of a ${gap * n} m road, ${gap} m apart, with a tree at each end. How many trees are there?`, n + 1); }
  const kind = ri(1, 3);
  if (kind === 1) { const p = pick([200, 250, 300, 350, 400, 500]), d1 = pick([10, 12, 15, 20]), d2 = pick([5, 10]), v = p * (1 - d1 / 100) * (1 - d2 / 100); if (Math.round(v * 100) / 100 !== Math.round(v * 1000) / 1000) return null; return dec('measurement · percentages', `A bike is priced at $${p}. The price is cut by ${d1}%, and then the new price is cut by another ${d2}%. What is the final price, in dollars?`, v); }
  if (kind === 2) { const a = pick([100, 200, 300, 400]), b = pick([100, 200, 300, 600]), pp = ri(10, 40), q = ri(10, 60), v = (a * pp + b * q) / (a + b); if (!Number.isInteger(v) || pp === q) return null; return int('measurement · mixtures', `${a} mL of a ${pp}% sugar solution is mixed with ${b} mL of a ${q}% sugar solution. What percentage of the mixture is sugar?`, v); }
  const N = 4 * ri(4, 20), p = ri(2, N / 2 - 1), q = N + 1 - p; return int('measurement · pages', `A booklet is made of sheets folded in half. Pages ${p} and ${q} are printed on the same side of one sheet, one on the left half and one on the right. How many pages does the booklet have?`, N);
};
// ---- Statistics and Probability ----
const spP1 = (y) => {
  const kids = shuffle(KIDS).slice(0, 4), what = pick(['books read', 'stickers', 'goals']);
  if (low(y)) { if (ri(1, 2) === 1) { const scale = pick([2, 3, 5]), vals = kids.map(() => ri(1, 6)); if (new Set(vals).size < 4) return null; const i = ri(0, 3); return withFigure(int('statistics · graphs', `The picture graph shows the ${what} of four children. Each ⭐ stands for ${scale}. How many ${what.split(' ')[0]} does ${kids[i]} have?`, vals[i] * scale), table(cap(what), ['Name', cap(what)], kids.map((n, k) => [n, '⭐'.repeat(vals[k])]))); } const r = ri(1, 6), b = ri(1, 6), cols = shuffle(['red', 'blue', 'green', 'yellow']).slice(0, 2); if (r === b) return null; return mcOnly('probability · chance', `A bag has ${r} ${cols[0]} and ${b} ${cols[1]} marbles. One is taken without looking. Which is true?`, r > b ? `${cols[0]} is more likely` : `${cols[1]} is more likely`, [r > b ? `${cols[1]} is more likely` : `${cols[0]} is more likely`, 'both are equally likely', 'it cannot be told']); }
  if (mid(y)) { if (ri(1, 2) === 1) { const vals = kids.map(() => ri(2, 30)); if (new Set(vals).size < 4) return null; const hi = vals.indexOf(Math.max(...vals)), lo = vals.indexOf(Math.min(...vals)); return withFigure(int('statistics · graphs', `The bar graph shows the ${what} of four children. How many more does ${kids[hi]} have than ${kids[lo]}?`, vals[hi] - vals[lo]), bars(cap(what), null, kids.map((n, k) => [n, vals[k]]))); } const parts = pick([[35, 20, 25, 20], [40, 25, 20, 15], [30, 30, 25, 15], [45, 25, 20, 10]]), labels = ['Food', 'Rent', 'Travel', 'Fun'], total = pick([1000, 2000, 4000]), i = ri(0, 1), j = ri(2, 3); return withFigure(int('statistics · pie charts', `The pie chart shows how a family spent $${total} in a month. How much went on ${labels[i]} and ${labels[j]} together, in dollars?`, ((parts[i] + parts[j]) * total) / 100), pie('Monthly spending', labels.map((l, k) => [l, parts[k]]))); }
  const kind = ri(1, 3);
  if (kind === 1) { const xs = Array.from({ length: 5 }, () => ri(3, 40)).sort((p, q) => p - q); return int('statistics · median', `What is the median of ${shuffle(xs).join(', ')}?`, xs[2]); }
  if (kind === 2) { const vals = kids.map(() => ri(5, 30)); if (new Set(vals).size < 4 || sum(vals) % 4) return null; return withFigure(int('statistics · average', `The bar graph shows the ${what} of four children. What is the mean number per child?`, sum(vals) / 4), bars(cap(what), null, kids.map((n, k) => [n, vals[k]]))); }
  const parts = pick([[35, 20, 25, 20], [40, 25, 20, 15], [30, 30, 25, 15]]), labels = ['Food', 'Rent', 'Travel', 'Fun'], total = pick([1200, 2400, 3600]), i = ri(0, 3); return withFigure(int('statistics · pie charts', `The pie chart shows how a family spent $${total} in a month. How much went on ${labels[i]}, in dollars?`, (parts[i] * total) / 100), pie('Monthly spending', labels.map((l, k) => [l, parts[k]])));
};
const spP2 = (y) => {
  if (low(y)) { const cs = shuffle(['red', 'blue', 'green', 'yellow']).slice(0, ri(2, 3)), counts = cs.map(() => ri(3, 9)); return int('probability · pigeonhole', `A bag has ${bagOf(cs, counts, 'marbles')}. Without looking, what is the smallest number you must take out to be sure of two of the same colour?`, cs.length + 1); }
  if (mid(y)) { if (ri(1, 2) === 1) { const m = pick([13, 15, 17, 20]); return int('probability · pigeonhole', `A pack has ${4 * m} cards, ${m} of each of 4 colours. Without looking, what is the smallest number of cards you must draw to be sure of at least one card of every colour?`, 3 * m + 1); } const t = ri(3, 11); let n = 0; for (let a = 1; a <= 6; a++) for (let c = 1; c <= 6; c++) if (a + c === t) n++; return int('probability · counting outcomes', `Two dice are rolled. In how many ways can the numbers add up to ${t}?`, n); }
  if (ri(1, 2) === 1) { const [e, f] = pick([['the two numbers add up to an even number', 18], ['the two numbers are the same', 6], ['the two numbers add up to 7', 6], ['both numbers are even', 9], ['both numbers are prime', 9], ['the two numbers add up to 10', 3]]); return frac('probability · fractions', `Two dice are rolled. What is the probability that ${e}? Give a fraction in its simplest form.`, f, 36); }
  const n = ri(4, 8), avg = ri(10, 40), x = ri(avg + 1, avg + 30), nu = (n * avg + x) / (n + 1); if (!Number.isInteger(nu)) return null; return int('statistics · average', `The mean of ${n} numbers is ${avg}. When ${x} is added to the list, what is the new mean?`, nu);
};
const spP3 = (y) => {
  if (low(y)) { const cs = shuffle(['red', 'blue', 'green', 'yellow']).slice(0, 3), counts = cs.map(() => ri(4, 9)); return int('probability · pigeonhole', `A bag has ${bagOf(cs, counts, 'marbles')}. Without looking, what is the smallest number you must take out to be sure of three of the same colour?`, 2 * cs.length + 1); }
  if (mid(y)) { const cs = shuffle(['red', 'blue', 'green', 'yellow']).slice(0, 3), counts = cs.map(() => ri(5, 40)); if (new Set(counts).size < 3) return null; return int('probability · pigeonhole', `A box has ${bagOf(cs, counts, 'balls')}. Without looking, what is the smallest number of balls you must take out to be sure of at least one ball of every colour?`, sum(counts) - Math.min(...counts) + 1); }
  if (ri(1, 2) === 1) { const a = ri(2, 4), b = ri(2, 4), tot = choose(a + b, 2); return frac('probability · two draws', `A bag holds ${a} red and ${b} blue marbles. Two are taken out without looking. What is the probability that both are red? Give a fraction in its simplest form.`, (a * (a - 1)) / 2, tot); }
  const cs = shuffle(['red', 'blue', 'green', 'yellow']).slice(0, 4), counts = cs.map(() => ri(5, 40)), k = ri(3, 6); if (new Set(counts).size < 4) return null; return int('probability · pigeonhole', `A box has ${bagOf(cs, counts, 'balls')}. Without looking, what is the smallest number of balls you must take out to be sure of ${k} balls of the same colour?`, 4 * (k - 1) + 1);
};

// each strand carries a kind for each tier: Part 1 two-mark multiple choice, then three-mark and five-mark typed answers
const T = (cat, gen, ...sections) => ({ cat, gen, sections });
const POOL = [T('number sense', nsP1, 'P1'), T('number sense · 3', nsP2, 'P2'), T('number sense · 5', nsP3, 'P3'), T('geometry', geP1, 'P1'), T('geometry · 3', geP2, 'P2'), T('geometry · 5', geP3, 'P3'), T('pattern and algebra', paP1, 'P1'), T('pattern and algebra · 3', paP2, 'P2'), T('pattern and algebra · 5', paP3, 'P3'), T('measurement', meP1, 'P1'), T('measurement · 3', meP2, 'P2'), T('measurement · 5', meP3, 'P3'), T('statistics and probability', spP1, 'P1'), T('statistics and probability · 3', spP2, 'P2'), T('statistics and probability · 5', spP3, 'P3')];
const SHAPE = slots([['P1', 'mc', 5], ['P2', 'sa', 3], ['P3', 'sa', 2]]);
export const heat = (year) => buildHeat(SHAPE, POOL, year, { options: 5, none: true }); // five choices with "None of the above", as the 2025 paper's Part 1 (the source check of 20 Sep 2026)
export const TOPICS = [
  { band: 'Grades 1–2', lines: ['Part 1, 2 marks: more than, remainders, a quarter of a pizza, sides altogether, patterns, o\'clock, picture graphs with a scale', 'Part 2, 3 marks: balloons in a repeating pattern, tiles on a board, stacked cubes, rule machines, a frog in a well, two of a colour', 'Part 2, 5 marks: tens and ones taken away, pages with a digit, rectangles in a grid, three sums, floors, three of a colour', 'five options, one of them “None of the above”'] },
  { band: 'Grades 3–4', lines: ['Part 1, 2 marks: fractions of a number, remainders, ratio, perimeter, angles, growing patterns, minutes, bar graphs, pie charts', 'Part 2, 3 marks: halves of quarters, meeting days, doubling, cupcakes, surface area, symbol equations, frogs, fence posts, cards of every colour', 'Part 2, 5 marks: four numbers and their sums, shares by height, painted cubes, star rules, trees along a road, every colour', 'five options, one of them “None of the above”'] },
  { band: 'Grades 5–6', lines: ['Part 1, 2 marks: percentages, the greatest fraction, rectangles of an area, circles, volume, x, the minute hand, medians, pie charts', 'Part 2, 3 marks: LCM and HCF, rows of chairs, swapped digits, paths round gardens, painted cubes, star rules, frogs, average speed, two dice', 'Part 2, 5 marks: exactly three factors, divisible by either, books on shelves, corner cubes removed, glued blocks, series', 'robots together, spending twice, two cuts in a price, mixtures, pages on a sheet, two draws, the same colour k times'] },
];
