// 🏮 T-MOON — practice modelled on WMI (the World Mathematics Invitational, Taiwan); not affiliated. The real preliminary is
// split into two named halves, Section A "Logical Reasoning" and Section B "Applications", every question multiple choice of
// four options, and its topic chart puts logical reasoning, word problems and a "math puzzle" at every grade from kindergarten
// up. Section A is 15 questions — ten at six marks, five at eight — and Section B ten at ten marks, 40 minutes each (wminv.org,
// the official samples with keys and the retyped 2022 papers; the source check of 20 Sep 2026). So a heat is three six-mark and
// two eight-mark logic questions, then five applications, one paper per grade as WMI has it; the kinds after "the paper's
// tiers" are the staples of those papers the first build lacked — sequences that interleave, rule machines, positions in a
// row, the assumption method, three balances, symbol equations, order of operations, unit traps, remainders, decimals.
import { ri, pick, shuffle, sum, names, thing, int, dec, mcOnly, withFigure, grid, table, bars, buildHeat, slots, isPrime, gcd, lcm, cap } from './common.mjs';

const DAYS = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];
const money = (n) => `Rp${n.toLocaleString('en-US')}`;
const SHAPES = [['🔺', 'triangle'], ['🔵', 'circle'], ['🟩', 'square'], ['⭐', 'star']];
const ord = (n) => `${n}${n % 100 >= 11 && n % 100 <= 13 ? 'th' : ['th', 'st', 'nd', 'rd'][n % 10] || 'th'}`;

// ---- Section A: logical reasoning ----
const lineUp = (y) => {
  const w = names(y <= 2 ? 3 : 4);
  if (y <= 2) return mcOnly('order and direction', `Three children stand in a line. ${w[0]} is in front of ${w[1]}. ${w[2]} is behind ${w[1]}. Who is second in the line?`, w[1], [w[0], w[2], 'Cannot be decided']);
  const order = shuffle(w), pos = ['first', 'second', 'third', 'last'], k = ri(1, 2); // first and last are stated: ask second or third
  return mcOnly('order and direction', `Four children stand in a line. ${order[0]} is first. ${order[2]} is right behind ${order[1]}. ${order[3]} is last. Who is ${pos[k]}?`, order[k], order.filter((_, i) => i !== k));
};
const shapePattern = (y) => {
  const [a, b, c] = shuffle(SHAPES).slice(0, 3), period = y <= 2 ? pick([[a, b], [a, b, b], [a, a, b]]) : pick([[a, b, c], [a, b, b, c], [a, c, b, b]]), n = ri(9, 14);
  const seq = Array.from({ length: n }, (_, i) => period[i % period.length]), next = period[n % period.length];
  return mcOnly('patterns', `${seq.map((s) => s[0]).join(' ')} … Which shape comes next?`, next[0], SHAPES.filter((s) => s !== next).map((s) => s[0]), { read: `The pattern goes ${seq.map((s) => s[1]).join(', ')}. Which shape comes next: ${SHAPES.map((s) => s[1]).join(', ')}?` });
};
const oddOne = (y) => {
  const kind = y <= 2 ? 1 : y <= 4 ? ri(1, 2) : ri(1, 3);
  if (kind === 1) { const evens = Array.from({ length: 3 }, () => ri(1, y <= 2 ? 20 : 50) * 2), odd = ri(1, y <= 2 ? 20 : 50) * 2 - 1; return mcOnly('odd one out', `Which number does not belong with the others: ${shuffle([...evens, odd]).join(', ')}?`, odd, evens); }
  if (kind === 2) { const m = pick([3, 4, 5]), ins = Array.from({ length: 3 }, () => ri(2, 12) * m); let out = ri(5, 60); while (out % m === 0) out++; return mcOnly('odd one out', `Which number does not belong with the others: ${shuffle([...ins, out]).join(', ')}?`, out, ins); }
  const ps = shuffle([11, 13, 17, 19, 23, 29, 31, 37, 41]).slice(0, 3), comp = pick([15, 21, 25, 27, 33, 35, 39]); return mcOnly('odd one out', `Three of these numbers are prime. Which one is not: ${shuffle([...ps, comp]).join(', ')}?`, comp, ps);
};
const balance = (y) => {
  const [a, b] = shuffle([['🍎', 'apple'], ['🍐', 'pear'], ['🍊', 'orange'], ['🍋', 'lemon']]).slice(0, 2), p = ri(1, 3), q = ri(p + 1, y <= 2 ? 4 : 6), k = ri(2, y <= 2 ? 3 : 5);
  return int('balance puzzles', `${a[0].repeat(p)} weighs the same as ${b[0].repeat(q)}. How many ${b[1]}s weigh the same as ${p * k} ${a[1]}s?`, q * k, { read: `${p} ${a[1]}${p > 1 ? 's' : ''} weigh the same as ${q} ${b[1]}s. How many ${b[1]}s weigh the same as ${p * k} ${a[1]}s?` });
};
const ages = (y) => {
  const [a, b] = names(2);
  if (y <= 4) { const age = ri(5, 12), d = ri(2, 8), yrs = ri(2, 10); return int('ages', `${a} is ${age} and ${b} is ${age + d}. How old will ${b} be when ${a} is ${age + yrs}?`, age + d + yrs); }
  const x = ri(6, 14), d = ri(2, 8), yrs = ri(2, 8); return int('ages', `${a} is ${d} years older than ${b}. In ${yrs} years their ages will add up to ${2 * x + d + 2 * yrs}. How old is ${b} now?`, x);
};
const calendar = (y) => { const d = ri(0, 6), n = y <= 2 ? ri(3, 12) : ri(14, 29), m = pick(['May', 'August', 'October']); return mcOnly('calendar logic', `The 1st of ${m} is a ${DAYS[d]}. What day of the week is the ${ord(n + 1)} of ${m}?`, DAYS[(d + n) % 7], DAYS.filter((_, i) => i !== (d + n) % 7).slice(0, 3)); };
const puzzle = (y) => {
  const kind = y <= 2 ? ri(1, 2) : ri(1, 3);
  if (kind === 1) { const s = ri(6, y <= 2 ? 20 : 100), a = ri(1, s - 1); return int('math puzzle', `${a} + ▢ = ${s}. What number is ▢?`, s - a, { read: `${a} plus what number makes ${s}?` }); }
  if (kind === 2) { const a = ri(2, y <= 2 ? 9 : 12); return int('math puzzle', `▢ + ▢ + ▢ = ${3 * a}. What number is ▢?`, a, { read: `Three of the same number add up to ${3 * a}. What is the number?` }); }
  const a = ri(2, 9), b = ri(2, 9); return int('math puzzle', `▢ × △ = ${a * b} and ▢ + △ = ${a + b}. What is the bigger of the two numbers?`, Math.max(a, b), { read: `Two numbers multiply to ${a * b} and add to ${a + b}. What is the bigger one?` });
};
const truth = () => { const w = names(3); return mcOnly('logic', `One of three friends broke a vase. ${w[0]} says: "It was ${w[1]}." ${w[1]} says: "It was not me." ${w[2]} says: "It was not me." Exactly one of them is telling the truth. Who broke the vase?`, w[2], [w[0], w[1], 'Cannot be decided']); }; // with one liar the third friend is the one who CANNOT have done it; with one truth-teller it is the only one who can (the source check of 20 Sep 2026)
const countRange = (y) => { const a = ri(3, y <= 2 ? 9 : 20), b = a + ri(5, y <= 2 ? 12 : 40); return int('counting', `How many whole numbers are there from ${a} to ${b}, counting both ${a} and ${b}?`, b - a + 1); };
const legs = (y) => { const n = ri(2, y <= 2 ? 6 : 12), m = ri(1, y <= 2 ? 5 : 10); return int('counting', `In a garden there are ${n} birds and ${m} cats. How many legs are there altogether?`, 2 * n + 4 * m); };
// the paper's tiers: Section A staples of the 2022 papers and the official samples
const orderOps = (y) => { if (y <= 4) { const b = ri(2, 9), q1 = ri(3, 30), d = ri(2, 9), q2 = ri(2, 12); return int('order of operations', `${b * q1} ÷ ${b} + ${d * q2} ÷ ${d} = ?`, q1 + q2); } if (ri(1, 2) === 1) { const b = pick([2, 3, 4, 5, 6]), q1 = ri(20, 120), c = ri(11, 30), e = ri(11, 30); return int('order of operations', `${b * q1} ÷ ${b} + ${c} × ${e} = ?`, q1 + c * e); } const b = ri(11, 29), q1 = ri(12, 40), d = ri(2, 9), q2 = ri(3, 12); return int('order of operations', `${b * q1} ÷ ${b} + ${d * q2} ÷ ${d} = ?`, q1 + q2); };
const interleaved = (y) => { const s1 = ri(1, 9), d1 = ri(2, y <= 2 ? 3 : 6), s2 = ri(1, 9), d2 = ri(1, y <= 2 ? 3 : 6); if (d1 === d2 && s1 === s2) return null; const n = y <= 2 ? 6 : 8, seq = Array.from({ length: n }, (_, i) => (i % 2 === 0 ? s1 + (i / 2) * d1 : s2 + ((i - 1) / 2) * d2)), next = n % 2 === 0 ? s1 + (n / 2) * d1 : s2 + ((n - 1) / 2) * d2; return int('number sequences', `${seq.join(', ')}, ? What number comes next?`, next); };
const RULES = [['a + b', (a, b) => a + b], ['a × b', (a, b) => a * b], ['2a + b', (a, b) => 2 * a + b], ['a + 2b', (a, b) => a + 2 * b], ['a × b − a', (a, b) => a * b - a], ['a + b + 1', (a, b) => a + b + 1], ['2a − b', (a, b) => 2 * a - b]];
const ruleGuess = (y) => { const pool = y <= 2 ? RULES.slice(0, 4) : RULES, [, f] = pick(pool), ex = Array.from({ length: 3 }, () => [ri(1, y <= 2 ? 6 : 9), ri(1, y <= 2 ? 6 : 9)]), a = ri(2, 9), b = ri(2, 9); if (ex.some(([p, q]) => f(p, q) < 0) || new Set(ex.map(String)).size < 3 || f(a, b) < 0) return null; if (pool.some(([, g]) => g !== f && ex.every(([p, q]) => g(p, q) === f(p, q)))) return null; return int('rule machine', `A machine turns two numbers into one: ${ex.map(([p, q]) => `${p} and ${q} give ${f(p, q)}`).join('; ')}. What does it give for ${a} and ${b}?`, f(a, b)); };
const positionRow = (y) => { const n = pick(y <= 2 ? [9, 13] : [13, 17, 21, 25, 29, 33]), c = (n + 1) / 2, w = names(3); return int('position in a row', `${n} children stand in a row. ${w[0]} is last. ${w[1]} is exactly in the centre of the row. ${w[2]} stands exactly halfway between ${w[1]} and ${w[0]}. Counting from the front, what position is ${w[2]} in?`, (c + n) / 2); };
const assumption = (y) => { if (ri(1, 2) === 1) { const n = y <= 2 ? 10 : pick([10, 15, 20]), plus = y <= 2 ? pick([2, 5]) : pick([5, 8, 10]), minus = y <= 2 ? 1 : pick([2, 3, 4]), right = ri(Math.ceil(n / 2), n - 1); return int('assumption method', `A quiz has ${n} questions. A right answer scores ${plus} points and a wrong answer loses ${minus} points. ${names(1)[0]} answered all ${n} and scored ${plus * right - minus * (n - right)}. How many answers were wrong?`, n - right); } const s = ri(y <= 2 ? 5 : 15, y <= 2 ? 12 : 40), clovers = ri(1, y <= 2 ? 2 : 4); return int('assumption method', `A vase holds shamrocks with 3 leaves each and ${clovers} clover${clovers > 1 ? 's' : ''} with 4 leaves each. There are ${3 * s + 4 * clovers} leaves altogether. How many shamrocks are there?`, s); };
const threeBalances = (y) => { const [f1, f2, f3] = shuffle([['🍎', 'apple'], ['🍌', 'banana'], ['🍒', 'cherry'], ['🍐', 'pear']]).slice(0, 3), hi = y <= 2 ? 20 : 400, vals = [ri(2, hi), ri(2, hi), ri(2, hi)], ask = ri(0, 2), [a, b, c] = vals; return int('three balances', `${f1[0]} and ${f2[0]} together weigh ${a + b} g. ${f2[0]} and ${f3[0]} together weigh ${b + c} g. ${f1[0]} and ${f3[0]} together weigh ${a + c} g. How much does one ${[f1, f2, f3][ask][1]} weigh, in grams?`, vals[ask], { read: `${cap(f1[1])} plus ${f2[1]} weighs ${a + b} grams; ${f2[1]} plus ${f3[1]} weighs ${b + c}; ${f1[1]} plus ${f3[1]} weighs ${a + c}. How much does one ${[f1, f2, f3][ask][1]} weigh?` }); };
const symbolEq = (y) => { if (y <= 4 || ri(1, 2) === 1) { const o = ri(2, 30), t = ri(1, 40), s1 = 2 * t + o, s2 = 3 * o; return int('symbol equations', `△ + ○ + △ = ${s1} and ○ + ○ + ○ = ${s2}. What is ○ × △?`, o * t, { read: `Triangle plus circle plus triangle is ${s1}; three circles make ${s2}. What is circle times triangle?` }); } const r = ri(2, 9); return int('symbol equations', `▢ × ▢ × ▢ = ${r ** 3}. What number is ▢?`, r, { read: `A number multiplied by itself three times gives ${r ** 3}. What is the number?` }); };
const adjacentRing = (y) => { const a = ri(1, 9), b = ri(1, 9), c = ri(0, 9), n = y <= 4 ? ri(8, 15) : ri(16, 40), row = [a, b, c], i = ri(4, n - 1), j = i + ri(1, 3); if (j > n) return null; return int('adjacent sums', `${n} boxes stand in a row, and the numbers in any three boxes next to each other add up to ${a + b + c}. The first box holds ${a} and the second holds ${b}. What is the number in box ${i} plus the number in box ${j}?`, row[(i - 1) % 3] + row[(j - 1) % 3]); };
const countFigures = (y) => { const n = y <= 2 ? 2 : y <= 4 ? 3 : 4; return withFigure(int('counting figures', `How many squares of every size are there in this ${n} by ${n} grid?`, sum(Array.from({ length: n }, (_, i) => (i + 1) * (i + 1)))), grid('Count the squares', n, n)); };

// ---- Section B: applications by grade ----
const addSubWords = (y) => { const [w] = names(1), it = thing(); if (y === 1) { const a = ri(3, 12), b = ri(2, 20 - a); return int('word problems', `${w} has ${a} ${it}s and gets ${b} more. How many ${it}s does ${w} have now?`, a + b); } const hi = y === 2 ? 100 : y <= 4 ? 1000 : 10000, a = ri(hi / 5, hi), b = ri(1, a); return int('word problems', `A shop had ${a} ${it}s and sold ${b}. How many are left?`, a - b); };
const measure = () => { const kind = ri(1, 2); if (kind === 1) { const m = ri(2, 9), cm = ri(1, 99); return int('units', `How many centimetres are there in ${m} m ${cm} cm?`, m * 100 + cm); } const kg = ri(1, 9), g = ri(1, 9) * 100; return int('units', `How many grams are there in ${kg} kg ${g} g?`, kg * 1000 + g); };
const dataQ = (y) => {
  const names4 = shuffle(['Adi', 'Sari', 'Bayu', 'Putri', 'Wira']).slice(0, 4), vals = names4.map(() => ri(1, y <= 2 ? 9 : 40)), what = pick(['stickers', 'books read', 'goals']);
  const hi = vals.indexOf(Math.max(...vals)), lo = vals.indexOf(Math.min(...vals)); if (hi === lo || new Set(vals).size !== vals.length) return null;
  const f = y <= 2 ? table(cap(what), ['Name', cap(what)], names4.map((n, i) => [n, '⭐'.repeat(vals[i])])) : bars(cap(what), null, names4.map((n, i) => [n, vals[i]]));
  const kind = ri(1, 3);
  const shows = `The ${y <= 2 ? 'picture graph' : 'bar chart'} shows how many ${what} four children have${y <= 2 ? ' (each ⭐ is one)' : ''}.`;
  if (kind === 1) return withFigure(mcOnly('data and graphs', `${shows} Who has the most?`, names4[hi], names4.filter((_, i) => i !== hi)), f);
  if (kind === 2) return withFigure(int('data and graphs', `${shows} How many more does ${names4[hi]} have than ${names4[lo]}?`, vals[hi] - vals[lo]), f);
  return withFigure(int('data and graphs', `${shows} How many altogether?`, sum(vals)), f);
};
const shapesQ = () => { const c = pick([['How many sides does a hexagon have?', 6, [5, 8, 4]], ['How many sides does a pentagon have?', 5, [6, 4, 8]], ['How many corners does a rectangle have?', 4, [3, 6, 8]], ['How many sides does an octagon have?', 8, [6, 7, 10]]]); return mcOnly('shapes', c[0], c[1], c[2]); };
const mulDiv = (y) => { const kind = ri(1, 2), [w] = names(1), it = thing(); if (kind === 1) { const n = ri(2, y === 2 ? 5 : 9), k = ri(2, y === 2 ? 5 : 9); return int('multiplication and division', `${w} puts ${k} ${it}s in each of ${n} boxes. How many ${it}s is that?`, n * k); } const k = ri(2, y === 2 ? 5 : 9), n = ri(2, y === 2 ? 5 : 12); return int('multiplication and division', `${w} shares ${n * k} ${it}s equally among ${k} friends. How many does each friend get?`, n); };
const moneyQ = (y) => { const [w] = names(1); if (y <= 4) { const p = ri(2, 20) * 500, n = ri(2, 6), had = p * n + ri(1, 10) * 1000; return int('money', `${w} has ${money(had)} and buys ${n} ${thing()}s at ${money(p)} each. How much money is left, in rupiah?`, had - p * n, { decoys: shuffle([had - p * n + 1000, had - p * n - 1000, had - p * n + 500, had - p * n + 5000, had - p * (n - 1), had - p].filter((x) => x > 0 && x !== had - p * n)).map(String) }); } const p = pick([80000, 120000, 150000, 200000]), off = pick([10, 20, 25, 50]), up = pick([10, 20, 25]); const sale = p - (p * off) / 100, final = sale + (sale * up) / 100; if (!Number.isInteger(final)) return null; return int('financial literacy', `A bag costs ${money(p)}. In a sale its price is cut by ${off}%. The next week the sale price is raised by ${up}%. What is the final price, in rupiah?`, final, { decoys: shuffle([...new Set([p, sale, final + 1000, final - 1000, final + 5000, p + (p * up) / 100 - (p * off) / 100].map(Math.round).filter((x) => x > 0 && x !== final))]).map(String) }); };
const timeQ = (y) => { const h = ri(1, 10), m = y <= 2 ? pick([0, 30]) : pick([0, 15, 30, 45]), d = y <= 2 ? pick([30, 60, 90]) : pick([25, 40, 45, 70, 95, 135]), e = h * 60 + m + d, hm = (t) => `${Math.floor(t / 60)}:${String(t % 60).padStart(2, '0')}`; return mcOnly('time', `A film starts at ${hm(h * 60 + m)} and lasts ${d >= 60 ? `${Math.floor(d / 60)} h ${d % 60 ? `${d % 60} min` : ''}`.trim() : `${d} min`}. When does it end?`, hm(e), [hm(e + 15), hm(e - 15), hm(e + 30)]); };
const fractionsQ = (y) => { const d = pick(y <= 4 ? [2, 3, 4, 5] : [3, 4, 5, 6, 8]), n = ri(1, d - 1), whole = d * ri(2, y <= 4 ? 8 : 15); return int('fractions', `${names(1)[0]} has ${whole} ${thing()}s and gives away ${n}/${d} of them. How many are given away?`, (whole / d) * n); };
const factors = () => { const kind = ri(1, 3); if (kind === 1) { const a = pick([4, 6, 8, 9, 10, 12]), b = pick([6, 8, 10, 12, 15]); if (a === b) return null; return int('factors and multiples', `What is the lowest common multiple of ${a} and ${b}?`, lcm(a, b)); } if (kind === 2) { const g = pick([4, 6, 8, 12]), a = g * pick([2, 3, 5]), b = g * pick([3, 4, 7]); if (a === b) return null; return int('factors and multiples', `What is the highest common factor of ${a} and ${b}?`, gcd(a, b)); } const ps = shuffle([2, 3, 5, 7, 11, 13, 17, 19, 23]).slice(0, 3), c = pick([4, 6, 8, 9, 10, 12, 14, 15, 21]); return mcOnly('prime or composite', `Which of these numbers is NOT prime: ${shuffle([...ps, c]).join(', ')}?`, c, ps); };
const ratioQ = () => { const a = ri(1, 4), b = ri(a + 1, 7), u = ri(2, 12); if (gcd(a, b) !== 1) return null; return int('ratio', `Blue and white paint are mixed in the ratio ${a} : ${b}. If ${a * u} litres of blue paint are used, how many litres of white paint are needed?`, b * u); };
const areaVolume = (y) => { const kind = y === 5 ? ri(1, 2) : ri(1, 3); if (kind === 1) { const l = ri(3, 12), w = ri(2, 10), h = ri(2, 8); return int('area and volume', `A box is ${l} cm long, ${w} cm wide and ${h} cm tall. What is its volume, in cm³?`, l * w * h); } if (kind === 2) { const l = ri(4, 20), w = ri(2, l); return int('area and volume', `A rectangle is ${l} cm by ${w} cm. What is its area, in cm²?`, l * w); } const r = pick([7, 14, 21]); return int('circles', `Taking π as 22/7, what is the area of a circle with radius ${r} cm, in cm²?`, (22 / 7) * r * r); };
const algebra = () => { const kind = ri(1, 2); if (kind === 1) { const a = ri(2, 9), x = ri(2, 15), b = ri(1, 20); return int('algebraic thinking', `If ${a}x + ${b} = ${a * x + b}, what is x?`, x); } const x = ri(3, 30), a = ri(2, 9); return int('algebraic thinking', `A number is multiplied by ${a} and the result is ${a * x}. What is the number?`, x); };
const speedQ = () => { const v = pick([40, 50, 60, 80]), t = ri(2, 5); return int('speed', `A train travels at ${v} km/h for ${t} hours. How far does it go, in km?`, v * t); };
const negative = () => { const t1 = ri(-9, 5), d = ri(3, 12), up = Math.random() < 0.5, v = up ? t1 + d : t1 - d; // decoys below zero too, or the one negative option gives itself away
  return int('negative numbers', `The temperature was ${t1}°C. It ${up ? 'rose' : 'fell'} by ${d}°C. What is the temperature now, in °C?`, v, { decoys: shuffle([...new Set([up ? t1 - d : t1 + d, -v, v + 2, v - 2, v + 1, v - 1, -t1].filter((x) => x !== v))]).slice(0, 5).map(String) }); };
const exponents = () => { const b = pick([2, 3, 5, 10]), n = b === 2 ? ri(3, 8) : b === 3 ? ri(2, 5) : ri(2, 4); return int('exponents', `What is ${b}^${n} (${b} to the power ${n})?`, b ** n); };
const percentQ = () => { const t = pick([40, 60, 80, 120, 200, 250]), p = pick([10, 15, 20, 25, 30, 40, 60, 75]); if ((t * p) % 100) return null; return int('percentages', `${p}% of ${t} children in a school take the bus. How many take the bus?`, (t * p) / 100); };
// the paper's tiers: Section B staples
const bracketsOps = () => { const a = ri(5, 30), b = ri(3, 20), k = ri(2, 6), c = ri(1, 40), v = (a + b) * k - c; if (v < 0) return null; return int('order of operations', `(${a} + ${b}) × ${k} − ${c} = ?`, v); };
const unitTrap = (y) => { if (y <= 2) { const cands = shuffle([[200, '2 m'], [150, '150 cm'], [180, '1 m 80 cm'], [95, '95 cm'], [120, '1 m 20 cm'], [300, '3 m'], [45, '45 cm']]).slice(0, 4), top = cands.reduce((p, q) => (q[0] > p[0] ? q : p)); return mcOnly('measurement', 'Which of these lengths is the longest?', top[1], cands.filter((c) => c !== top).map((c) => c[1])); } const lo = ri(3, 9) * 10, hi = lo + ri(4, 9) * 10, fmt = (cm) => pick([() => `${cm} cm`, () => (cm < 100 ? `${cm} cm` : cm % 100 === 0 ? `${cm / 100} m` : `${Math.floor(cm / 100)} m ${cm % 100} cm`), () => `${cm * 10} mm`])(), inside = ri(lo + 1, hi - 1), outs = shuffle([Math.max(1, lo - ri(1, 30)), hi + ri(1, 40), (lo + hi) * 3, Math.max(1, Math.floor(lo / 4))]).slice(0, 3); return mcOnly('measurement', `A rope is longer than ${fmt(lo)} and shorter than ${fmt(hi)}. Which of these could be its length?`, fmt(inside), outs.map((o) => fmt(o))); };
const statsMMR = (y) => { const xs = Array.from({ length: 5 }, () => ri(2, y <= 4 ? 20 : 60)), sorted = [...xs].sort((p, q) => p - q), kind = ri(1, 4); if (kind === 1) return int('statistics', `What is the range of ${xs.join(', ')}?`, sorted[4] - sorted[0]); if (kind === 2) return int('statistics', `What is the median of ${xs.join(', ')}?`, sorted[2]); if (kind === 3) { const t = sum(xs); if (t % 5) return null; return int('statistics', `What is the mean (average) of ${xs.join(', ')}?`, t / 5); } const counts = {}; for (const x of xs) counts[x] = (counts[x] || 0) + 1; const top = Object.entries(counts).sort((p, q) => q[1] - p[1]); if (top[0][1] < 2 || (top[1] && top[1][1] === top[0][1])) return null; return int('statistics', `What is the mode of ${xs.join(', ')}?`, Number(top[0][0])); };
const remainderSystem = () => { const [m1, m2] = pick([[6, 8], [4, 6], [5, 8], [6, 9], [3, 5], [4, 5]]), r = ri(1, Math.min(m1, m2) - 1), l = lcm(m1, m2), k = ri(1, Math.floor(200 / l)), N = k * l + r, lo = Math.floor(N / 10) * 10, m3 = pick([5, 7, 9].filter((m) => m !== m1 && m !== m2)), inRange = []; for (let x = lo; x < lo + 10; x++) if (x % m1 === r && x % m2 === r) inRange.push(x); if (inRange.length !== 1) return null; return int('remainders', `A farmer has between ${lo} and ${lo + 10} apples. Packed in bags of ${m1} there is ${r} left over, and packed in bags of ${m2} there is also ${r} left over. How many apples are left over when they are packed in bags of ${m3}?`, N % m3); };
const decimalOps = () => { const kind = ri(1, 3); if (kind === 1) { const a = ri(11, 99) / 10, b = ri(2, 9); return dec('decimals', `${a} × ${b} = ?`, a * b); } if (kind === 2) { const a = ri(11, 99) / 10, b = ri(11, 99) / 10; return dec('decimals', `${a} + ${b} = ?`, a + b); } const q = ri(2, 12), b = ri(2, 9) / 10; return dec('decimals', `${Math.round(q * b * 100) / 100} ÷ ${b} = ?`, q); };
const compositeVolume = () => { const l1 = ri(6, 15), w = ri(3, 8), h = ri(2, 6), l2 = ri(3, 10), h2 = ri(2, 6); return int('area and volume', `A solid is made of two blocks glued together: one ${l1} cm by ${w} cm by ${h} cm and one ${l2} cm by ${w} cm by ${h2} cm. What is its volume, in cm³?`, l1 * w * h + l2 * w * h2); };
const divisibleCount = () => { const ds = shuffle([1, 2, 3, 4, 5, 6, 7, 8, 9]).slice(0, ri(3, 4)).sort((p, q) => p - q), m = pick([3, 4, 5, 6, 9]); let n = 0; for (const a of ds) for (const b of ds) if ((10 * a + b) % m === 0) n++; if (n === 0) return null; return int('divisibility', `How many two-digit numbers can be made from the digits ${ds.join(', ')} (a digit may be used twice in a number) that are divisible by ${m}?`, n); };
const twoStepChart = (y) => { const labels = ['Mon', 'Tue', 'Wed', 'Thu'], vals = labels.map(() => ri(2, y <= 4 ? 9 : 20)), price = pick([2000, 2500, 5000, 10000]), i = ri(0, 2), f = bars('Books sold', null, labels.map((l, k) => [l, vals[k]])); return withFigure(int('data and graphs', `The bar chart shows the books a stall sold on four days. Each book costs ${money(price)}. How much did the stall take on ${labels[i]} and ${labels[i + 1]} together, in rupiah?`, price * (vals[i] + vals[i + 1])), f); };
const perimArea34 = () => { const l = ri(6, 20), w = ri(2, l - 1); if (ri(1, 2) === 1) return int('perimeter and area', `A rectangle has a perimeter of ${2 * (l + w)} cm and a length of ${l} cm. What is its area, in cm²?`, l * w); return int('perimeter and area', `A rectangle has an area of ${l * w} cm² and a width of ${w} cm. What is its perimeter, in cm?`, 2 * (l + w)); };
const rounding34 = () => { const n = ri(1000, 9999), to = pick([10, 100, 1000]); return int('rounding', `Round ${n} to the nearest ${to}.`, Math.round(n / to) * to); };
const diceProb = () => { const [e, right, wrong] = pick([['both dice show an even number', '1/4', ['1/2', '1/3', '1/6']], ['both dice show a prime number', '1/4', ['1/2', '1/9', '1/6']], ['the two numbers add up to 7', '1/6', ['1/12', '1/4', '7/36']], ['both dice show the same number', '1/6', ['1/36', '1/12', '1/3']], ['both dice show a number greater than 4', '1/9', ['1/3', '1/6', '4/9']], ['the two numbers add up to 12', '1/36', ['1/12', '1/6', '2/36']]]); return mcOnly('probability', `Two fair dice are rolled. What is the probability that ${e}?`, right, wrong); };

// ---- the pools: Section A by tier (six-mark A6, eight-mark A8), Section B ----
const A = (y) => {
  const rows = [], add = (cat, gen, ...sections) => rows.push({ cat, gen, sections });
  if (y <= 2) { add('order and direction', lineUp, 'A6'); add('patterns', shapePattern, 'A6'); add('odd one out', oddOne, 'A6'); add('balance puzzles', balance, 'A6', 'A8'); add('calendar logic', calendar, 'A6'); add('math puzzle', puzzle, 'A6'); add('counting', legs, 'A6'); add('number sequences', interleaved, 'A6', 'A8'); add('rule machine', ruleGuess, 'A8'); add('position in a row', positionRow, 'A8'); add('assumption method', assumption, 'A8'); add('three balances', threeBalances, 'A8'); add('counting figures', countFigures, 'A6', 'A8'); }
  else if (y <= 4) { add('order and direction', lineUp, 'A6'); add('patterns', shapePattern, 'A6'); add('odd one out', oddOne, 'A6'); add('calendar logic', calendar, 'A6'); add('math puzzle', puzzle, 'A6'); add('counting', countRange, 'A6'); add('number sequences', interleaved, 'A6'); add('rule machine', ruleGuess, 'A6', 'A8'); add('order of operations', orderOps, 'A6'); add('balance puzzles', balance, 'A8'); add('ages', ages, 'A8'); add('logic', truth, 'A8'); add('position in a row', positionRow, 'A8'); add('assumption method', assumption, 'A8'); add('three balances', threeBalances, 'A8'); add('symbol equations', symbolEq, 'A8'); add('adjacent sums', adjacentRing, 'A8'); add('counting figures', countFigures, 'A6', 'A8'); }
  else { add('number sequences', interleaved, 'A6'); add('rule machine', ruleGuess, 'A6'); add('order of operations', orderOps, 'A6'); add('calendar logic', calendar, 'A6'); add('math puzzle', puzzle, 'A6'); add('counting', countRange, 'A6'); add('odd one out', oddOne, 'A6'); add('ages', ages, 'A8'); add('logic', truth, 'A8'); add('position in a row', positionRow, 'A8'); add('assumption method', assumption, 'A8'); add('three balances', threeBalances, 'A8'); add('symbol equations', symbolEq, 'A8'); add('adjacent sums', adjacentRing, 'A8'); add('counting figures', countFigures, 'A8'); add('balance puzzles', balance, 'A8'); }
  return rows;
};
const B = (y) => {
  const rows = [['word problems', addSubWords], ['data and graphs', dataQ], ['time', timeQ], ['measurement', unitTrap]];
  if (y === 1) rows.push(['shapes', shapesQ]);
  if (y >= 2 && y <= 4) rows.push(['multiplication and division', mulDiv]);
  if (y >= 3) rows.push(['units', measure], ['money', moneyQ], ['fractions', fractionsQ], ['two-step charts', twoStepChart]);
  if (y >= 3 && y <= 4) rows.push(['brackets', bracketsOps], ['perimeter and area', perimArea34], ['rounding', rounding34]);
  if (y >= 4) rows.push(['statistics', statsMMR]);
  if (y >= 5) rows.push(['factors and multiples', factors], ['ratio', ratioQ], ['area and volume', areaVolume], ['composite solids', compositeVolume], ['probability', diceProb], ['algebraic thinking', algebra], ['financial literacy', moneyQ], ['remainders', remainderSystem], ['decimals', decimalOps], ['divisibility', divisibleCount]);
  if (y >= 6) rows.push(['speed', speedQ], ['negative numbers', negative], ['exponents', exponents], ['percentages', percentQ]);
  return rows.map(([cat, gen]) => ({ cat, gen, sections: ['B'] }));
};
// the paper's shape in miniature: three six-mark and two eight-mark logic questions, then five ten-mark applications, all four-option
const SHAPE = slots([['A6', 'mc', 3], ['A8', 'mc', 2], ['B', 'mc', 5]]);
export const heat = (year) => buildHeat(SHAPE, [...A(year), ...B(year)], year, { options: 4 });
export const TOPICS = [
  { band: 'Grades 1–2', lines: ['A, 6 marks: who is second in the line, the next shape, the odd one out, balance puzzles, two sequences woven together', 'A, 8 marks: a rule machine, the centre of a row, shamrocks and clovers, three balances, squares in a grid', 'B: adding and taking away in words, the longest length, picture graphs, what time a film ends', 'B: equal groups, sides of shapes'] },
  { band: 'Grades 3–4', lines: ['A, 6 marks: four in a line, sequences woven together, rule machines, order of operations, calendars', 'A, 8 marks: ages, who is lying, the centre of a row, quiz scores, three balances, symbol equations, adjacent sums', 'B: metres and centimetres, a rope between two lengths, bar charts then money, brackets', 'B: rupiah left after shopping, fractions of a set, perimeter and area, rounding, mean and median'] },
  { band: 'Grades 5–6', lines: ['A, 6 marks: sequences woven together, rule machines, order of operations, primes among the numbers', 'A, 8 marks: ages, who is lying, symbol equations, adjacent sums, three balances, squares in a grid', 'B: LCM and HCF, ratio of paints, glued blocks, two dice, remainders in bags, decimals, digits that divide', 'B (Grade 6): speed, temperatures below zero, powers, percentages'] },
];
